// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Stack',
	displayName: 'Stack',
	keywords: [
		'stack',
		'hstack',
		'vstack',
		'flexbox',
		'flex',
		'spacing',
		'gap',
		'horizontal',
		'vertical',
		'row',
		'column'
	],
	group: 'Layout',
	category: 'Layout',
	theming: {
		targets: [
			{
				className: 'astryx-stack',
				visualProps: ['direction', 'gap', 'wrap']
			},
			{
				className: 'astryx-stack-item',
				visualProps: ['size']
			}
		]
	},
	usage: {
		description:
			'Stack arranges items in a row or column with consistent spacing. Use the gap prop to control the space between items.',
		bestPractices: [
			{
				guidance: true,
				description: "Use the gap prop for spacing between items; don't add margins manually."
			},
			{
				guidance: true,
				description:
					'Use StackItem with size="fill" to make one item stretch and fill the leftover space.'
			},
			{
				guidance: false,
				description:
					'Nest stacks inside stacks; try wrap="wrap" first to let items flow to the next line.'
			}
		]
	},
	props: [
		{
			name: 'direction',
			type: "'horizontal' | 'vertical'",
			description:
				"Direction of the stack layout. 'horizontal' flows items left-to-right (like HStack), 'vertical' flows top-to-bottom (like VStack). Note: the value is 'horizontal', NOT 'row'.",
			default: "'vertical'"
		},
		{
			name: 'gap',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Spacing step (number literal): 0, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 8, 10. Pass as a JSX number expression e.g. gap={4}, NOT a string like gap="4".'
		},
		{
			name: 'padding',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Inner padding on all sides, using the spacing scale. Pass as a JSX number expression e.g. padding={3}.'
		},
		{
			name: 'paddingInline',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Inline (horizontal) padding. Overrides padding on the inline axis when both are set.'
		},
		{
			name: 'paddingInlineStart',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Inline-start padding, using the spacing scale (left in LTR, right in RTL). Overrides paddingInline and padding on that edge only.'
		},
		{
			name: 'paddingInlineEnd',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Inline-end padding, using the spacing scale (right in LTR, left in RTL). Overrides paddingInline and padding on that edge only.'
		},
		{
			name: 'paddingBlock',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Block (vertical) padding. Overrides padding on the block axis when both are set.'
		},
		{
			name: 'paddingBlockStart',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Block-start (top) padding, using the spacing scale. Overrides paddingBlock and padding on that edge only.'
		},
		{
			name: 'paddingBlockEnd',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Block-end (bottom) padding, using the spacing scale. Overrides paddingBlock and padding on that edge only.'
		},
		{
			name: 'isScrollable',
			type: 'boolean',
			description: 'Enables scrollable overflow (overflow: auto).',
			default: 'false'
		},
		{
			name: 'width',
			type: 'SizeValue',
			description:
				"Width of the stack container. Numbers are treated as pixels, strings are used as-is (e.g., '100%')."
		},
		{
			name: 'height',
			type: 'SizeValue',
			description:
				"Height of the stack container. Numbers are treated as pixels, strings are used as-is (e.g., '100%')."
		},
		{
			name: 'maxWidth',
			type: 'SizeValue',
			description: 'Maximum width of the stack container.'
		},
		{
			name: 'minHeight',
			type: 'SizeValue',
			description: 'Minimum height of the stack container.'
		},
		{
			name: 'hAlign',
			type: "'end' | 'start' | 'center' | 'stretch' | 'between' | 'around' | 'evenly'",
			description:
				"Horizontal alignment. When direction='horizontal': main-axis (justify-content). When direction='vertical': cross-axis (align-items)."
		},
		{
			name: 'vAlign',
			type: "'end' | 'start' | 'center' | 'stretch' | 'between' | 'around' | 'evenly'",
			description:
				"Vertical alignment. When direction='horizontal': cross-axis (align-items). When direction='vertical': main-axis (justify-content)."
		},
		{
			name: 'justify',
			type: "'end' | 'start' | 'center' | 'between' | 'around' | 'evenly'",
			description:
				"Main-axis alignment alias. Resolves to hAlign (horizontal) or vAlign (vertical). Note: use 'between', NOT 'space-between'."
		},
		{
			name: 'align',
			type: "'end' | 'start' | 'center' | 'stretch'",
			description: 'Cross-axis alignment alias. Mirrors CSS align-items.'
		},
		{
			name: 'wrap',
			type: "'wrap' | 'nowrap' | 'wrap-reverse'",
			description: 'Flex wrap behavior.',
			default: "'nowrap'"
		},
		{
			name: 'as',
			type: "'object' | 'title' | 'slot' | 'style' | 'small' | 'header' | 'menu' | 'search' | 'button' | 'article' | 'dialog' | 'figure' | 'form' | 'img' | 'link' | 'main' | 'option' | 'table' | 'label' | 'base' | 'body' | 'code' | 'time' | 'section' | 'input' | 'strong' | 'div' | 'li' | 'span' | 'blockquote' | 'hr' | 'a' | 'abbr' | 'address' | 'area' | 'aside' | 'audio' | 'b' | 'bdi' | 'bdo' | 'br' | 'canvas' | 'caption' | 'cite' | 'col' | 'colgroup' | 'data' | 'datalist' | 'dd' | 'del' | 'details' | 'dfn' | 'dl' | 'dt' | 'em' | 'embed' | 'fieldset' | 'figcaption' | 'footer' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'head' | 'hgroup' | 'html' | 'i' | 'iframe' | 'ins' | 'kbd' | 'legend' | 'map' | 'mark' | 'meta' | 'meter' | 'nav' | 'noscript' | 'ol' | 'optgroup' | 'output' | 'p' | 'picture' | 'pre' | 'progress' | 'q' | 'rp' | 'rt' | 'ruby' | 's' | 'samp' | 'script' | 'select' | 'source' | 'sub' | 'summary' | 'sup' | 'tbody' | 'td' | 'template' | 'textarea' | 'tfoot' | 'th' | 'thead' | 'tr' | 'track' | 'u' | 'ul' | 'var' | 'video' | 'wbr'",
			description: 'HTML element to render as the stack container.',
			default: "'div'"
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Stack content.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
