// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'SideNav',
	displayName: 'Side Nav',
	keywords: [
		'sidenav',
		'sidebar',
		'navigation',
		'drawer',
		'menu',
		'nav',
		'aside',
		'sidemenu',
		'navmenu',
		'sider',
		'treeview'
	],
	group: 'Navigation',
	category: 'Navigation',
	theming: {
		targets: [
			{
				className: 'astryx-side-nav',
				visualProps: ['mode']
			},
			{
				className: 'astryx-side-nav-heading'
			},
			{
				className: 'astryx-side-nav-item',
				visualProps: ['size'],
				states: ['selected']
			},
			{
				className: 'astryx-side-nav-section'
			}
		]
	},
	usage: {
		description:
			'A sidebar navigation component for organizing application pages with sections, nested items, and icons. Use SideNav as the primary navigation when an app has 5 or more destinations or requires hierarchical grouping.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use sections to group related navigation items and help users scan for their destination.'
			},
			{
				guidance: true,
				description:
					'Pair outline and filled icon variants so the selected state is visually distinct.'
			},
			{
				guidance: false,
				description:
					'Include a SideNavHeading when a TopNav is already providing app identity; this duplicates branding.'
			},
			{
				guidance: false,
				description: 'Use for filtering content; use tabs or filter buttons instead.'
			}
		],
		anatomy: [
			{
				name: 'Product icon and name',
				required: false,
				description: 'Branding area at the top of the nav.'
			},
			{
				name: 'Navigation items',
				required: true,
				description: 'Sections and groups of navigable links.'
			},
			{
				name: 'Collapse/expand toggle',
				required: false,
				description: 'Toggle to collapse or expand the side nav.'
			}
		]
	},
	props: [
		{
			name: 'header',
			type: 'Snippet',
			description: 'Header area (typically SideNavHeading). Sticky.'
		},
		{
			name: 'topContent',
			type: 'Snippet',
			description: 'Content below the header, e.g., a create button.'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Navigation sections and items. Scrollable.'
		},
		{
			name: 'footer',
			type: 'Snippet',
			description: 'Footer area above the icon bar.'
		},
		{
			name: 'footerIcons',
			type: 'Snippet',
			description: 'Footer icon bar.'
		},
		{
			name: 'collapsible',
			type: 'boolean | { defaultIsCollapsed?: boolean; isCollapsed?: boolean; onCollapsedChange?: (isCollapsed: boolean) => void; hasButton?: boolean; buttonLabel?: string; }',
			description:
				'Enables collapse behavior. true for uncontrolled with default toggle button, or an object for controlled mode and advanced config (defaultIsCollapsed, isCollapsed + onCollapsedChange, hasButton, buttonLabel).',
			default: 'false'
		},
		{
			name: 'resizable',
			type: 'boolean | ResizableConfig',
			description:
				'Enables a resize handle at the inline-end edge. true for defaults (260px initial, 180-480px range), or a ResizableConfig object (defaultWidth, minWidth, maxWidth, autoSaveId for localStorage persistence, onWidthChange). The handle is hidden while collapsed.',
			default: 'false'
		},
		{
			name: 'handleRef',
			type: 'SideNavImperativeCollapseHandle | null',
			description:
				'Imperative collapse handle for SideNavCollapseButton instances rendered outside this SideNav. Separate from `ref`, which continues to expose the root HTMLElement.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
