// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'SideNavItem',
	displayName: 'Side Nav Item',
	subComponentOf: 'SideNav',
	description:
		'Navigation item with icon, selected state, optional end content, and nesting support via children.',
	keywords: [
		'sidenav',
		'sidebar',
		'navigation',
		'drawer',
		'menu',
		'nav',
		'aside',
		'sidemenu',
		'navmenu',
		'sider',
		'treeview'
	],
	group: 'Navigation',
	category: 'Navigation',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'label',
			type: 'string',
			description: 'Item label.',
			required: true
		},
		{
			name: 'as',
			type: 'LinkComponentType',
			description: 'Custom link component.'
		},
		{
			name: 'icon',
			type: 'IconName | Snippet',
			description:
				'Icon displayed in the outline (unselected) variant. See `astryx docs icons` for valid semantic names.'
		},
		{
			name: 'selectedIcon',
			type: 'IconName | Snippet',
			description:
				'Icon displayed when the item is selected (filled variant). See `astryx docs icons` for valid semantic names.'
		},
		{
			name: 'isSelected',
			type: 'boolean',
			description: 'Marks this item as the current page.',
			default: 'false'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Disabled state.',
			default: 'false'
		},
		{
			name: 'href',
			type: 'string',
			description: 'Navigation URL.'
		},
		{
			name: 'onclick',
			type: '(event: MouseEvent) => void',
			description: 'Click handler.'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Right-side content such as badges or counts.'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Sub-items for nesting.'
		},
		{
			name: 'collapsible',
			type: 'boolean | { defaultIsCollapsed?: boolean; isCollapsed?: boolean; onCollapsedChange?: (isCollapsed: boolean) => void; }',
			description:
				'Enables collapse behavior for items with children. Pass true for uncontrolled (starts expanded), or an object for controlled mode.',
			default: 'false'
		}
	]
};
