// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'SideNavCollapseButton',
	displayName: 'Side Nav Collapse Button',
	subComponentOf: 'SideNav',
	description:
		'Toggle button for sidenav collapse. Place inside SideNav (reads context automatically) or outside it (hand the same controlled collapsible config to both). Renders as an icon-only ghost button by default.',
	keywords: [
		'sidenav',
		'sidebar',
		'navigation',
		'drawer',
		'menu',
		'nav',
		'aside',
		'sidemenu',
		'navmenu',
		'sider',
		'treeview'
	],
	group: 'Navigation',
	category: 'Navigation',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'collapsible',
			type: 'SideNavControlledCollapsible',
			description:
				'The same controlled collapsible config passed to SideNav. Only needed when the button is rendered outside the sidenav, where collapse context cannot reach it.'
		},
		{
			name: 'handleRef',
			type: 'SideNavImperativeCollapseHandle | null',
			description: 'Deprecated. Imperative collapse handle from SideNav; pass collapsible instead.'
		},
		{
			name: 'label',
			type: 'string',
			description:
				'Custom button label. When provided, renders as a text button with chevron. When omitted, renders icon-only.'
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description:
				"Button size. Defaults to the size its container cascades ('sm' inside a SideNav footer) and to 'md' with no container. Set it when the button sits outside a sized container and has to match its neighbours."
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Custom button content. Overrides the default chevron icon and label.'
		}
	]
};
