// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'SideNavSection',
	displayName: 'Side Nav Section',
	subComponentOf: 'SideNav',
	description: 'Section grouping with an optional title, subtitle, and end content.',
	keywords: [
		'sidenav',
		'sidebar',
		'navigation',
		'drawer',
		'menu',
		'nav',
		'aside',
		'sidemenu',
		'navmenu',
		'sider',
		'treeview'
	],
	group: 'Navigation',
	category: 'Navigation',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'title',
			type: 'string',
			description: 'Section title.',
			required: true
		},
		{
			name: 'subtitle',
			type: 'string',
			description: 'Section subtitle.'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Section items.'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Right-side content in the section header.'
		},
		{
			name: 'isHeaderHidden',
			type: 'boolean',
			description:
				'Visually hides the section header while keeping it accessible to screen readers.',
			default: 'false'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
