// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'GridSpan',
	displayName: 'Grid Span',
	subComponentOf: 'Grid',
	description: 'Grid item that spans multiple columns or rows.',
	keywords: [
		'grid',
		'columns',
		'responsive',
		'auto-fill',
		'auto-fit',
		'masonry',
		'tiles',
		'row',
		'col',
		'simplegrid',
		'responsive grid',
		'card grid'
	],
	group: 'Layout',
	category: 'Layout',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			columns: 2,
			children: 'Spans 2 columns'
		},
		wrapper: {
			component: 'Grid',
			props: {
				columns: 3,
				gap: 2
			}
		}
	},
	props: [
		{
			name: 'columns',
			type: "number | 'full'",
			description: "Columns to span; use `'full'` to span the entire row."
		},
		{
			name: 'rows',
			type: 'number',
			description: 'Rows to span.'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Content.'
		}
	]
};
