// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'useTableTreeData',
	displayName: 'useTableTreeData',
	subComponentOf: 'Table',
	description:
		'Headless tree plugin for Table: renders nested rows with per-level indentation and expand/collapse chevrons in the tree column (the first column by default), and reflects hierarchy on body rows via aria-level and aria-expanded. Composable with the other Table plugins: the canonical plugin order places tree before selection, so the checkbox column lands left of the indented tree column. Feed it the treeConfig from useTableTreeState, or construct the config directly for server-driven or pre-flattened trees. When no row is expandable (flat data), every transform is a pass-through and the table renders identically to one without the plugin. Known limitation: the tree column wraps its cell content, so textOverflow="truncate" tooltips do not apply within the tree column.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	props: [
		{
			name: 'getRowMeta',
			type: '(item: T) => TableTreeRowMeta',
			description:
				'Structural meta for a visible row: {id, level (0-based), hasChildren, isExpanded}.',
			required: true
		},
		{
			name: 'onToggleItem',
			type: '(item: T) => void',
			description: "Toggle a row's expansion.",
			required: true
		},
		{
			name: 'hasExpandableRows',
			type: 'boolean',
			description:
				'Whether any row in the dataset is expandable. When false the plugin is a no-op: no expanders, no indent, no tree ARIA.',
			required: true
		},
		{
			name: 'hasExpandAllControl',
			type: 'boolean',
			description:
				'Show an expand-all/collapse-all toggle in the tree column header. Requires isAllExpanded plus onExpandAll/onCollapseAll (all supplied by useTableTreeState).',
			default: 'false'
		},
		{
			name: 'isAllExpanded',
			type: "boolean | 'indeterminate'",
			description:
				'Aggregate expansion state across every expandable row, driving the header expand-all toggle. true when all are expanded, false when none are, indeterminate when some are.'
		},
		{
			name: 'onExpandAll',
			type: '() => void',
			description: 'Expand every expandable row. Wired to the header control.'
		},
		{
			name: 'onCollapseAll',
			type: '() => void',
			description: 'Collapse every row. Wired to the header control.'
		},
		{
			name: 'indent',
			type: "'sm' | 'md' | 'lg'",
			description: 'Indent step per level, mapped to the spacing-3 / spacing-4 / spacing-6 tokens.',
			default: "'md'"
		},
		{
			name: 'treeColumnKey',
			type: 'string',
			description: 'Column that carries the indent + expander. Defaults to the first column.'
		},
		{
			name: 'hasRowClickExpansion',
			type: 'boolean',
			description:
				'When true, clicking anywhere on an expandable row toggles its expansion, in addition to the chevron. A pointer-only convenience: keyboard and assistive-tech users toggle via the chevron button. Clicks on interactive cell content (buttons, links, form controls) or a text selection do not toggle. Leaf rows stay inert, and it is a no-op on flat data.',
			default: 'false'
		}
	]
};
