// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Banner',
	displayName: 'Banner',
	keywords: [
		'banner',
		'alert',
		'notification',
		'callout',
		'notice',
		'status',
		'message',
		'info',
		'warning',
		'error',
		'success',
		'toast'
	],
	category: 'Feedback & Status',
	theming: {
		targets: [
			{
				className: 'astryx-banner',
				visualProps: ['container', 'status']
			},
			{
				className: 'astryx-banner-icon',
				visualProps: ['status']
			},
			{
				className: 'astryx-banner-content',
				visualProps: ['container', 'status']
			}
		],
		vars: [
			{
				name: '--_banner-radius',
				description: 'Border radius (card container only)',
				default: 'var(--radius-container)',
				private: true
			}
		],
		derived: [
			{
				property: 'borderRadius',
				vars: ['--_banner-radius']
			}
		]
	},
	usage: {
		description:
			'Banner shows a persistent message at the top of a page or section. Use it for form errors, system updates, maintenance notices, or success confirmations that the user needs to see until they act on it.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Pick a status that matches the message: info for updates, warning for caution, error for problems, success for confirmations.'
			},
			{
				guidance: true,
				description:
					'Use the card container inside page content and the section container for full-width messages that span the entire page.'
			},
			{
				guidance: true,
				description:
					'Make info and success banners dismissable. Keep error banners visible until the user fixes the issue.'
			},
			{
				guidance: true,
				description:
					'Keep titles short and scannable: "Payment failed" not "There was a problem processing your most recent payment."'
			},
			{
				guidance: false,
				description:
					'Use Banner for short-lived messages that disappear on their own; use Toast instead.'
			},
			{
				guidance: false,
				description:
					'Stack multiple banners with the same status; combine related messages into one banner.'
			}
		],
		anatomy: [
			{
				name: 'Icon',
				required: true,
				description: 'Automatically set based on the status (info, warning, error, success).'
			},
			{
				name: 'Title',
				required: false,
				description: 'The main message. Required if no description is provided.'
			},
			{
				name: 'Description',
				required: false,
				description: 'Additional detail below the title. Required if no title is provided.'
			},
			{
				name: 'Action button',
				required: false,
				description: 'A button for the user to act on the message, like "Review" or "Retry".'
			},
			{
				name: 'Dismiss button',
				required: false,
				description: 'Lets the user close the banner. Enabled by setting isDismissable.'
			},
			{
				name: 'Collapsible content',
				required: false,
				description: 'Extra detail that expands below the banner header, like a list of errors.'
			}
		]
	},
	playground: {
		defaults: {
			title: 'System maintenance scheduled',
			description: 'The platform will be briefly unavailable on Sunday from 2–4 AM PST.',
			status: 'info'
		}
	},
	props: [
		{
			name: 'status',
			type: "'success' | 'error' | 'warning' | 'info'",
			description: 'Status type controlling icon and color.',
			required: true
		},
		{
			name: 'title',
			type: 'string | Snippet',
			description: 'Title text or ReactNode displayed in the header.',
			required: true
		},
		{
			name: 'description',
			type: 'string | Snippet',
			description: 'Description text rendered below the title in the header.'
		},
		{
			name: 'icon',
			type: 'Snippet',
			description: 'Override the default status icon.'
		},
		{
			name: 'isDismissable',
			type: 'boolean',
			description: 'Whether the banner can be dismissed by the user.',
			default: 'false'
		},
		{
			name: 'onDismiss',
			type: '() => void',
			description:
				'Called when the dismiss button is clicked; banner hides itself regardless of whether this is provided.'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description:
				'Action content rendered in the header area, end-aligned. Typically a button or link.'
		},
		{
			name: 'container',
			type: "'section' | 'card'",
			description:
				'Container type: card has border-radius; section is full-width with no border-radius for page-level use.',
			default: "'card'"
		},
		{
			name: 'elevation',
			type: "'none' | 'low' | 'med' | 'high'",
			description:
				'Resting shadow depth. Use for a floating banner that hovers above content; `none` is the default inline banner. A `card`-container banner rounds its shadow to match.',
			default: "'none'"
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Content rendered in the card-background area below the colored header.'
		},
		{
			name: 'defaultIsExpanded',
			type: 'boolean',
			description:
				'Whether the content area (children) starts expanded. Only relevant when children are provided.',
			default: 'false'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
