// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'MetadataList',
	displayName: 'Metadata List',
	keywords: [
		'metadata',
		'description',
		'definition',
		'keyvalue',
		'properties',
		'details',
		'attributes',
		'summary'
	],
	group: 'MetadataList',
	category: 'Table & List',
	theming: {
		targets: [
			{
				className: 'astryx-metadata-list',
				visualProps: ['columns', 'orientation']
			},
			{
				className: 'astryx-metadata-list-item'
			}
		]
	},
	usage: {
		description:
			'MetadataList displays key-value pairs for object attributes like quality, condition, and status, in a structured layout. Use it for detail panels, settings summaries, and record information.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Choose label position based on content: "start" for short values, "top" for long or complex values.'
			},
			{
				guidance: true,
				description: 'Collapse long lists with `maxNumOfItems` to keep the page scannable.'
			},
			{
				guidance: false,
				description: 'Use for extensive form input; use a form layout instead.'
			},
			{
				guidance: false,
				description: "Use for data that doesn't have a clear key-value structure."
			}
		],
		anatomy: [
			{
				name: 'Title',
				required: false,
				description: 'Optional title for the metadata list.'
			},
			{
				name: 'Label',
				required: true,
				description: 'The key label for each metadata entry.'
			},
			{
				name: 'Metadata',
				required: true,
				description: 'The value displayed in various formats.'
			},
			{
				name: 'Disclosure',
				required: false,
				description: 'Collapse/expand control for the list.'
			}
		]
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Metadata items (MetadataListItem components).',
			required: true
		},
		{
			name: 'columns',
			type: "number | 'single' | 'multi'",
			description: 'Column layout mode.',
			default: "'single'"
		},
		{
			name: 'label',
			type: 'MetadataListLabelConfig',
			description:
				"Label display configuration. position controls label placement, width sets a custom label column width. Defaults to { position: 'top' } for multi-column layouts.",
			default: "{ position: 'start' } (single-column) / { position: 'top' } (multi-column)"
		},
		{
			name: 'maxNumOfItems',
			type: 'number',
			description: 'Maximum items to show before collapsing with a show more/less toggle.'
		},
		{
			name: 'orientation',
			type: "'horizontal' | 'vertical'",
			description: 'Layout orientation. Horizontal mode flows items in a row with flex-wrap.',
			default: "'vertical'"
		},
		{
			name: 'title',
			type: 'Snippet',
			description: 'Optional title or heading above the list.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for layout customization. Must be a stylex.create() value.'
		}
	]
};
