// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'MetadataListItem',
	displayName: 'Metadata List Item',
	subComponentOf: 'MetadataList',
	description: 'A single labeled metadata value within an MetadataList.',
	keywords: [
		'metadata',
		'description',
		'definition',
		'keyvalue',
		'properties',
		'details',
		'attributes',
		'summary'
	],
	group: 'MetadataList',
	category: 'Table & List',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			label: 'Status',
			children: 'Active'
		},
		wrapper: {
			component: 'MetadataList'
		}
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Content value for this metadata item.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description: 'Label text for this metadata item.',
			required: true
		},
		{
			name: 'icon',
			type: 'Snippet',
			description: 'Icon rendered before the label text.'
		}
	]
};
