// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'CollapsibleGroup',
	displayName: 'Collapsible Group',
	subComponentOf: 'Collapsible',
	description:
		'Coordinates multiple Collapsible instances so only one (single mode) or any number (multiple mode) can be open at a time. Renders no wrapper DOM element unless dividers are enabled.',
	keywords: [
		'accordion',
		'collapse',
		'expandable',
		'disclosure',
		'toggle',
		'panel',
		'foldable',
		'expander',
		'expand'
	],
	group: 'Collapsible',
	category: 'Container',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'type',
			type: "'single' | 'multiple'",
			description: 'Whether one or many items can be open simultaneously.',
			default: "'single'"
		},
		{
			name: 'defaultValue',
			type: 'string | string[]',
			description:
				'Default open item(s) for uncontrolled usage. Use a string for single mode and an array for multiple mode.'
		},
		{
			name: 'value',
			type: 'string | string[]',
			description: 'Controlled open item(s).'
		},
		{
			name: 'onChange',
			type: '(value: string | string[]) => void',
			description: 'Callback invoked when the set of open items changes.'
		},
		{
			name: 'hasDividers',
			type: 'boolean',
			description:
				"Whether to draw hairline dividers between the group's items. When set, the group renders a wrapper div and items default to 'balanced' density. Pair with bare Collapsible children; Card-wrapped items provide their own separation.",
			default: 'false'
		},
		{
			name: 'density',
			type: "'compact' | 'balanced' | 'spacious'",
			description:
				"Row density controlling trigger and content block padding on the group's items. Defaults to 'balanced' when dividers are shown; otherwise items keep their default unpadded look."
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Collapsible instances to coordinate.',
			required: true
		}
	]
};
