// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useCollapsible',
	displayName: 'useCollapsible',
	group: 'Collapsible',
	keywords: ['collapsible', 'collapse', 'expand', 'toggle', 'accordion', 'disclosure', 'fold'],
	params: [
		{
			name: 'isCollapsible',
			type: 'boolean | CollapsibleConfig',
			description:
				'Enable collapsible behavior. true = self-managed (starts open). Pass config object for controlled mode or custom defaults.'
		},
		{
			name: 'value',
			type: 'string',
			description:
				'Unique identifier within an CollapsibleGroup. When present and inside a group, state is managed by the group.'
		}
	],
	returns: [
		{
			name: 'isEnabled',
			type: 'boolean',
			description: 'Whether collapsible behavior is active.'
		},
		{
			name: 'isOpen',
			type: 'boolean',
			description: 'Whether the content is currently expanded.'
		},
		{
			name: 'toggle',
			type: '() => void',
			description:
				'Toggle open/closed state. Dispatches to group, controlled callback, or internal state.'
		}
	],
	usage: {
		description:
			'Reusable hook that encapsulates the collapsible state machine. Supports three modes: group-controlled (inside CollapsibleGroup), controlled (isOpen + onOpenChange), and uncontrolled (self-managed with defaultIsOpen). Used internally by Card and Section.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use the hook directly when building custom collapsible components that need Astryx collapsible behavior without Collapsible wrapper.'
			},
			{
				guidance: true,
				description:
					'For accordion behavior, wrap items in CollapsibleGroup and pass unique value props.'
			},
			{
				guidance: false,
				description:
					'Implement your own open/close state when useCollapsible already provides it; the hook handles group coordination automatically.'
			}
		]
	},
	relatedComponents: ['Collapsible', 'Card', 'Section'],
	importPath: '@astryx-svelte/core',
	category: 'interaction'
};
