// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Markdown',
	displayName: 'Markdown',
	keywords: [
		'markdown',
		'rich text',
		'prose',
		'renderer',
		'streaming',
		'markup',
		'formatted text',
		'md',
		'markdown renderer'
	],
	category: 'Content',
	theming: {
		targets: [
			{
				className: 'astryx-markdown',
				visualProps: ['density']
			},
			{
				className: 'astryx-markdown-heading',
				visualProps: ['density', 'level']
			},
			{
				className: 'astryx-markdown-paragraph',
				visualProps: ['density']
			},
			{
				className: 'astryx-markdown-list',
				visualProps: ['density']
			},
			{
				className: 'astryx-markdown-codeblock',
				visualProps: ['density']
			},
			{
				className: 'astryx-markdown-blockquote',
				visualProps: ['density']
			},
			{
				className: 'astryx-markdown-table',
				visualProps: ['density']
			},
			{
				className: 'astryx-markdown-hr',
				visualProps: ['density']
			},
			{
				className: 'astryx-markdown-image',
				visualProps: ['density']
			}
		]
	},
	usage: {
		description:
			'Renders a markdown string as Astryx-styled components. Use Markdown for user-generated content, AI responses, and documentation; it handles headings, lists, tables, code blocks, and citations with consistent styling.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Set headingLevelStart to match the page hierarchy, e.g. start at 3 if the markdown sits inside an h2 section.'
			},
			{
				guidance: true,
				description: 'Use contentWidth to keep prose at a readable line length in wide layouts.'
			},
			{
				guidance: true,
				description:
					'Use inlinePlugins for custom shorthand patterns like issue refs, diff refs, and mentions instead of preprocessing the markdown string.'
			},
			{
				guidance: true,
				description:
					'Pair with Outline and useOutlineFromMarkdown for section navigation: headings render generated id attributes that match the outline item ids, so hash links scroll to their target.'
			},
			{
				guidance: false,
				description:
					'Use Markdown for hand-authored layouts; use Text and Heading directly when you control the content.'
			}
		]
	},
	playground: {
		defaults: {
			children:
				"## Getting Started\n\nInstall the package:\n\n```bash\nnpm install @astryx-svelte/core\n```\n\nThen import and use any component:\n\n```tsx\nimport {Button} from '@astryx-svelte/core';\n```\n\n**Bold**, *italic*, and `inline code` all work."
		}
	},
	props: [
		{
			name: 'children',
			type: 'string',
			description: 'The markdown string to render.',
			required: true
		},
		{
			name: 'display',
			type: "'inline' | 'block'",
			description:
				"Display type. Markdown defaults to block. Use 'inline' for markdown spans embedded inside text.",
			default: "'block'"
		},
		{
			name: 'density',
			type: "'compact' | 'default'",
			description: 'Controls spacing between block-level elements.',
			default: "'default'"
		},
		{
			name: 'headingLevelStart',
			type: '1 | 2 | 3 | 4 | 5 | 6',
			description:
				'The HTML heading level that markdown # maps to. Shifts all heading levels down to fit the surrounding page hierarchy. Levels exceeding h6 are clamped to h6.',
			default: '1'
		},
		{
			name: 'isStreaming',
			type: 'boolean',
			description:
				'Enables streaming mode; it uses incremental parsing and a smooth fade-in animation for chunk-by-chunk text delivery.',
			default: 'false'
		},
		{
			name: 'onLinkClick',
			type: '(href: string, event: MouseEvent) => void | false',
			description:
				'Handler for link clicks. Return false to prevent the default navigation behavior.'
		},
		{
			name: 'sources',
			type: 'Record<string, MarkdownSource>',
			description:
				'Citation sources keyed by ID. When provided, [id] and 【id】 markers in the markdown that match a key are rendered as citation chips.'
		},
		{
			name: 'citationStyle',
			type: "'number' | 'label'",
			description:
				"How citations are displayed inline. 'label' shows a chip with source title, icon, and border. 'number' shows a compact numbered badge.",
			default: "'label'"
		},
		{
			name: 'contentWidth',
			type: 'number | string',
			description:
				'Max width for prose content (paragraphs, headings, lists, blockquotes). Tables and code blocks are unconstrained and can expand to the full container width. Use for readable line lengths in wide layouts.',
			default: '680'
		},
		{
			name: 'contentAlign',
			type: "'start' | 'center'",
			description:
				'Alignment of prose content within the container when contentWidth is narrower than the available space.',
			default: "'start'"
		},
		{
			name: 'inlinePlugins',
			type: 'MarkdownInlinePlugin[]',
			description:
				'Transforms regex matches in parsed text nodes into custom inline React elements. Use for issue refs, diff refs, mentions, and other shorthand patterns. Inline code and fenced code blocks are unaffected.'
		},
		{
			name: 'autolink',
			type: "'gfm'",
			description:
				"Opt-in autolinking of bare URLs and emails. 'gfm' applies GitHub-Flavored Markdown autolink-literal rules: bare https?://..., www...., <scheme:url>, <email>, and user@host all become links. Trailing sentence punctuation and unbalanced trailing close-parens are excluded; matches inside code spans, code blocks, existing links, and image alt text are skipped. Default behavior (option unset) is unchanged."
		},
		{
			name: 'components',
			type: 'Partial<MarkdownComponents>',
			description:
				'Custom React component overrides for rendered Markdown elements (code, inlineCode, link, heading, paragraph, image, blockquote, hr, citation).'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		},
		{
			name: 'class',
			type: 'ClassValue | null',
			description:
				'CSS class name for the root element. Prefer xstyle for styling; className is provided for integration with non-StyleX systems.'
		},
		{
			name: 'style',
			type: 'string | null',
			description:
				'Inline styles for the root element. Prefer xstyle for styling; inline styles bypass StyleX optimization.'
		},
		{
			name: 'data-testid',
			type: 'string',
			description: 'Test selector for automated testing frameworks.'
		}
	]
};
