// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ButtonGroup',
	displayName: 'Button Group',
	keywords: ['button-group', 'connected', 'split', 'toolbar', 'actions', 'grouped', 'buttons'],
	group: 'Button',
	category: 'Action',
	theming: {
		targets: [
			{
				className: 'astryx-button-group',
				visualProps: ['size', 'orientation', 'elevation']
			}
		]
	},
	usage: {
		description:
			'ButtonGroup joins related actions into a single connected control. Use it when multiple buttons represent related choices or operations that belong together visually, like copy/cut/paste, or undo/redo.',
		accessibility: [
			{
				name: 'Text label',
				category: 'Color contrast',
				criterion: '1.4.3 Contrast (Minimum)',
				requirement: '4.5:1',
				states: ['Rest', 'Hover', 'Pointer down'],
				description:
					'Text in each button must have at least 4.5:1 contrast with its background in every state. For Hover and Pointer down, measure the final background after the overlay is applied.'
			},
			{
				name: 'Essential icon or spinner arc',
				category: 'Color contrast',
				criterion: '1.4.11 Non-text Contrast',
				requirement: '3:1',
				states: ['Icon only', 'Loading'],
				description:
					'An icon used instead of text must have at least 3:1 contrast with the button background. The moving spinner arc must also meet 3:1. An icon beside a visible label does not need its own check.'
			},
			{
				name: 'Visible control boundary',
				category: 'Color contrast',
				criterion: '1.4.11 Non-text Contrast',
				requirement: '3:1 if needed',
				states: ['Rest'],
				description:
					'Some groups need a divider or edge to show each button. That divider or edge must have at least 3:1 contrast.'
			},
			{
				name: 'Keyboard focus indicator',
				category: 'Color contrast',
				criterion: '1.4.11 Non-text Contrast',
				requirement: '3:1',
				states: ['Focus visible'],
				description: 'The focus outline must have at least 3:1 contrast with the area around it.'
			},
			{
				name: 'Disabled appearance',
				category: 'Color contrast',
				criterion: '1.4.3 and 1.4.11 exceptions',
				requirement: 'Not required',
				states: ['Disabled'],
				description: 'Disabled controls do not need to meet these contrast ratios.'
			}
		],
		bestPractices: [
			{
				guidance: true,
				description:
					'Group buttons that perform related actions on the same object, like copy, cut, paste on selected text.'
			},
			{
				guidance: true,
				description:
					'Use the same variant for all buttons in a group so they look like a single connected unit.'
			},
			{
				guidance: true,
				description:
					'Keep groups small (2–4 buttons). For more actions, use a Toolbar or DropdownMenu instead.'
			},
			{
				guidance: false,
				description:
					"Don't mix wildly different actions. A Save button next to a Delete button in the same group is confusing."
			},
			{
				guidance: false,
				description:
					"Don't use ButtonGroup for navigation. Use SegmentedControl or TabList for switching between views."
			},
			{
				guidance: false,
				description:
					"Don't nest ButtonGroups. If you need multiple groups, place them side by side with a gap."
			},
			{
				guidance: true,
				description:
					"Name the group for what its buttons act on. The label is the group's accessible name and a screen reader reads it before each member."
			},
			{
				guidance: true,
				description:
					'Keep the group a single Tab stop. Arrow keys move between members along the orientation, Home/End jump to the ends, and disabled members are skipped. This is the WAI-ARIA APG roving tabindex technique: https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_roving_tabindex'
			},
			{
				guidance: false,
				description:
					"Don't disable the group to show that an action is in flight. A disabled member drops focus, so a keyboard user loses their place; leave the group enabled and show progress on the button that started the work."
			}
		],
		anatomy: [
			{
				name: 'Button',
				required: true,
				description: 'One or more Button or IconButton children that form the connected group.'
			},
			{
				name: 'Divider',
				required: false,
				description: 'A thin border between buttons, rendered automatically by the group.'
			}
		]
	},
	playground: {
		defaults: {
			label: 'Actions'
		}
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Button or IconButton children.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the group (aria-label).',
			required: true
		},
		{
			name: 'orientation',
			type: "'horizontal' | 'vertical'",
			description: 'Layout direction of the button group.',
			default: "'horizontal'"
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description: 'Default size for buttons in the group. Individual buttons can override.',
			default: "'md'"
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether all buttons in the group are disabled.',
			default: 'false'
		},
		{
			name: 'elevation',
			type: "'none' | 'low' | 'med' | 'high'",
			description:
				'Resting shadow depth for the whole group. The connected buttons share one surface, so the shadow lifts them as a unit. Use for a group that floats above content.',
			default: "'none'"
		},
		{
			name: 'ref',
			type: 'HTMLDivElement | null',
			description: 'Ref forwarded to the root element.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for layout customization. Must be a stylex.create() value.'
		},
		{
			name: 'data-testid',
			type: 'string',
			description: 'Test selector for automated testing frameworks.'
		}
	]
};
