// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'InternationalizationProvider',
	displayName: 'Internationalization Provider',
	keywords: [
		'i18n',
		'internationalization',
		'localization',
		'locale',
		'translation',
		'translations',
		'provider',
		'language'
	],
	group: 'Utilities',
	category: 'Utility',
	isHiddenFromOverview: true,
	usage: {
		description:
			'Wraps your app to set the active locale and (optionally) merge additional translation catalogs + per-locale overrides. Astryx components inside the subtree resolve their strings against this context. If no provider is present, components fall back to the shipped English defaults.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use shipped Astryx locale catalogs from `@astryx-svelte/core` when one exists for your target locale.'
			},
			{
				guidance: true,
				description:
					'Use a same-shape local catalog only when Astryx has not shipped that locale yet or you are testing in-progress translations.'
			},
			{
				guidance: true,
				description:
					'Use real BCP 47 tags such as `fr`, `pt-BR`, or `ar`; regional locales fall back to their base language before English.'
			},
			{
				guidance: true,
				description:
					"Set the `dir` attribute on `<html>` (or a wrapping element) yourself — the provider does not set it. Astryx components mirror layout and directional icons from the DOM `dir`, so an RTL locale won't visually mirror without it. Use `getLocaleDirection(locale)` to derive the value for both the provider and the DOM."
			},
			{
				guidance: false,
				description:
					'Cast custom catalog maps to `any`; the i18n package exports `MessagesByLocale` and `Catalog` for local catalog typing.'
			}
		]
	},
	props: [
		{
			name: 'locale',
			type: 'Locale',
			description:
				'BCP 47 language tag for the active locale (e.g. "en", "pt", "pt-BR", "zh-Hans"). Regional tags fall back to their base language, then to the shipped "en" catalog.',
			required: true
		},
		{
			name: 'messages',
			type: 'MessagesByLocale',
			description:
				'Optional map of BCP 47 tag to translation catalog. Import shipped catalogs from `@astryx-svelte/core`; the shipped "en" catalog is always available and does not need to be listed here.'
		},
		{
			name: 'overrides',
			type: 'Overrides',
			description:
				'Sparse per-locale key overrides applied on top of shipped defaults. Overrides are locale-keyed so a runtime locale swap picks up the correct set.'
		},
		{
			name: 'dir',
			type: "'ltr' | 'rtl'",
			description:
				'Explicit text-direction override for the context. When omitted, direction is derived from `locale` via `Intl.Locale.getTextInfo()`. This sets the direction Astryx reads, but it does NOT set the DOM `dir` attribute — you must set `dir` on `<html>` (or a wrapping element) yourself, since Astryx components mirror layout and directional icons from the DOM `dir`, not from this prop. Set both to the same value and keep them in sync.'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Content to render with the internationalization provider.',
			required: true
		}
	]
};
