// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useCollator',
	displayName: 'useCollator',
	keywords: [
		'i18n',
		'internationalization',
		'locale',
		'collation',
		'compare',
		'sort',
		'table',
		'hook'
	],
	params: [
		{
			name: 'options',
			type: '() => Intl.CollatorOptions',
			description:
				'Optional collation behavior such as numeric ordering, sensitivity, punctuation handling, and case order.'
		}
	],
	returns: [
		{
			name: 'collator',
			type: 'Intl.Collator',
			description: 'A memoized collator bound to the active InternationalizationProvider locale.'
		}
	],
	usage: {
		description:
			'Returns the sanctioned locale-aware comparator for custom sorting. The collator is recreated when the provider locale or an option changes.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Reuse collator.compare in custom Table comparators and other user-visible string ordering.'
			},
			{
				guidance: false,
				description:
					'Construct Intl.Collator directly or call localeCompare; those bypass the provider-backed locale contract.'
			}
		]
	},
	relatedComponents: ['InternationalizationProvider', 'Table'],
	relatedHooks: ['useLocale'],
	importPath: '@astryx-svelte/core',
	category: 'utilities'
};
