// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useTranslator',
	displayName: 'useTranslator',
	keywords: [
		'i18n',
		'internationalization',
		'localization',
		'translation',
		'translate',
		'locale',
		'hook'
	],
	params: [],
	returns: [
		{
			name: 'value',
			type: '(key: string, values?: Record<string, string | number | Date>) => string',
			description:
				"A stable translator function bound to the current InternationalizationProvider context. Call it with a message key and optional ICU MessageFormat values to get the formatted string in the active locale. Safe to use in render, event handlers, effects, or any code that runs during the parent component's lifecycle."
		}
	],
	usage: {
		description:
			"Returns a translator function that resolves keys against the current locale, provider overrides, and the shipped English fallback catalog. Call inside a component; the returned function can be used anywhere within that component's scope."
	},
	relatedComponents: ['InternationalizationProvider'],
	importPath: '@astryx-svelte/core',
	category: 'utilities'
};
