// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ChatMessage',
	displayName: 'Chat Message',
	subComponentOf: 'Chat',
	description:
		'Sender context wrapper: handles avatar, name, metadata, and alignment based on sender role.',
	keywords: [
		'chat',
		'message',
		'bubble',
		'conversation',
		'ai',
		'assistant',
		'thread',
		'system-message',
		'composer',
		'mention',
		'trigger',
		'typeahead',
		'token',
		'imperative',
		'tokenized-text'
	],
	group: 'Chat',
	category: 'Chat',
	props: [
		{
			name: 'sender',
			type: "'user' | 'assistant' | 'system'",
			description: 'Who sent this message: controls alignment and layout.',
			required: true
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Free-form content: bubbles, asset lists, tool calls, images.',
			required: true
		},
		{
			name: 'avatar',
			type: 'Snippet',
			description: 'Avatar element rendered beside the message. Typically Avatar.'
		},
		{
			name: 'name',
			type: 'string | Snippet',
			description:
				"Sender name rendered above the message body. Use when the first child is raw content (not a bubble). If the first child is a bubble, put the name on the bubble's `name` prop instead."
		},
		{
			name: 'metadata',
			type: 'string | Snippet',
			description:
				"Metadata rendered below the message body. Use when the last child is raw content (not a bubble). If the last child is a bubble, put metadata on the bubble's `metadata` prop instead."
		},
		{
			name: 'density',
			type: "'compact' | 'balanced' | 'spacious'",
			description: 'Visual density. Inherited from list context if not set.'
		}
	]
};
