// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ChatMessageMetadata',
	displayName: 'Chat Message Metadata',
	subComponentOf: 'Chat',
	description:
		'Composable metadata row for chat messages. Renders timestamp, footer content, and delivery status in a single row. Direction reverses for user sender. Renders nothing if all props are empty.',
	keywords: [
		'chat',
		'message',
		'bubble',
		'conversation',
		'ai',
		'assistant',
		'thread',
		'system-message',
		'composer',
		'mention',
		'trigger',
		'typeahead',
		'token',
		'imperative',
		'tokenized-text'
	],
	group: 'Chat',
	category: 'Chat',
	props: [
		{
			name: 'timestamp',
			type: 'string | Snippet',
			description: 'Timestamp content: a string or Timestamp component.'
		},
		{
			name: 'footer',
			type: 'string | Snippet',
			description: 'Footer content: model info, reaction buttons, copy button.'
		},
		{
			name: 'status',
			type: "'error' | 'sending' | 'sent' | 'delivered' | 'read'",
			description: 'Message delivery status. Shows icon + label.'
		}
	]
};
