// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ChatComposerDrawer',
	displayName: 'Chat Composer Drawer',
	subComponentOf: 'Chat',
	description:
		"Collapsible drawer panel that sits above the chat input inside ChatComposer. Pass it to the composer's `drawer` slot to show attachments, context chips, or any supplementary content. When `count` is provided the drawer gains a collapse toggle: collapsed state shows a badge and label, expanded state shows all children.",
	keywords: [
		'chat',
		'message',
		'bubble',
		'conversation',
		'ai',
		'assistant',
		'thread',
		'system-message',
		'composer',
		'mention',
		'trigger',
		'typeahead',
		'token',
		'imperative',
		'tokenized-text'
	],
	group: 'Chat',
	category: 'Chat',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			count: 3,
			label: 'Attachments'
		},
		wrapper: {
			component: 'Stack',
			props: {
				width: 480
			}
		}
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description:
				'Content to render inside the drawer: tokens, chips, previews, or any React elements.',
			required: true
		},
		{
			name: 'count',
			type: 'number',
			description:
				'Total item count shown in the collapsed badge. When provided, the drawer gains a collapse/expand toggle.'
		},
		{
			name: 'label',
			type: 'string',
			description: 'Label shown next to the count in collapsed state.',
			default: "'Items'"
		},
		{
			name: 'isCollapsed',
			type: 'boolean',
			description: 'Controlled collapsed state. Use with `onCollapsedChange` for external control.'
		},
		{
			name: 'defaultIsCollapsed',
			type: 'boolean',
			description: 'Initial collapsed state for uncontrolled usage.',
			default: 'false'
		},
		{
			name: 'onCollapsedChange',
			type: '(isCollapsed: boolean) => void',
			description: 'Callback fired when the user toggles the drawer.'
		}
	]
};
