// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ChatComposerTokenElement',
	displayName: 'Chat Composer Token Element',
	subComponentOf: 'Chat',
	description:
		'Renders a single token chip outside the contentEditable input. Wraps a badge config or custom render function in the correct data-astryx-token span so the token serializes properly and stays visually consistent with tokens inside the composer.',
	keywords: [
		'chat',
		'message',
		'bubble',
		'conversation',
		'ai',
		'assistant',
		'thread',
		'system-message',
		'composer',
		'mention',
		'trigger',
		'typeahead',
		'token',
		'imperative',
		'tokenized-text'
	],
	group: 'Chat',
	category: 'Chat',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'token',
			type: 'ChatComposerToken',
			description:
				'The token to render. Pass a badge config ({ value, label, variant?, icon? }) for the common case, or a custom render ({ value, render }) for full control.',
			required: true
		}
	]
};
