// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ChatMessageList',
	displayName: 'Chat Message List',
	subComponentOf: 'Chat',
	description:
		'Presentational message container with density context and infinite scroll support. Provides role="log" with aria-live="polite" for accessibility. A flex spacer pushes messages to the bottom when the list isn\'t full; set align="top" to start messages at the top instead.',
	keywords: [
		'chat',
		'message',
		'bubble',
		'conversation',
		'ai',
		'assistant',
		'thread',
		'system-message',
		'composer',
		'mention',
		'trigger',
		'typeahead',
		'token',
		'imperative',
		'tokenized-text'
	],
	group: 'Chat',
	category: 'Chat',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Message elements: typically ChatMessage or ChatSystemMessage.',
			required: true
		},
		{
			name: 'emptyState',
			type: 'Snippet',
			description: 'Content shown when the list has no messages.'
		},
		{
			name: 'scrollToTopAction',
			type: '() => Promise<void>',
			description:
				'Async action fired when user scrolls to top. Use for loading older messages. Wrapped in useTransition: shows a spinner at the top while pending.'
		},
		{
			name: 'density',
			type: "'compact' | 'balanced' | 'spacious'",
			description: 'Visual density: flows to child messages via context.',
			default: "'balanced'"
		},
		{
			name: 'gap',
			type: '0 | 6 | 2 | 4 | 0.5 | 1 | 1.5 | 3 | 5 | 8 | 10',
			description:
				'Gap between top-level message rows. Defaults to the selected density; override for LLM event streams or independent rows that need different spacing from density.'
		},
		{
			name: 'align',
			type: "'top' | 'bottom'",
			description:
				"Vertical alignment when the list is shorter than its container. 'bottom' fills free space with a spacer so short conversations sit above the composer; 'top' omits the spacer so messages start at the top. Only affects a non-full list; overflowing lists scroll identically, preserving auto-scroll-to-bottom.",
			default: "'bottom'"
		},
		{
			name: 'isStreaming',
			type: 'boolean',
			description:
				'Whether an assistant message is actively streaming. Marks the log aria-busy so screen readers wait and announce the completed message once instead of re-announcing partial text on every token.',
			default: 'false'
		}
	]
};
