// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'CheckboxListItem',
	displayName: 'Checkbox List Item',
	subComponentOf: 'CheckboxList',
	description:
		'Individual checkbox item with label, description, and end content slot. Works in collection mode (inside CheckboxList) or standalone mode (inside List).',
	keywords: [
		'checkboxlist',
		'checkbox',
		'checkboxgroup',
		'multichoice',
		'multiselect',
		'checklist'
	],
	group: 'Checkbox',
	category: 'Form Controls',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'label',
			type: 'string | Snippet',
			description:
				'Primary text label for the item. Rich labels may contain links or buttons, which keep their own behavior without toggling the item. A ReactNode label names the checkbox from its visible text; pass aria-label only when that text is absent, or include all visible label words in the override.',
			required: true
		},
		{
			name: 'aria-label',
			type: 'string',
			description:
				'Plain-text accessible name for the checkbox, replacing the one derived from label. Applied to the checkbox control. Use it when a rich label has no visible text; otherwise the value must retain every visible label word.'
		},
		{
			name: 'value',
			type: 'string',
			description: 'Identity key (required inside CheckboxList).'
		},
		{
			name: 'description',
			type: 'string',
			description:
				"Secondary content below the label. String or ReactNode. Exposed as the checkbox's accessible description through aria-describedby, so assistive technology can tell it is the explanation for that choice."
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Content rendered after the label area.'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether this individual item is disabled.',
			default: 'false'
		},
		{
			name: 'isLoading',
			type: 'boolean',
			description:
				'Whether this item is loading. Shows a spinner inside the checkbox and blocks interaction on this item. In collection mode, the toggled item also shows this automatically while the parent changeAction is pending.',
			default: 'false'
		},
		{
			name: 'isChecked',
			type: "boolean | 'indeterminate'",
			description: 'Direct checked state (standalone mode only).'
		},
		{
			name: 'onCheck',
			type: '(checked: boolean) => void',
			description: 'Direct check handler (standalone mode only).'
		}
	]
};
