// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Dialog',
	displayName: 'Dialog',
	keywords: [
		'dialog',
		'modal',
		'popup',
		'overlay',
		'lightbox',
		'alert',
		'confirm',
		'prompt',
		'backdrop',
		'focus trap',
		'imperative'
	],
	group: 'Dialog',
	category: 'Overlay',
	theming: {
		container: true,
		targets: [
			{
				className: 'astryx-dialog',
				visualProps: ['variant']
			}
		],
		vars: [
			{
				name: '--_dialog-radius',
				description: 'Border radius of the dialog',
				default: 'var(--radius-container)',
				private: true
			}
		],
		derived: [
			{
				property: 'borderRadius',
				vars: ['--_dialog-radius']
			},
			{
				property: 'padding',
				expand: 'container'
			}
		]
	},
	usage: {
		description:
			'Dialog displays a modal overlay that blocks interaction with the page until the user responds. Use it for delete confirmations, edit forms, terms acceptance, or any decision that should not be skipped.\n\nFor cases where you want to show a dialog without managing open state, use the `useImperativeDialog` hook: call `dialog.show(content)` and render `dialog.element` in your tree.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Choose the right purpose: info for dismissable content, form to prevent accidental backdrop dismissal, required when the user must respond.'
			},
			{
				guidance: true,
				description:
					'Include a clear title in the header so users immediately understand what the dialog is asking.'
			},
			{
				guidance: true,
				description:
					'Use purpose="form" for dialogs with inputs so the user can\'t accidentally lose data by clicking the backdrop.'
			},
			{
				guidance: true,
				description:
					'Keep dialogs focused on a single task; if the content grows beyond what fits, consider a full page instead.'
			},
			{
				guidance: false,
				description:
					'Use a dialog for simple messages that could be shown inline or as a toast notification.'
			},
			{
				guidance: false,
				description:
					'Nest dialogs inside other dialogs; restructure the flow into steps within a single dialog instead.'
			},
			{
				guidance: false,
				description:
					'Use the fullscreen variant for simple confirmations; it is meant for complex content like editors or long forms.'
			}
		],
		anatomy: [
			{
				name: 'Header',
				required: true,
				description:
					'Title, optional subtitle, and close button. The title receives focus on open and labels the dialog via aria-labelledby.'
			},
			{
				name: 'Body',
				required: true,
				description: 'The main content area: text, forms, lists, or any layout.'
			},
			{
				name: 'Footer',
				required: false,
				description: 'Action buttons like Save/Cancel or Accept/Decline, aligned to the end.'
			},
			{
				name: 'Backdrop',
				required: true,
				description: 'Semi-transparent overlay behind the dialog that blocks page interaction.'
			}
		]
	},
	playground: {
		defaults: {
			isOpen: true,
			isInline: true,
			width: 400
		}
	},
	props: [
		{
			name: 'isOpen',
			type: 'boolean',
			description: 'Whether the dialog is open.',
			required: true
		},
		{
			name: 'onOpenChange',
			type: '(isOpen: boolean) => unknown',
			description: 'Callback when dialog visibility changes.',
			required: true
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Dialog content.',
			required: true
		},
		{
			name: 'width',
			type: 'number | string',
			description:
				'Preferred width of the dialog in pixels or any CSS value. Standard dialogs clamp to their container and the dynamic viewport with spacing-token gutters so narrow viewports keep content on screen.',
			default: '400'
		},
		{
			name: 'maxHeight',
			type: 'number | string',
			description:
				'Maximum height of the dialog. Defaults to a dynamic viewport value so browser UI changes are reflected where supported.',
			default: "'75dvh'"
		},
		{
			name: 'position',
			type: 'Readonly<DialogPosition>',
			description:
				'Static position for the dialog; centered by default when omitted. Use logical `start`/`end` for inline offsets so positioned dialogs mirror correctly under RTL.'
		},
		{
			name: 'variant',
			type: "'standard' | 'fullscreen'",
			description: 'Dialog variant: fullscreen expands to fill the entire viewport.',
			default: "'standard'"
		},
		{
			name: 'purpose',
			type: "'info' | 'form' | 'required'",
			description:
				'Controls dismissal behavior: required disables Escape and backdrop click; form disables backdrop click after interaction; info allows both.',
			default: "'info'"
		},
		{
			name: 'padding',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description: 'Internal padding of the dialog using the spacing scale step.'
		},
		{
			name: 'isInline',
			type: 'boolean',
			description:
				'Renders dialog content inline without the <dialog> element, backdrop, or modal behavior. For documentation previews and showcases only.',
			default: 'false'
		}
	]
};
