// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'DialogHeader',
	displayName: 'Dialog Header',
	subComponentOf: 'Dialog',
	description:
		'Header for dialogs with a title, optional subtitle, close button, and start/end content slots.',
	keywords: [
		'dialog',
		'modal',
		'popup',
		'overlay',
		'lightbox',
		'alert',
		'confirm',
		'prompt',
		'backdrop',
		'focus trap',
		'imperative'
	],
	group: 'Dialog',
	category: 'Overlay',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			title: 'Delete file?',
			subtitle: 'This action cannot be undone.',
			hasDivider: true
		}
	},
	props: [
		{
			name: 'title',
			type: 'string',
			description:
				'Dialog title (receives focus on open and labels the dialog via aria-labelledby).'
		},
		{
			name: 'subtitle',
			type: 'string',
			description: 'Subtitle below the title.'
		},
		{
			name: 'onOpenChange',
			type: '(isOpen: boolean) => unknown',
			description: 'Close button callback (no button if omitted).'
		},
		{
			name: 'startContent',
			type: 'Snippet',
			description: 'Content before the title (e.g., a back button).'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Content after the title, before close button.'
		},
		{
			name: 'hasDivider',
			type: 'boolean',
			description: 'Adds border at the bottom edge.',
			default: 'true'
		}
	]
};
