// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'List',
	displayName: 'List',
	keywords: ['list', 'listitem', 'listbox', 'menu', 'collection', 'items', 'ul', 'navlist'],
	group: 'List',
	category: 'Table & List',
	theming: {
		targets: [
			{
				className: 'astryx-list',
				visualProps: ['density', 'listStyle']
			},
			{
				className: 'astryx-list-item'
			}
		]
	},
	usage: {
		description:
			'A vertical collection of items with consistent spacing, dividers, and optional markers. Supports headers, icons, avatars, badges, and interactive items with click or link behavior. Use it to display ordered or unordered groups of related content.',
		bestPractices: [
			{
				guidance: true,
				description: 'Provide a header to label the list and give context to screen readers.'
			},
			{
				guidance: true,
				description:
					'Use start and end content slots to add icons, avatars, or badges to each item.'
			},
			{
				guidance: false,
				description:
					'Place interactive elements inside an interactive list item; it creates nested click targets and confusing focus behavior.'
			},
			{
				guidance: false,
				description:
					'Use a list for a single item or for laying out unrelated content; lists imply a meaningful collection.'
			},
			{
				guidance: false,
				description:
					'Mix clickable and non-clickable items in the same list without clear visual distinction.'
			}
		],
		anatomy: [
			{
				name: 'List title',
				required: true,
				description: 'Heading that labels the list.'
			},
			{
				name: 'Description',
				required: false,
				description: 'Supplementary text below the title.'
			},
			{
				name: 'List items',
				required: true,
				description: 'Individual entries, which may include icons or images.'
			},
			{
				name: 'Item description',
				required: false,
				description: 'Additional detail for an individual list item.'
			}
		]
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'List items (ListItem components).'
		},
		{
			name: 'density',
			type: "'compact' | 'balanced' | 'spacious'",
			description: 'Spacing density for items.',
			default: "'balanced'"
		},
		{
			name: 'hasDividers',
			type: 'boolean',
			description: 'Show dividers between items.',
			default: 'false'
		},
		{
			name: 'header',
			type: 'string | Snippet',
			description: 'Header content, associated with the list via aria-labelledby.'
		},
		{
			name: 'listStyle',
			type: "'circle' | 'none' | 'decimal' | 'disc'",
			description: "List marker style. 'decimal' renders an <ol> element instead of <ul>.",
			default: "'none'"
		},
		{
			name: 'start',
			type: 'number',
			description:
				"Starting number for ordered lists (listStyle='decimal'). Sets the CSS counter to begin at this value.",
			default: '1'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
