// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ListItem',
	displayName: 'List Item',
	subComponentOf: 'List',
	description:
		'List item with label, description, start/end content slots, and interactive patterns.',
	keywords: ['list', 'listitem', 'listbox', 'menu', 'collection', 'items', 'ul', 'navlist'],
	group: 'List',
	category: 'Table & List',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Primary text.',
			required: true
		},
		{
			name: 'description',
			type: 'string | Snippet',
			description:
				'Secondary content below the label. A plain string gets single-line truncation automatically; a ReactNode lets child components control their own wrapping and line-clamp behavior.'
		},
		{
			name: 'startContent',
			type: 'Snippet',
			description: 'Content rendered before the label area (e.g. icon, avatar).'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Content rendered after the label area (e.g. badge, chevron).'
		},
		{
			name: 'onclick',
			type: '(event: MouseEvent) => void',
			description: 'Click handler; enables the invisible button pattern.'
		},
		{
			name: 'interactiveRef',
			type: '() => HTMLElement | null',
			description:
				"Ref to a nested control (e.g. a checkbox in startContent) that owns the item's keyboard access and action. The row becomes an enlarged click/tap target that delegates surface clicks to it (useClickableContainer) and renders no invisible button/anchor, so the row adds no second tab stop (WCAG 4.1.2). Mutually exclusive with onClick/href; those are ignored when set."
		},
		{
			name: 'href',
			type: 'string',
			description: 'Link URL; enables the invisible anchor pattern.'
		},
		{
			name: 'target',
			type: 'string',
			description:
				'Link target attribute, only applicable when href is provided. target="_blank" automatically adds noopener noreferrer.'
		},
		{
			name: 'rel',
			type: 'string',
			description:
				'Link relationship tokens. noopener noreferrer are merged automatically for target="_blank".'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Disabled state; sets aria-disabled on the item.',
			default: 'false'
		},
		{
			name: 'isSelected',
			type: 'boolean',
			description: 'Selected state; sets aria-selected on the item.',
			default: 'false'
		}
	]
};
