// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Blockquote',
	displayName: 'Blockquote',
	keywords: ['blockquote', 'quote', 'citation', 'pullquote', 'quotation', 'cite', 'excerpt'],
	category: 'Content',
	theming: {
		targets: [
			{
				className: 'astryx-blockquote',
				visualProps: []
			}
		]
	},
	usage: {
		description:
			'A quotation block with a rule on its inline-start edge and secondary text color. Use to highlight quoted content, testimonials, or excerpts. The rule and padding are logical, so they move to the right edge in right-to-left locales.',
		anatomy: [
			{
				name: 'Rule',
				required: true,
				description: 'The border on the inline-start edge, drawn with --color-border-emphasized.'
			},
			{
				name: 'Quotation',
				required: true,
				description:
					'The quoted content, passed as children. Renders inside the <blockquote> element.'
			},
			{
				name: 'Attribution',
				required: false,
				description: 'The source, passed as cite. Renders as a <cite> element below the quotation.'
			}
		],
		bestPractices: [
			{
				guidance: true,
				description:
					'Use for quoted text, testimonials, or highlighted excerpts from external sources.'
			},
			{
				guidance: true,
				description: 'Provide a cite prop when the source of the quote is known.'
			},
			{
				guidance: true,
				description:
					'Pass the source through cite rather than typing it into children, so it renders as a semantic <cite> element that assistive technology can distinguish from the quotation.'
			},
			{
				guidance: false,
				description: 'Use for callout boxes or informational notes; use Banner for those.'
			},
			{
				guidance: false,
				description:
					'Wrap the attribution in your own <footer>. A <footer> inside a <blockquote> becomes a contentinfo document landmark, and a page with several quotes then reports several page footers.'
			}
		]
	},
	playground: {
		defaults: {
			children: 'Design is not just what it looks like and feels like. Design is how it works.',
			cite: 'Steve Jobs'
		}
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Content of the blockquote.',
			required: true
		},
		{
			name: 'cite',
			type: 'Snippet',
			description:
				'Optional attribution for the quote. Rendered in a <cite> element after the quoted content.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
