// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'useTableSortable',
	displayName: 'useTableSortable',
	subComponentOf: 'Table',
	description:
		'Headless multi-sort plugin for Table. Call with a config object: `useTableSortable({ sort, onSortChange })`. Returns a TablePlugin to pass to `<Table plugins={{ sort: sortPlugin }} />`.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	usage: {
		description:
			'Call useTableSortable with a config object containing sort state and callback. Pass the returned plugin to Table via the plugins prop.'
	},
	props: [
		{
			name: 'sort',
			type: 'TableSortState<TSortKey>',
			description:
				"Current sort state (TableSortState<TSortKey>). Ordered array of entries; the first is the primary sort, the rest are tiebreakers. An empty array means unsorted. Direction is the full word: 'ascending' / 'descending', not 'asc' / 'desc'.",
			required: true
		},
		{
			name: 'onSortChange',
			type: '(sort: TableSortState<TSortKey>) => void',
			description:
				'Called when the user clicks a header cell to change sort. Receives the next sort state.',
			required: true
		},
		{
			name: 'allowUnsortedState',
			type: 'boolean',
			description:
				"Allow cycling back to unsorted. When true: 'ascending', 'descending', unsorted. When false: 'ascending', 'descending', 'ascending'.",
			default: 'true'
		},
		{
			name: 'isMultiSortEnabled',
			type: 'boolean',
			description:
				'Enable multi-sort via Shift+click. Regular click still replaces the entire sort state.',
			default: 'false'
		}
	]
};
