// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Badge',
	displayName: 'Badge',
	keywords: [
		'badge',
		'tag',
		'chip',
		'label',
		'status',
		'indicator',
		'count',
		'counter',
		'pill',
		'notification',
		'marker'
	],
	category: 'Feedback & Status',
	theming: {
		targets: [
			{
				className: 'astryx-badge',
				visualProps: ['variant']
			}
		]
	},
	usage: {
		description:
			'Badge highlights a status or category at a glance. Use it sparingly: only when a value represents a distinct state (Active, Failed) or a grouping tag (Engineering, Design). Most metadata (dates, durations, counts, descriptions) should be plain description text, not badges.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Every status badge steals attention. Only badge states where the user needs to notice or act: errors, warnings, items requiring follow-up. If no action is needed, plain text is fine.'
			},
			{
				guidance: true,
				description:
					'Use success, warning, and error variants only for system status that demands attention: "Failed", "Degraded", "Action Required". These have bold solid backgrounds designed to stand out.'
			},
			{
				guidance: true,
				description:
					'Use color variants (blue, purple, teal, etc.) for category tags that group or classify items: team names, content types, priority levels.'
			},
			{
				guidance: true,
				description:
					'Keep labels to one or two words. If you need more detail, put it in surrounding text instead of the badge.'
			},
			{
				guidance: true,
				description:
					'Add an icon when it helps identify the badge type quickly, but always include a text label alongside it.'
			},
			{
				guidance: false,
				description:
					'Apply a "success" badge to every healthy/active/normal item. If all rows show green "Active" badges, none stand out; the badge adds noise, not information. Show only the states that need user attention (errors, warnings, pending actions).'
			},
			{
				guidance: false,
				description:
					'Use badges for metadata. Durations ("6h window"), counts ("12 trigger types"), dates, and descriptions are not statuses or categories; use description text (Text with type="supporting") instead.'
			},
			{
				guidance: false,
				description:
					'Use semantic status variants (success, warning, error, info) for categories or informational content. These are visually loud and should only indicate system state.'
			},
			{
				guidance: false,
				description:
					"Repeat the same badge in every row of a table or list. If the same value appears in most rows, it's not adding information; use plain text for common states and reserve badges for the exceptional ones."
			},
			{
				guidance: false,
				description:
					'Make badges clickable; they are read-only indicators. Use a button or link if the user needs to take action.'
			}
		],
		anatomy: [
			{
				name: 'Icon',
				required: false,
				description: 'An optional leading icon that helps identify the badge type at a glance.'
			},
			{
				name: 'Label',
				required: true,
				description: 'The text or number shown inside the badge.'
			}
		]
	},
	playground: {
		defaults: {
			label: 'Badge',
			variant: 'neutral'
		}
	},
	props: [
		{
			name: 'variant',
			type: "'success' | 'neutral' | 'error' | 'warning' | 'info' | 'blue' | 'cyan' | 'green' | 'orange' | 'pink' | 'purple' | 'red' | 'teal' | 'yellow'",
			description:
				'Visual style variant. Semantic variants (neutral, info, success, warning, error) use solid backgrounds. Non-semantic color variants use tinted backgrounds with colored text for categorization and tagging.',
			default: "'neutral'"
		},
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Badge text content.'
		},
		{
			name: 'icon',
			type: 'Snippet',
			description: 'Optional leading icon.'
		}
	]
};
