// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'useTableColumnSettings',
	displayName: 'useTableColumnSettings',
	subComponentOf: 'Table',
	description:
		'Headless column visibility and ordering management for Table. Provides filtered columns, toggle helpers, and pre-built MultiSelector options for a column picker UI.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	props: [
		{
			name: 'columns',
			type: 'ReadonlyArray<ColumnSettingsOption<TColumnKey>>',
			description:
				'All available columns with metadata for the settings UI. Each entry has key, label, optional isAlwaysVisible and group.',
			required: true
		},
		{
			name: 'activeColumnKeys',
			type: 'ReadonlyArray<TColumnKey>',
			description:
				'Currently active column keys, in display order. Only columns with keys in this array are shown.',
			required: true
		},
		{
			name: 'onChangeActiveColumnKeys',
			type: '(keys: ReadonlyArray<TColumnKey>) => void',
			description: 'Called when active columns change (toggle, reorder).',
			required: true
		},
		{
			name: 'defaultColumnKeys',
			type: 'ReadonlyArray<TColumnKey>',
			description:
				'Default column set for "Reset to default". When omitted, reset shows all columns.'
		}
	]
};
