// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Divider',
	displayName: 'Divider',
	keywords: ['divider', 'separator', 'hr', 'rule', 'line', 'border', 'spacer', 'horizontal rule'],
	category: 'Layout',
	theming: {
		targets: [
			{
				className: 'astryx-divider',
				visualProps: ['orientation', 'variant']
			}
		]
	},
	usage: {
		description:
			'A visual separator that divides content into distinct sections. Use to create clear boundaries between groups of related content, or to demarcate interactive regions within a layout.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use subtle dividers between related content sections and strong dividers for high-contrast boundaries.'
			},
			{
				guidance: true,
				description: 'Add a label to the divider when sections need a visible category heading.'
			},
			{
				guidance: false,
				description:
					'Overuse dividers; rely on spacing and layout to separate content when possible.'
			}
		]
	},
	props: [
		{
			name: 'orientation',
			type: "'horizontal' | 'vertical'",
			description: 'Orientation of the divider.',
			default: "'horizontal'"
		},
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Optional label centered on the divider.'
		},
		{
			name: 'variant',
			type: "'subtle' | 'strong'",
			description: 'Visual weight of the divider line.',
			default: "'subtle'"
		},
		{
			name: 'isFullBleed',
			type: 'boolean',
			description: 'Extend the divider to container edges with negative margins.',
			default: 'false'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
