// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'SegmentedControl',
	displayName: 'Segmented Control',
	keywords: [
		'radio',
		'tabs',
		'toggle',
		'toggle-group',
		'pill',
		'button-group',
		'switch',
		'segment',
		'control'
	],
	group: 'SegmentedControl',
	category: 'Action',
	theming: {
		targets: [
			{
				className: 'astryx-segmented-control',
				visualProps: ['size']
			},
			{
				className: 'astryx-segmented-control-item',
				visualProps: ['size'],
				states: ['selected', 'disabled']
			}
		],
		vars: [
			{
				name: '--_segmented-control-radius',
				description: 'Border radius of the segmented control',
				default: 'var(--radius-element)',
				private: true
			},
			{
				name: '--_segmented-control-padding',
				description: 'Inner padding of the segmented control',
				default: 'var(--spacing-0-5)',
				private: true
			}
		],
		derived: [
			{
				property: 'borderRadius',
				vars: ['--_segmented-control-radius']
			},
			{
				property: 'padding',
				vars: ['--_segmented-control-padding']
			}
		]
	},
	usage: {
		description:
			'A segmented button group that allows users to make a single selection from a small set of mutually exclusive options. Use SegmentedControl when all options should be visible at once and the selection controls a value or mode, not page navigation.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use for switching between 2–5 mutually exclusive views or modes where all options should be visible.'
			},
			{
				guidance: true,
				description:
					'Provide a descriptive label for the control to ensure the group is accessible to screen readers.'
			},
			{
				guidance: false,
				description:
					'Use for page-level navigation; use TabList instead. TabList is a navigation component, while SegmentedControl is an input that always has exactly one selected option.'
			},
			{
				guidance: false,
				description:
					'Use for simple on/off states; use ToggleButton instead. ToggleButton can be toggled on or off independently, while SegmentedControl enforces a single selection from a group.'
			},
			{
				guidance: false,
				description:
					'Wrap a disabled SegmentedControl in Tooltip to explain why it is disabled; disabled controls swallow the hover events the wrapper needs. Use the disabledMessage prop instead.'
			}
		]
	},
	playground: {
		defaults: {
			value: 'option-1'
		}
	},
	props: [
		{
			name: 'value',
			type: 'string',
			description: 'The currently selected value (controlled).',
			required: true
		},
		{
			name: 'onChange',
			type: '(value: string) => void',
			description: 'Callback fired when a segment is selected.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description:
				'Accessible label for the radio group (used as aria-label, never rendered visually).',
			required: true
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description: 'Size variant for the control.',
			default: "'md'"
		},
		{
			name: 'layout',
			type: "'fill' | 'hug'",
			description:
				'Layout mode. hug (default) sizes segments to content; fill stretches them equally to fill the container.',
			default: "'hug'"
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether the entire control is disabled.',
			default: 'false'
		},
		{
			name: 'disabledMessage',
			type: 'string',
			description:
				'Explains why the control is disabled. Applies to the whole-group disabled state (isDisabled), not per segment. With isDisabled, shows a tooltip on hover/keyboard focus and keeps the control focusable via aria-disabled (selection stays blocked). Use this instead of wrapping a disabled SegmentedControl in Tooltip. Disabled controls swallow the hover events an external Tooltip needs.'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'SegmentedControlItem children.',
			required: true
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
