// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'SegmentedControlItem',
	displayName: 'Segmented Control Item',
	subComponentOf: 'SegmentedControl',
	description: 'Individual segment item rendering as a radio button within the segmented control.',
	keywords: [
		'radio',
		'tabs',
		'toggle',
		'toggle-group',
		'pill',
		'button-group',
		'switch',
		'segment',
		'control'
	],
	group: 'SegmentedControl',
	category: 'Action',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			value: 'item-1',
			label: 'Item'
		},
		wrapper: {
			component: 'SegmentedControl',
			props: {
				value: 'item-1',
				label: 'Segmented control'
			}
		}
	},
	props: [
		{
			name: 'value',
			type: 'string',
			description: 'Unique value for this segment, matched against the parent value.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description:
				'Accessible label for this segment. Rendered as visible text unless isLabelHidden is true.',
			required: true
		},
		{
			name: 'isLabelHidden',
			type: 'boolean',
			description:
				'Whether the label is visually hidden. When true, only the icon is displayed and label is used as aria-label.',
			default: 'false'
		},
		{
			name: 'icon',
			type: 'Snippet',
			description: 'Icon element displayed before the label.'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether this individual item is disabled.',
			default: 'false'
		}
	]
};
