// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'CommandPaletteGroup',
	displayName: 'Command Palette Group',
	subComponentOf: 'CommandPalette',
	description: 'Visual grouping with a heading label. Place inside CommandPaletteList.',
	keywords: [
		'command',
		'spotlight',
		'launcher',
		'omnibox',
		'quicksearch',
		'palette',
		'finder',
		'search',
		'modal',
		'dialog',
		'navigation'
	],
	group: 'CommandPalette',
	category: 'Overlay',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			heading: 'Navigation'
		}
	},
	props: [
		{
			name: 'heading',
			type: 'string',
			description: 'Group heading text.',
			required: true
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'CommandPaletteItem children.',
			required: true
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for layout customization. Must be a stylex.create() value.'
		}
	]
};
