// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'CommandPaletteInput',
	displayName: 'Command Palette Input',
	subComponentOf: 'CommandPalette',
	description:
		'Search input slot. Auto-focuses on mount. Wires to command palette context when used inside CommandPalette.',
	keywords: [
		'command',
		'spotlight',
		'launcher',
		'omnibox',
		'quicksearch',
		'palette',
		'finder',
		'search',
		'modal',
		'dialog',
		'navigation'
	],
	group: 'CommandPalette',
	category: 'Overlay',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			placeholder: 'Search commands, files, or actions...',
			hasAutoFocus: false
		}
	},
	props: [
		{
			name: 'placeholder',
			type: 'string',
			description: 'Placeholder text for the input.',
			default: "'Search...'"
		},
		{
			name: 'label',
			type: 'string',
			description:
				'Accessible label for the combobox input, announced by screen readers. Falls back to the placeholder text when omitted.'
		},
		{
			name: 'hasAutoFocus',
			type: 'boolean',
			description:
				'Auto-focus the input when mounted. Automatically disabled when inside an inline command palette.',
			default: 'true'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description:
				'Content rendered at the trailing end of the input, after the spinner. Use for clear buttons or keyboard shortcut hints.'
		},
		{
			name: 'value',
			type: 'string',
			description: 'Search value. When omitted inside CommandPalette, reads from context.'
		},
		{
			name: 'onValueChange',
			type: '(value: string) => void',
			description:
				'Called when search value changes. When omitted inside CommandPalette, writes to context.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for layout customization. Must be a stylex.create() value.'
		}
	]
};
