// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'CommandPaletteEmpty',
	displayName: 'Command Palette Empty',
	subComponentOf: 'CommandPalette',
	description:
		'Empty state display for the results area. Rendered automatically by CommandPalette for no-results and no-query states.',
	keywords: [
		'command',
		'spotlight',
		'launcher',
		'omnibox',
		'quicksearch',
		'palette',
		'finder',
		'search',
		'modal',
		'dialog',
		'navigation'
	],
	group: 'CommandPalette',
	category: 'Overlay',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			children: 'No results found. Try a different search.'
		}
	},
	props: [
		{
			name: 'children',
			type: 'string | Snippet',
			description: 'Message or content to display.',
			required: true
		}
	]
};
