// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'MoreMenu',
	displayName: 'More Menu',
	keywords: [
		'moremenu',
		'overflow',
		'kebab',
		'dotmenu',
		'threedot',
		'ellipsis',
		'dropdown',
		'contextmenu',
		'actionmenu'
	],
	category: 'Action',
	theming: {
		targets: [
			{
				className: 'astryx-more-menu'
			}
		]
	},
	usage: {
		anatomy: [
			{
				name: 'Trigger button',
				required: true,
				description: 'Icon-only Button that provides the visible overflow-menu entry point.'
			},
			{
				name: 'Icon-resolved trigger icon',
				required: false,
				description: 'Default semantic three-dot artwork resolved from the active Icon registry.'
			},
			{
				name: 'Caller-rendered trigger content',
				required: false,
				description: 'Arbitrary React content supplied directly as the trigger icon override.'
			},
			{
				name: 'Menu surface',
				required: true,
				description: 'DropdownMenu panel that also carries MoreMenu’s current public target.'
			},
			{
				name: 'Pointer action row',
				required: false,
				description:
					'Action or nested-action trigger row rendered by DropdownMenu in the anchored presentation.'
			},
			{
				name: 'Touch action row',
				required: false,
				description: 'ListItem button rendered by DropdownMenu in the BottomSheet presentation.'
			}
		],
		description:
			"MoreMenu is a three-dot button that opens a list of actions. Use it for secondary actions that don't need to be always visible, like in table rows, card headers, or toolbars.",
		bestPractices: [
			{
				guidance: true,
				description:
					'Use for overflow or secondary actions; keep primary actions visible outside the menu.'
			},
			{
				guidance: true,
				description:
					'Use dividers or sections to group related actions when the menu has many items.'
			},
			{
				guidance: true,
				description:
					'Use `presentation="adaptive"` when the visible overflow trigger should open a thumb-reachable BottomSheet on compact touch devices.'
			},
			{
				guidance: false,
				description: 'Hide primary actions inside a MoreMenu; they should be directly visible.'
			}
		]
	},
	playground: {
		defaults: {
			items: [
				{
					label: 'Edit',
					value: 'edit'
				},
				{
					label: 'Duplicate',
					value: 'duplicate'
				},
				{
					label: 'Delete',
					value: 'delete'
				}
			]
		}
	},
	props: [
		{
			name: 'items',
			type: 'DropdownMenuOption[]',
			description:
				'Menu items: data array of actions, dividers, and sections. Same type as DropdownMenu items prop.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the trigger button (aria-label) and tooltip text.',
			default: "'More options'"
		},
		{
			name: 'variant',
			type: "'primary' | 'secondary' | 'ghost' | 'destructive'",
			description: 'Visual style variant of the trigger button.',
			default: "'ghost'"
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description: 'Size of the trigger button.',
			default: "'md'"
		},
		{
			name: 'icon',
			type: 'Snippet',
			description: 'Override the default three-dot icon. Accepts any ReactNode.'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether the menu trigger is disabled.',
			default: 'false'
		},
		{
			name: 'placement',
			type: "'below' | 'above' | 'end' | 'start'",
			description:
				"Position of the menu relative to the trigger. Logical: start/end resolve against the menu's own inherited direction (RTL mirrors).",
			default: "'below'"
		},
		{
			name: 'alignment',
			type: "'end' | 'start' | 'center'",
			description:
				"Alignment along the placement axis. Use 'end' to align the menu with the trigger's trailing edge, which is usually what an overflow menu wants.",
			default: "'start'"
		},
		{
			name: 'presentation',
			type: "'popover' | 'bottom-sheet' | 'adaptive'",
			description:
				'Presentation policy forwarded to DropdownMenu. `adaptive` keeps the anchored popover on pointer-based layouts and uses a BottomSheet at 768px and below when the primary pointer is coarse.',
			default: "'popover'"
		},
		{
			name: 'onOpenChange',
			type: '(isOpen: boolean) => void',
			description: 'Callback fired when the menu opens or closes.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
