// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'FieldStatus',
	displayName: 'Field Status',
	group: 'Field',
	category: 'Form Controls',
	isHiddenFromOverview: true,
	theming: {
		targets: [
			{
				className: 'astryx-field-status',
				visualProps: ['type', 'variant']
			},
			{
				className: 'astryx-field-status-icon',
				visualProps: ['type']
			}
		]
	},
	usage: {
		description:
			'FieldStatus renders validation feedback for fields and field-like controls. Use it directly for custom controls that need the same error, warning, or success presentation as Field.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use attached status below bordered inputs when the message belongs to that input.'
			},
			{
				guidance: true,
				description:
					'Use detached status for controls like checkboxes, switches, and custom controls where overlap would be visually awkward.'
			},
			{
				guidance: false,
				description:
					'Use FieldStatus for general alerts or page-level notices; use Banner or Toast instead.'
			}
		],
		anatomy: [
			{
				name: 'Message box',
				required: true,
				description: 'Painted container for the validation feedback.'
			},
			{
				name: 'Detached icon',
				required: false,
				description: 'Leading status glyph shown only by the detached variant.'
			},
			{
				name: 'Message text',
				required: true,
				description: 'Text describing the validation status.'
			}
		]
	},
	props: [
		{
			name: 'type',
			type: "'success' | 'error' | 'warning'",
			description: 'Status type.',
			required: true
		},
		{
			name: 'message',
			type: 'string',
			description: 'Status message text.',
			required: true
		},
		{
			name: 'id',
			type: 'string | null',
			description: 'ID for aria-describedby association.'
		},
		{
			name: 'variant',
			type: "'tooltip' | 'attached' | 'detached'",
			description: 'Visual variant: attached overlaps the input, detached floats below.',
			default: "'attached'"
		}
	]
};
