// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Calendar',
	displayName: 'Calendar',
	keywords: [
		'calendar',
		'datepicker',
		'date picker',
		'rangepicker',
		'date range',
		'monthview',
		'daypicker'
	],
	category: 'Form Controls',
	theming: {
		targets: [
			{
				className: 'astryx-calendar',
				visualProps: ['mode']
			},
			{
				className: 'astryx-calendar-nav',
				visualProps: ['nav'],
				states: ['disabled']
			},
			{
				className: 'astryx-calendar-day',
				states: ['selected', 'today', 'disabled', 'in-range', 'marker']
			}
		]
	},
	usage: {
		description:
			'Calendar lets the user pick a date or date range from a month grid. Use it in booking flows, scheduling UIs, date filters, or anywhere the user needs to see surrounding dates for context.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Set min and max dates to limit selection to a valid window, like only future dates for a booking or the current quarter for a report.'
			},
			{
				guidance: true,
				description:
					'Use range mode when the user needs to pick a start and end date, like a trip or a time-off request.'
			},
			{
				guidance: true,
				description:
					'Use dateConstraints to disable specific dates like weekends or holidays, and explain why they are unavailable.'
			},
			{
				guidance: true,
				description:
					'Show two months side by side when the user frequently selects dates that span a month boundary.'
			},
			{
				guidance: false,
				description:
					'Use a calendar for dates far in the past or future like a birth date. A text input is faster for open-ended entry.'
			},
			{
				guidance: false,
				description:
					'Disable large blocks of dates without context. The user should understand why dates are unavailable.'
			}
		],
		anatomy: [
			{
				name: 'Month header',
				required: true,
				description:
					'The month name and year with navigation arrows to move between months. The arrows mirror automatically under dir="rtl".'
			},
			{
				name: 'Day grid',
				required: true,
				description: 'A 7-column grid of days with column headers for the day names.'
			},
			{
				name: 'Selected day',
				required: false,
				description:
					'The currently selected date, highlighted. In range mode, the start and end dates plus the days between them.'
			},
			{
				name: 'Today marker',
				required: false,
				description: 'A subtle indicator on the current date for orientation.'
			}
		]
	},
	props: [
		{
			name: 'mode',
			type: "'single' | 'range'",
			description: 'Selection mode.',
			default: "'single'"
		},
		{
			name: 'value',
			type: '`${number}${number}${number}${number}-${number}${number}-${number}${number}` | DateRange',
			description: 'Controlled selected value.'
		},
		{
			name: 'defaultValue',
			type: '`${number}${number}${number}${number}-${number}${number}-${number}${number}` | DateRange',
			description: 'Uncontrolled default value.'
		},
		{
			name: 'onChange',
			type: '((value: `${number}${number}${number}${number}-${number}${number}-${number}${number}`, valueAsDate: Date) => void) | ((value: DateRange) => void)',
			description: 'Selection callback.'
		},
		{
			name: 'numberOfMonths',
			type: '2 | 1',
			description: 'Number of months to display.',
			default: '1'
		},
		{
			name: 'min',
			type: 'ISODateString',
			description: 'Minimum selectable date.'
		},
		{
			name: 'max',
			type: 'ISODateString',
			description: 'Maximum selectable date.'
		},
		{
			name: 'dateConstraints',
			type: 'ReadonlyArray<(date: Date) => boolean>',
			description: 'Custom constraint functions.'
		},
		{
			name: 'maxRangeSpan',
			type: 'number',
			description:
				'Range mode: max days a range may span, both endpoints counted (7 = a 7-day window). Caps the window from the picked start; before a start is picked every day stays selectable.'
		},
		{
			name: 'minRangeSpan',
			type: 'number',
			description:
				'Range mode: min days a range must span, both endpoints counted (2 forbids a single-day range). Clicking the start again commits a one-day range when allowed, or cancels the in-progress selection when the minimum is longer. Default 1.'
		},
		{
			name: 'focusDate',
			type: 'ISODateString',
			description:
				'Controlled visible month. Unset, the calendar opens on the selected date, else on today clamped into the min/max window.'
		},
		{
			name: 'onFocusDateChange',
			type: '(focusDate: ISODateString) => void',
			description: 'Navigation callback.'
		},
		{
			name: 'handleRef',
			type: 'CalendarHandle | null',
			description: 'Imperative handle for calendar navigation, including navigateTo().'
		},
		{
			name: 'hasOutsideDays',
			type: 'boolean',
			description: 'Show days from adjacent months.',
			default: 'true'
		},
		{
			name: 'hasWeekNumbers',
			type: 'boolean',
			description: 'Show ISO week numbers.',
			default: 'false'
		},
		{
			name: 'hasVariableRowCount',
			type: 'boolean',
			description: 'Variable vs fixed 6-row grid.',
			default: 'false'
		},
		{
			name: 'weekStartsOn',
			type: "0 | 6 | 2 | 4 | 1 | 3 | 5 | 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat'",
			description:
				'First day of week. Accepts a number (0=Sunday) or a three-letter day name (e.g. "mon").',
			default: '0'
		}
	]
};
