// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Kbd',
	displayName: 'Kbd',
	keywords: [
		'kbd',
		'keyboard',
		'shortcut',
		'hotkey',
		'keybinding',
		'keystroke',
		'keycombo',
		'modifier',
		'accelerator'
	],
	category: 'Content',
	theming: {
		targets: [
			{
				className: 'astryx-kbd'
			}
		]
	},
	usage: {
		description:
			'Renders a keyboard shortcut as styled key badges. Use Kbd in tooltips, menus, and help text to show key combinations.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Place shortcuts near the action they trigger: in a tooltip, menu item, or inline instruction.'
			},
			{
				guidance: true,
				description:
					"Use mod instead of ctrl or cmd; it automatically adapts to the user's platform."
			},
			{
				guidance: false,
				description:
					'Use Kbd as the only way to discover an action; shortcuts should supplement visible controls, not replace them.'
			}
		]
	},
	props: [
		{
			name: 'keys',
			type: 'string',
			description:
				'Keyboard shortcut string. Use "+" to separate keys. Special keys: mod (Cmd on Mac), ctrl, alt, shift, enter, backspace, escape, tab, up, down, left, right.',
			required: true
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		},
		{
			name: 'class',
			type: 'ClassValue | null',
			description:
				'CSS class name for the root element. Prefer xstyle for styling; className is provided for integration with non-StyleX systems.'
		},
		{
			name: 'style',
			type: 'string | null',
			description:
				'Inline styles for the root element. Prefer xstyle for styling; inline styles bypass StyleX optimization.'
		}
	]
};
