import { readdirSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * Astryx's `src/docPropReferences.test.ts`, ported case for case — **2 upstream
 * `it` declarations at the 0.5.0 pin, 2 here**, in upstream's order and under
 * upstream's titles. Nothing dropped, nothing added, and both assertions are
 * upstream's.
 *
 * A **server** project file (`*.test.ts`), as upstream's is: it reads doc
 * modules off disk and renders nothing.
 *
 * Upstream's premise (#3360): doc prose is LLM training signal, so a bullet that
 * says "the `syntaxTheme` prop on CodeBlock" when no such prop is documented
 * steers codegen straight at a hallucinated API. The scan finds every "X prop on
 * Y" phrase anywhere in a doc module and checks that Y's own `props[]` lists X.
 *
 * **The premise holds harder here than upstream, and that is why this is not a
 * tautology.** These `.doc.mjs` files are generated by
 * `docs/scripts/emit-core-docs.mjs`, which reconciles two sources that can
 * disagree: the **prose is upstream's, verbatim**, while `props[]` is derived
 * from *this* package's compiled declarations. So a prop upstream documents and
 * this port does not implement leaves its prose behind and its entry gone —
 * exactly the dangling reference this case catches, and precisely the case the
 * emitter's own `--check` cannot see, because `--check` only asks whether the
 * committed file matches what the emitter would write again.
 *
 * ## Three translations, none of them a case
 *
 * **Module shape.** Upstream's docs are CommonJS with `docs` / `docsZh` keys and
 * are read with `require()`. This port's are ESM with a single `export default`,
 * so they are read with `await import()` and the block is `mod.default`.
 *
 * **No `docsZh`.** Upstream carries a second, Chinese doc block per file, and
 * its `collectStrings` walk reaches that prose too. This port has no translated
 * docs, so the walk covers one block per file. That is an absence in the
 * documentation surface, not a dropped case: the `it` is declared once and scans
 * every string it finds.
 *
 * **Where the docs live.** `src/lib/**` here against upstream's `src/**`, and
 * one file per documented export rather than one per component directory.
 *
 * `UNIVERSAL_PROPS` is upstream's set, unchanged. Widening it to cover Svelte's
 * own universals (`class`, `children`) would be weakening the guard, and nothing
 * needs it: the scan is clean at 0.4.5.
 */

const SRC_DIR = resolve(__dirname, '../lib');

type DocExport = {
	name?: string;
	props?: { name: string }[];
	components?: { name?: string; props?: { name: string }[] }[];
};

/**
 * `components[]` is read exactly as upstream reads it even though this port's
 * emitter writes one file per documented export and never populates it. Keeping
 * the reader identical costs nothing and means a future sub-component entry is
 * covered the day it appears, rather than silently unscanned.
 */
type DocModule = { default?: DocExport };

/**
 * Props intentionally omitted from doc `props[]`: the CLI's `ComponentPropDoc`
 * contract says to skip internal/styling props, so prose may reference them even
 * though no doc lists them.
 */
const UNIVERSAL_PROPS = new Set(['xstyle', 'className', 'style', 'ref', 'data-testid']);

/**
 * Matches prose like "the foo prop on Bar", "foo prop of Bar", and conjunction
 * targets: "foo prop on Bar or Baz". Group 1 is the prop (camelCase, lowercase
 * first letter), group 2 the component name list.
 */
const PROP_REF_PATTERN =
	/\b([a-z][A-Za-z0-9]*) prop (?:on|of) (?:the )?([A-Z][A-Za-z0-9]*(?:(?:,(?: and| or)?| and| or) [A-Z][A-Za-z0-9]*)*)/g;

/** A same-string negation marks the reference as a deliberate counter-signal. */
const NEGATION_PATTERN = /no such prop|does not exist|doesn't exist/i;

function findDocFiles(dir: string): string[] {
	const files: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...findDocFiles(full));
		} else if (entry.name.endsWith('.doc.mjs')) {
			files.push(full);
		}
	}
	return files;
}

/** Collect every string value reachable from a doc module export. */
function collectStrings(value: unknown, out: string[]): void {
	if (typeof value === 'string') {
		out.push(value);
	} else if (Array.isArray(value)) {
		for (const item of value) {
			collectStrings(item, out);
		}
	} else if (value && typeof value === 'object') {
		for (const item of Object.values(value)) {
			collectStrings(item, out);
		}
	}
}

const docFiles = findDocFiles(SRC_DIR);

// Loaded once, up front: `await import()` is async where upstream's `require()`
// is not, and the scan below runs inside a synchronous `it`.
const docModules = new Map<string, DocExport | undefined>();
for (const file of docFiles) {
	docModules.set(file, ((await import(pathToFileURL(file).href)) as DocModule).default);
}

// Component name → documented prop names, from every doc file's props[] (single
// and sub-component docs) and inline components[] entries.
const documentedProps = new Map<string, Set<string>>();
for (const file of docFiles) {
	const docs = docModules.get(file);
	if (!docs) {
		continue;
	}
	const entries = [{ name: docs.name, props: docs.props }, ...(docs.components || [])];
	for (const { name, props } of entries) {
		if (!name || !Array.isArray(props)) {
			continue;
		}
		const set = documentedProps.get(name) || new Set<string>();
		for (const prop of props) {
			set.add(prop.name);
		}
		documentedProps.set(name, set);
	}
}

interface Violation {
	file: string;
	component: string;
	prop: string;
	excerpt: string;
}

function findViolations(): Violation[] {
	const violations: Violation[] = [];
	for (const file of docFiles) {
		const strings: string[] = [];
		collectStrings(docModules.get(file), strings);
		for (const text of strings) {
			let match;
			while ((match = PROP_REF_PATTERN.exec(text)) !== null) {
				const [, prop, componentList] = match;
				if (UNIVERSAL_PROPS.has(prop) || NEGATION_PATTERN.test(text)) {
					continue;
				}
				for (const component of componentList.split(/,(?: and| or)?| and | or /)) {
					const name = component.trim();
					if (!name) {
						continue;
					}
					const known = documentedProps.get(name);
					if (known && !known.has(prop)) {
						violations.push({
							file: relative(SRC_DIR, file),
							component: name,
							prop,
							excerpt: text.slice(Math.max(0, match.index - 40), match.index + match[0].length + 20)
						});
					}
				}
			}
		}
	}
	return violations;
}

describe('doc prose prop references', () => {
	it('sanity: discovers doc files and documented components', () => {
		expect(docFiles.length).toBeGreaterThan(0);
		expect(documentedProps.size).toBeGreaterThan(0);
	});

	it('every "X prop on Y" reference names a documented prop of Y', () => {
		const violations = findViolations();
		expect(
			violations,
			violations
				.map(
					(v) =>
						`${v.file} references prop "${v.prop}" on ${v.component}, ` +
						`which does not document it (…${v.excerpt}…). Either the prop ` +
						`doesn't exist (fix the prose; negate with "no such prop ` +
						`exists" if countering a known hallucination) or it exists in ` +
						`source but is missing from the component's doc props[] (add it).`
				)
				.join('\n')
		).toEqual([]);
	});
});
