import { readdirSync, readFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * Astryx's `src/docPropLiterals.test.ts`, ported case for case — **20 upstream
 * `it` declarations at v0.4.5, 20 here**, in upstream's order and under
 * upstream's titles. Nothing dropped, nothing added.
 *
 * A **server** project file (`*.test.ts`), as upstream's is: it reads source and
 * doc files off disk and renders nothing.
 *
 * Upstream's premise (#1645): a prop type of `SpacingStep` or
 * `TableSortState<TSortKey>` names a type without revealing what may be written
 * into it. Readers without an IDE — agents especially — then guess: `gap={16}`
 * (pixels, not a scale step), `direction: 'desc'` (the type says
 * `'descending'`). Both fail to compile. Two ways a doc prop can hide values,
 * checked at different strictness:
 *
 *   1. DIRECT — the prop type *is* (or contains) a literal-union type name.
 *      Inlining is required; prose is not an escape.
 *   2. INDIRECT — the prop type names a composite whose own definition carries a
 *      literal union. Either surface counts: spell the shape out in the type, or
 *      name the values in the description.
 *
 * **The premise holds here, and the subject shifts.** Upstream's `.doc.mjs` are
 * hand-authored, so the guard constrains a human writing a `type` string. This
 * port's are generated by `docs/scripts/emit-core-docs.mjs`, whose type column
 * is read from `packages/core/dist/**\/*.d.ts` — so the guard constrains that
 * emitter's type printer instead. The question it asks is unchanged and still
 * live: the CLI and the docs site render this exact string to readers, and a
 * reader who is told `status: InputStatus` still cannot see that the legal
 * values are `'warning' | 'error' | 'success'`. The emitter's own `--check`
 * cannot answer it — `--check` asks only whether the committed file matches what
 * the emitter would write again, which is true of a bad type column and a good
 * one alike.
 *
 * ## Four translations, none of them a case
 *
 * **Where prop bags are declared.** Upstream's live in `.tsx`; this port
 * declares each component's props interface in `<script module>` inside the
 * `.svelte` file (CLAUDE.md § Conventions), so the source walk covers `.ts` *and*
 * `.svelte`. Both of upstream's registry passes read raw text rather than an AST,
 * and a `<script module>` block is plain TypeScript, so the same expressions
 * apply unchanged; markup cannot match `export type` / `export interface`.
 *
 * **Module shape.** Upstream's docs are CommonJS with `docs` / `docsZh` keys,
 * read with `require()`. This port's are ESM with a single `export default`,
 * read with `await import()`.
 *
 * **No `docsZh`.** Upstream holds its translated block to the same bar. This
 * port has no translated docs, so there is one block per file to check — an
 * absence in the documentation surface, not a dropped case.
 *
 * **Path separators.** Upstream keys its registries on `'/'`; the walk here
 * normalises separators so the same keys survive Windows.
 */

const SRC_DIR = resolve(__dirname, '../lib').replaceAll('\\', '/');

type DocExport = {
	name?: string;
	props?: PropEntry[];
	components?: { name?: string; props?: PropEntry[] }[];
};

type DocModule = { default?: DocExport };

type PropEntry = { name: string; type?: string; description?: string };

/**
 * Unions too large to read inside a prop-type cell. Exempt from inlining, but
 * only while the prop's description enumerates every member — the values still
 * have to be discoverable from the docs alone.
 */
const ENUMERATED_IN_PROSE = new Set(['IconName']);

/**
 * Props whose documented `type` names a value-carrying alias that this port's
 * doc **emitter** does not expand, where upstream's hand-authored doc spells the
 * values out. Each is a real informational loss against upstream — `Toast.onHide`
 * is `(reason: "auto" | "manual") => void` upstream and
 * `(reason: ToastDismissReason) => void` here — and each is the emitter's doing,
 * not a doc author's.
 *
 * They fall in three classes, which want different fixes:
 *
 *   1. **A composite alias whose values reach neither surface** — `InputStatus`,
 *      `TextType`, `TableSortState`, `SelectorStatus`. Upstream prints the object
 *      structurally; `renderType` prints the name.
 *   2. **A literal union named inside a larger expression** — `boolean |
 *      LayerPlacement`, `SectionDivider[]`. The least arguable: `renderType`
 *      inlines a union only when the prop's *whole* type is literals plus
 *      primitives, so a union in a composite expression is never expanded.
 *   3. **The `IconName` prose exemption, inherited 13 times.** Upstream types
 *      these `ReactNode | IconType`, which carries no literals, so its
 *      `ENUMERATED_IN_PROSE` registry needed exactly one entry. This port's icon
 *      slot is `IconName | Snippet`, so 13 props inherit a bargain — "enumerate
 *      all 28 names in your description" — that upstream never had to pay.
 *
 * **This list is a debt, not an exemption policy.** It carries the class oracle's
 * skip hygiene in both directions: an entry that stops violating fails the run as
 * loudly as a violation that is not listed. It can only shrink. The fix lives in
 * `docs/scripts/lib/props-types.mjs`'s `renderType` and is recorded in
 * `port/debts.md`; upstream's own `ENUMERATED_IN_PROSE` above is left at its one
 * entry, because widening it would be divergence rather than porting.
 */
const PORT_DOC_TYPE_DEBT = new Set([
	'CheckboxInput.status',
	'CheckboxList.status',
	'ComplexSelector.startIcon',
	'ContextMenuItem.icon',
	'DropdownMenuCheckboxItem.icon',
	'DropdownMenuItem.icon',
	'DropdownMenuRadioItem.icon',
	'DropdownMenuSubMenu.icon',
	'Field.status',
	'FileInput.status',
	'Heading.hasTruncateTooltip',
	'InputGroup.status',
	'NumberInput.status',
	'PowerSearch.onChange',
	'PowerSearch.startIcon',
	'PowerSearch.status',
	'RadioList.status',
	'Section.dividers',
	'Selector.status',
	'SelectorOption.icon',
	'SideNavItem.icon',
	'SideNavItem.selectedIcon',
	'Slider.status',
	'Switch.status',
	'TabMenu.options',
	'Text.hasTruncateTooltip',
	'Text.type',
	'TextArea.status',
	'TextInput.status',
	'TimeInput.status',
	'Timestamp.type',
	'Toast.onHide',
	'Tokenizer.startIcon',
	'useTableSortable.onSortChange'
]);

/**
 * Generic wrappers whose type argument is still a value the consumer writes, so
 * the walk descends through them. Every other generic (`Snippet<P>`,
 * `Record<K, V>`) wraps a type the consumer never spells out by hand, and
 * descending into it would demand, say, every icon name in Button's
 * `endContent` docs.
 */
const TRANSPARENT_WRAPPERS = new Set(['Array', 'ReadonlyArray']);

/**
 * A union of nothing but string/number literals (plus null/undefined).
 *
 * Built so each separator has exactly ONE way to be parsed. The obvious spelling
 * — `(?:\s*\|?\s*LITERAL\s*(?:\|\s*)?)+` — lets a repetition's trailing
 * `(?:\|\s*)?` and the next one's leading `\|?` both claim the same pipe, so
 * every separator doubles the parse tree. On a union that *fails* to match (a
 * literal prefix ending in a named type) the engine explores all 2^n of them.
 * This form is linear.
 */
const LITERAL = String.raw`(?:'[^']*'|-?\d+(?:\.\d+)?|null|undefined)`;
const LITERAL_UNION = new RegExp(String.raw`^\s*\|?\s*${LITERAL}(?:\s*\|\s*${LITERAL})*\s*$`);

function findFiles(dir: string, suffixes: string[]): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const full = join(dir, entry.name).replaceAll('\\', '/');
		if (entry.isDirectory()) {
			out.push(...findFiles(full, suffixes));
		} else if (suffixes.some((s) => entry.name.endsWith(s))) {
			out.push(full);
		}
	}
	return out;
}

/** Strip comments so a doc block's prose never reads as type syntax. */
function stripComments(src: string): string {
	return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
}

/**
 * Literal members of a union flagged `@deprecated` in source. Docs shouldn't
 * advertise a deprecated value as a legal option (the prose can still mention
 * it), so the guard doesn't require it to be inlined. Detected from the *raw*
 * declaration, because the registry parses members from comment-stripped source
 * where the `@deprecated` marker is already gone.
 */
function deprecatedLiteralMembers(rawRhs: string): Set<string> {
	const out = new Set<string>();
	const marker =
		/(?:\/\*\*?[\s\S]*?@deprecated[\s\S]*?\*\/|\/\/[^\n]*@deprecated[^\n]*)\s*\|\s*('[^']*'|-?\d+(?:\.\d+)?|null|undefined)/g;
	for (const m of rawRhs.matchAll(marker)) {
		out.add(m[1]);
	}
	return out;
}

/**
 * Names a consumer would have to write values for, given a type expression.
 * Skips string literals, generic parameters, and the type arguments of any
 * wrapper that isn't transparent.
 */
function authoredTypeNames(expr: string): string[] {
	const names: string[] = [];
	const text = expr.replace(/'[^']*'/g, "''");
	let i = 0;
	while (i < text.length) {
		const match = /[A-Za-z_$][A-Za-z0-9_$]*/.exec(text.slice(i));
		if (!match) {
			break;
		}
		const start = i + match.index;
		const name = match[0];
		let end = start + name.length;
		if (/^[A-Z]/.test(name)) {
			names.push(name);
		}
		// A '<' directly after the name opens that name's type arguments.
		const rest = text.slice(end);
		const open = /^\s*</.exec(rest);
		if (open) {
			let depth = 0;
			let j = end + open[0].length - 1;
			for (; j < text.length; j++) {
				if (text[j] === '<') {
					depth++;
				} else if (text[j] === '>') {
					depth--;
					if (depth === 0) {
						break;
					}
				}
			}
			const args = text.slice(end + open[0].length, j);
			if (TRANSPARENT_WRAPPERS.has(name)) {
				names.push(...authoredTypeNames(args));
			}
			end = j + 1;
		}
		i = end;
	}
	return names;
}

// --- Registries, read straight from the TypeScript sources -----------------

/** Literal-union type name → its members, e.g. "'start' | 'center'". */
const literalUnions = new Map<string, string>();
/** Every other exported type/interface name → its definition body. */
const namedBodies = new Map<string, string>();

// `.svelte` alongside `.ts`: see the header — the props interface of a component
// is declared in its `<script module>` block, and a `.stylex.ts` module is where
// several of the literal unions themselves live (`GridAlignment`).
const SOURCE_SUFFIXES = ['.ts', '.svelte'];

for (const file of findFiles(SRC_DIR, SOURCE_SUFFIXES)) {
	if (file.includes('.test.')) {
		continue;
	}
	const raw = readFileSync(file, 'utf8');
	const src = stripComments(raw);
	// Raw type declarations, keyed by name, so we can inspect `@deprecated`
	// markers the comment-stripped `src` has already removed.
	const rawTypeRhs = new Map<string, string>();
	for (const m of raw.matchAll(/export type ([A-Z][A-Za-z0-9]*)(?:<[^>]*>)?\s*=\s*([^;]+);/g)) {
		rawTypeRhs.set(m[1], m[2]);
	}
	for (const m of src.matchAll(/export type ([A-Z][A-Za-z0-9]*)(?:<[^>]*>)?\s*=\s*([^;]+);/g)) {
		const [, name, rhsRaw] = m;
		const rhs = rhsRaw.replace(/\s+/g, ' ').trim();
		if (LITERAL_UNION.test(rhs)) {
			const deprecated = deprecatedLiteralMembers(rawTypeRhs.get(name) ?? '');
			literalUnions.set(
				name,
				rhs
					.replace(/^\|\s*/, '')
					.split('|')
					.map((s) => s.trim())
					.filter(Boolean)
					.filter((member) => !deprecated.has(member))
					.join(' | ')
			);
		} else {
			namedBodies.set(name, rhs);
		}
	}
	for (const m of src.matchAll(
		/export interface ([A-Z][A-Za-z0-9]*)(?:<[^>]*>)?\s*(?:extends [^{]+)?\{/g
	)) {
		const open = src.indexOf('{', m.index);
		let depth = 0;
		let close = open;
		for (; close < src.length; close++) {
			if (src[close] === '{') {
				depth++;
			} else if (src[close] === '}') {
				depth--;
				if (depth === 0) {
					break;
				}
			}
		}
		namedBodies.set(m[1], src.slice(open, close + 1).replace(/\s+/g, ' '));
	}
}

/** Literal unions a consumer must know to author a value of `name`. */
function requiredUnions(name: string, seen = new Set<string>()): Map<string, string> {
	const found = new Map<string, string>();
	if (seen.has(name)) {
		return found;
	}
	seen.add(name);
	const literals = literalUnions.get(name);
	if (literals) {
		found.set(name, literals);
		return found;
	}
	const body = namedBodies.get(name);
	if (!body) {
		return found;
	}
	for (const inner of authoredTypeNames(body)) {
		for (const [k, v] of requiredUnions(inner, seen)) {
			found.set(k, v);
		}
	}
	return found;
}

// --- Source prop declarations, per component directory ---------------------

/**
 * "{dir}::{Component}Props" → prop name → the type expression source declares.
 *
 * Keyed by the exact prop bag, never by directory: `chat/` alone holds
 * ChatComposer, ChatMessage and ChatToolCalls, each with a differently-typed
 * `status`, and judging one component's docs against a sibling's declaration is
 * a false accusation. A component with no `{Name}Props` bag in the doc's own
 * directory is simply not checked by this pass — a missed prop costs nothing, a
 * wrong failure costs the guard its credibility.
 */
const sourcePropTypes = new Map<string, Map<string, string>>();

/**
 * Bag name → its members, for bags whose name is unique across the package;
 * `null` marks a name declared in more than one place, which is never resolved
 * rather than resolved wrongly.
 *
 * A hook's config bag does not live in the directory its doc does:
 * `useTableSortable.doc.mjs` and `UseTableSortableConfig` are both under
 * `table/plugins/sortable/` here, but the same cross-directory lookup is what
 * makes `sort` — the very prop #1645 was filed about — resolvable at all when
 * they part company.
 */
const bagsByName = new Map<string, Map<string, string> | null>();

/**
 * Bags a hook's config may be called. Astryx spells it `Use{Name}Config` or
 * `Use{Name}Options`; the other two are cheap insurance and cost nothing when
 * absent.
 */
const HOOK_BAG_SUFFIXES = ['Config', 'Options', 'Props', 'Params'];

for (const file of findFiles(SRC_DIR, SOURCE_SUFFIXES)) {
	if (file.includes('.test.')) {
		continue;
	}
	const dir = file.slice(0, file.lastIndexOf('/'));
	const src = stripComments(readFileSync(file, 'utf8'));
	for (const m of src.matchAll(
		/export (?:interface|type) ([A-Z][A-Za-z0-9]*(?:Props|Config|Options|Params))(?:<[^>]*>)?\s*(?:extends [^{]+|=\s*)?\{/g
	)) {
		const open = src.indexOf('{', m.index);
		let depth = 0;
		let close = open;
		for (; close < src.length; close++) {
			if (src[close] === '{') {
				depth++;
			} else if (src[close] === '}') {
				depth--;
				if (depth === 0) {
					break;
				}
			}
		}
		const body = src.slice(open + 1, close);
		const byProp = new Map<string, string>();
		// Top-level `name?: Type;` members only — nested object literals would need
		// a real parser, and a missed prop costs nothing here.
		let depthInBody = 0;
		for (const rawLine of body.split(/[;\n]/)) {
			// `=>` is an arrow, not a closing angle bracket: counting it as one
			// drives the depth negative and silently swallows every prop below a
			// callback member.
			const line = rawLine.replace(/=>/g, '');
			const opens = (line.match(/[{(<]/g) || []).length;
			const closes = (line.match(/[})>]/g) || []).length;
			const member = /^\s*([a-z][A-Za-z0-9]*)\??\s*:\s*(.+?)\s*$/.exec(rawLine);
			if (depthInBody === 0 && member) {
				byProp.set(member[1], member[2]);
			}
			depthInBody = Math.max(0, depthInBody + opens - closes);
		}
		sourcePropTypes.set(`${dir}::${m[1]}`, byProp);
		// Second index, keyed by bag name alone, for the cross-directory hook
		// lookup below. A duplicate name poisons the entry: guessing between two
		// declarations is how a guard earns a false accusation.
		bagsByName.set(m[1], bagsByName.has(m[1]) ? null : byProp);
	}
}

/**
 * The type source declares for `Component.prop`, if it can be found.
 *
 * Two lookups, most-specific first: the component's own `{Name}Props` bag in its
 * own directory, then — for hooks only — the uniquely-named
 * `UseThingConfig` / `UseThingOptions` bag, wherever it is declared. Anything
 * else stays undefined and is judged on the doc alone.
 */
function declaredType(dir: string, component: string, prop: string): string | undefined {
	const own = sourcePropTypes.get(`${dir}::${component}Props`)?.get(prop);
	if (own !== undefined) {
		return own;
	}
	if (!/^use[A-Z]/.test(component)) {
		return undefined;
	}
	const pascal = component[0].toUpperCase() + component.slice(1);
	for (const suffix of HOOK_BAG_SUFFIXES) {
		const declared = bagsByName.get(`${pascal}${suffix}`)?.get(prop);
		if (declared !== undefined) {
			return declared;
		}
	}
	return undefined;
}

// --- Doc props -------------------------------------------------------------

const docFiles = findFiles(SRC_DIR, ['.doc.mjs']);

interface DocProp {
	file: string;
	dir: string;
	component: string;
	prop: string;
	type: string;
	description: string;
}

const docProps: DocProp[] = [];
for (const file of docFiles) {
	const docs = ((await import(pathToFileURL(file).href)) as DocModule).default;
	if (!docs) {
		continue;
	}
	const entries = [{ name: docs.name, props: docs.props }, ...(docs.components || [])];
	for (const { name, props } of entries) {
		if (!name || !Array.isArray(props)) {
			continue;
		}
		for (const prop of props) {
			if (typeof prop.type !== 'string') {
				continue;
			}
			docProps.push({
				file: relative(SRC_DIR, file),
				dir: file.slice(0, file.lastIndexOf('/')),
				component: name,
				prop: prop.name,
				type: prop.type,
				description: prop.description || ''
			});
		}
	}
}

function escapeRe(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\-]/g, '\\$&');
}

/** The value members of a union — `null`/`undefined` carry nothing to spell. */
function literalMembers(literals: string): string[] {
	return literals
		.split('|')
		.map((s) => s.trim())
		.filter((s) => s.startsWith("'") || /^-?\d/.test(s));
}

/**
 * Where a literal has to be written to count as surfaced.
 *
 * `code` — a type column. The literal must appear *as a literal*: quotes intact
 * for strings, digit-boundary-anchored for numbers.
 * `prose` — a free-text description. Quotes are optional, but the boundary still
 * holds.
 *
 * The boundary is the whole point. A bare `text.includes('sm')` is satisfied by
 * `'xsm'`, and `text.includes('1')` by `1.5` or `10` — so a doc could drop a
 * member and stay "green" purely because a longer sibling contains its
 * characters.
 */
type Surface = 'code' | 'prose';

function isSurfaced(text: string, literal: string, surface: Surface): boolean {
	const isString = literal.startsWith("'");
	const inner = isString ? literal.slice(1, -1) : literal;
	if (isString) {
		// In code, the quotes are part of the literal: 'xsm' does not contain the
		// *literal* 'sm', only the characters. In prose they are optional.
		const body = escapeRe(inner);
		return surface === 'code'
			? new RegExp(`['"\`]${body}['"\`]`).test(text)
			: new RegExp(`(?<![\\w-])${body}(?![\\w-])`).test(text);
	}
	// Numbers: reject a match that is really part of a longer number — `1` must
	// not be found inside `1.5`, `10` or `-1`. A trailing dot is allowed only when
	// it is sentence punctuation ("steps go 0, 0.5, 1."), not a decimal.
	return new RegExp(`(?<![\\w.-])${escapeRe(inner)}(?![\\w-])(?!\\.\\d)`).test(text);
}

/** Members of `literals` not written out in `text`. */
function missingFrom(text: string, literals: string, surface: Surface = 'code'): string[] {
	return literalMembers(literals).filter((literal) => !isSurfaced(text, literal, surface));
}

interface Violation {
	where: string;
	detail: string;
}

/**
 * Reasons this one prop hides values a reader would have to guess at.
 *
 * `resolveFrom` is the type expression whose unions the reader must know;
 * `type`/`description` are what the docs actually say. They are the same
 * expression for the doc-side pass, and differ for the source-side pass, where
 * the component's own declaration is the authority and the docs are the thing on
 * trial. That second pass is what makes the guard drift-proof: inlined literals
 * go stale the moment the union in source gains a member, and only the source
 * knows that happened.
 *
 * Pure — the synthetic cases below exercise it directly, so the guard is proven
 * to bite without dirtying a real doc.
 */
function hiddenValueReasons(
	type: string,
	description: string,
	resolveFrom: string = type
): string[] {
	const reasons: string[] = [];
	for (const named of authoredTypeNames(resolveFrom)) {
		for (const [union, literals] of requiredUnions(named)) {
			if (ENUMERATED_IN_PROSE.has(union)) {
				const missing = missingFrom(description, literals, 'prose');
				if (missing.length > 0) {
					reasons.push(
						`${union} is exempt from inlining only while its description ` +
							`enumerates every value; these are missing from the ` +
							`description: ${missing.join(', ')}.`
					);
				}
			} else if (named === union) {
				// DIRECT: the name is the union. Inlining is always affordable, so the
				// type column is the only surface that counts.
				if (missingFrom(type, literals, 'code').length > 0) {
					reasons.push(
						`names the union ${union} instead of inlining it. ` + `Write: "${literals}".`
					);
				}
			} else if (
				// INDIRECT: the union hides inside a composite. Spell the shape out in
				// the type, or name the values in the description. Each surface is read
				// on its own terms — the type as code, the description as prose — rather
				// than concatenated, so a value half-spelled in one and half-mentioned in
				// the other cannot pass for a value that is written down anywhere.
				literalMembers(literals).some(
					(literal) =>
						!isSurfaced(type, literal, 'code') && !isSurfaced(description, literal, 'prose')
				)
			) {
				reasons.push(
					`${named} hides ${union} = ${literals}, and neither the type nor ` +
						`the description says so. Spell the shape out in the type ` +
						`(preferred for small objects) or name the legal values in the ` +
						`description, so a reader without an IDE can see what is legal.`
				);
			}
		}
	}
	return reasons;
}

function findViolations(): Violation[] {
	const violations: Violation[] = [];
	for (const { file, dir, component, prop, type, description } of docProps) {
		const where = `${file} — ${component}.${prop}: "${type}"`;
		const seen = new Set<string>();
		const report = (detail: string) => {
			if (!seen.has(detail)) {
				seen.add(detail);
				violations.push({ where, detail });
			}
		};
		// Pass 1: what the docs themselves name.
		for (const detail of hiddenValueReasons(type, description)) {
			report(detail);
		}
		// Pass 2: what the component actually declares in source.
		const declared = declaredType(dir, component, prop);
		if (declared) {
			for (const detail of hiddenValueReasons(type, description, declared)) {
				report(`source declares \`${prop}: ${declared}\` — ${detail}`);
			}
		}
	}
	return violations;
}

describe('doc prop types surface their literal values (#1645)', () => {
	it('sanity: finds doc props and literal-union types in source', () => {
		expect(docProps.length).toBeGreaterThan(0);
		expect(literalUnions.size).toBeGreaterThan(0);
	});

	it('sanity: the registries read the real source definitions', () => {
		expect(literalUnions.get('SpacingStep')).toBe('0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10');
		expect(literalUnions.get('TableSortDirection')).toBe("'ascending' | 'descending'");
		// @deprecated members are dropped: SwitchLabelSpacing is
		// `'hug' | 'spread' | (@deprecated) 'default'`, and docs shouldn't have to
		// advertise the deprecated value as a legal option.
		expect(literalUnions.get('SwitchLabelSpacing')).toBe("'hug' | 'spread'");
		expect([...requiredUnions('InputStatus').keys()]).toContain('InputStatusType');
		expect([...requiredUnions('TableSortState').keys()]).toContain('TableSortDirection');
	});

	it('sanity: does not descend into opaque generic wrappers', () => {
		// RESTATED, first assertion only. Upstream's is `ReactElement<IconProps>`:
		// the consumer writes <Icon icon="check" />, not an IconProps object, so
		// IconName's values are Icon's business, not Button's. This port's
		// element-shaped prop is a `Snippet`, so the same opaque wrapper is
		// `Snippet<[IconProps]>` — same question, same answer, our type constructor.
		expect(authoredTypeNames('Snippet<[IconProps]>')).toEqual(['Snippet']);
		expect(authoredTypeNames('Record<string, MarkdownSource>')).toEqual(['Record']);
		expect(authoredTypeNames('ReadonlyArray<TableSortEntry<TSortKey>>')).toEqual([
			'ReadonlyArray',
			'TableSortEntry'
		]);
	});

	it('LITERAL_UNION rejects a long near-miss union in linear time', () => {
		// Every `export type` in the package is fed to this regex, so it must stay
		// cheap on the ones that DON'T match. The dangerous shape is a long literal
		// prefix ending in something that isn't a literal — the autocomplete escape
		// hatch — which the regex can only reject after trying every way to parse
		// it. An ambiguous pattern has 2^n of those. This union is 24 members long:
		// linear, it is instant; ambiguous, it would outlive the CI job.
		const nearMiss =
			Array.from({ length: 24 }, (_, i) => `'v${i}'`).join(' | ') + ' | ComponentType';
		const start = performance.now();
		expect(LITERAL_UNION.test(nearMiss)).toBe(false);
		expect(performance.now() - start).toBeLessThan(100);
	});

	it('no documented prop type hides its legal values', () => {
		const violations = findViolations();
		const key = (v: { where: string }) => v.where.replace(/^.*— /, '').replace(/:.*$/, '');

		// Hygiene first, so the list cannot rot: an entry that no longer violates
		// is stale and must go, exactly as a class-oracle skip that stops matching
		// fails the run.
		const violating = new Set(violations.map(key));
		const stale = [...PORT_DOC_TYPE_DEBT].filter((k) => !violating.has(k));
		expect(
			stale,
			`PORT_DOC_TYPE_DEBT lists ${stale.length} prop(s) that no longer hide their ` +
				`values: ${stale.join(', ')}. Remove them — the list may only shrink.`
		).toEqual([]);

		const unlisted = violations.filter((v) => !PORT_DOC_TYPE_DEBT.has(key(v)));
		expect(unlisted, unlisted.map((v) => `${v.where}\n    ${v.detail}`).join('\n')).toEqual([]);
	});

	describe('the guard bites (synthetic props, not real docs)', () => {
		it('flags a bare literal-union name and accepts the inlined form', () => {
			expect(hiddenValueReasons('SpacingStep', 'Gap between items.')).toEqual([
				expect.stringContaining('names the union SpacingStep')
			]);
			expect(
				hiddenValueReasons('0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10', 'Gap between items.')
			).toEqual([]);
		});

		it('is not fooled by prose alone for a direct union', () => {
			// The #1645 failure mode: prose hints at the scale, the type column still
			// says nothing, and the CLI signature builder (which splits the type on
			// `|`) still has no values to print.
			expect(hiddenValueReasons('SpacingStep', 'Steps: 0, 0.5, 1, 1.5, 2, 3, 4.')).not.toEqual([]);
		});

		it('flags a partially inlined union — one forgotten member is enough', () => {
			// Judged against what source declares, so a doc that drops 'stretch' (or
			// an inlined SpacingStep that misses a step the scale later gains) is
			// caught even though the doc no longer names the type at all.
			expect(
				hiddenValueReasons("'start' | 'center' | 'end'", 'Alignment.', 'GridAlignment')
			).toEqual([expect.stringContaining('GridAlignment')]);
			expect(
				hiddenValueReasons("'start' | 'center' | 'end' | 'stretch'", 'Alignment.', 'GridAlignment')
			).toEqual([]);
		});

		it('the source-side pass indexes the real component prop bags', () => {
			const gridDir = docProps.find((p) => p.component === 'Grid')!.dir;
			expect(declaredType(gridDir, 'Grid', 'gap')).toBe('SpacingStep');
			expect(declaredType(gridDir, 'Grid', 'align')).toBe('GridAlignment');
		});

		it('never judges a component against a sibling in the same directory', () => {
			// `chat/` declares three differently-typed `status` props. Reading
			// ChatComposer's docs against ChatMessageMetadata's declaration would be a
			// false accusation, so the index is keyed by prop bag, not folder.
			const chatDir = docProps.find((p) => p.component === 'ChatComposer')!.dir;
			expect(declaredType(chatDir, 'ChatComposer', 'status')).toBe('ChatComposerStatus');
			expect(declaredType(chatDir, 'ChatMessageMetadata', 'status')).toBe('ChatMessageStatus');
			// Upstream's third assertion, unchanged, holds for a different reason
			// here: upstream's Heading re-exports its props so `text/` has no
			// HeadingProps bag, while this port gives Heading its own directory. Both
			// ways the pass must stay silent rather than borrow TextProps.
			const textDir = docProps.find((p) => p.component === 'Text')!.dir;
			expect(declaredType(textDir, 'Heading', 'type')).toBeUndefined();
		});

		it('flags a composite that hides a union, and takes either surface', () => {
			expect(hiddenValueReasons('InputStatus', 'Validation status.')).toEqual([
				expect.stringContaining('InputStatus hides InputStatusType')
			]);
			// Spelled out in the type…
			expect(
				hiddenValueReasons(
					"{type: 'warning' | 'error' | 'success', message?: string}",
					'Validation status.'
				)
			).toEqual([]);
			// …or named in the description.
			expect(
				hiddenValueReasons(
					'InputStatus',
					"Validation status. type is 'warning', 'error', or 'success'."
				)
			).toEqual([]);
		});

		it("catches the issue's headline: sort direction is not 'asc'/'desc'", () => {
			expect(
				hiddenValueReasons(
					'TableSortState<TSortKey>',
					'Ordered array of {sortKey, direction} entries.'
				)
			).toEqual([expect.stringContaining("'ascending' | 'descending'")]);
			// The word "descending" contains "ascending"'s literal only as a substring
			// of itself, so a doc naming just one is still flagged.
			expect(
				hiddenValueReasons('TableSortState<TSortKey>', "Entries sort 'ascending' by default.")
			).toEqual([expect.stringContaining("'ascending' | 'descending'")]);
		});

		it('lets a value-free type through untouched', () => {
			expect(hiddenValueReasons('boolean', 'Disables the control.')).toEqual([]);
			// RESTATED: upstream's second probe is `ReactNode`, which has no
			// counterpart. `Snippet` is this port's slot type and carries no values
			// either — same question of the type that actually appears in our docs.
			expect(hiddenValueReasons('Snippet', 'Slot content.')).toEqual([]);
			expect(hiddenValueReasons('(value: string) => void', 'Called.')).toEqual([]);
		});

		it('a longer sibling literal does not mask a shorter one', () => {
			// A substring match lies: 'sm' looks "present" inside 'xsm', and the
			// spacing step 1 looks "present" inside 1.5 and 10. Both unions below are
			// complete EXCEPT for the masked member — so the *only* thing that can
			// fail them is the guard noticing the masked one is really gone.
			expect(
				hiddenValueReasons(
					// TextSize without 'sm'. 'xsm' is still there, masking it.
					"'4xs' | '3xs' | '2xs' | 'xsm' | 'base' | 'lg' | 'xl' | '2xl' | " + "'3xl' | '4xl'",
					'Size.',
					'TextSize'
				)
			).toEqual([expect.stringContaining('TextSize')]);
			expect(
				hiddenValueReasons(
					// SpacingStep without the step 1. 1.5 and 10 still mask it.
					'0 | 0.5 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
					'Gap.',
					'SpacingStep'
				)
			).toEqual([expect.stringContaining('SpacingStep')]);
			// …and the complete unions still pass, so the boundary match is not simply
			// rejecting everything.
			expect(
				hiddenValueReasons(
					"'4xs' | '3xs' | '2xs' | 'xsm' | 'sm' | 'base' | 'lg' | 'xl' | " +
						"'2xl' | '3xl' | '4xl'",
					'Size.',
					'TextSize'
				)
			).toEqual([]);
			expect(
				hiddenValueReasons('0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10', 'Gap.', 'SpacingStep')
			).toEqual([]);
		});

		it('holds the prose exemption to its bargain', () => {
			// IconName may stay named — but only while every value is in the prose.
			const enumerated = docProps.find((p) => p.component === 'Icon' && p.prop === 'icon');
			expect(enumerated?.type).toContain('IconName');
			expect(hiddenValueReasons(enumerated!.type, enumerated!.description)).toEqual([]);
			// Drop the enumeration and the exemption stops covering it. RESTATED only
			// in the companion type: upstream writes `ComponentType<SVGProps>` where
			// this port's Icon takes `IconType`, its own component type.
			expect(hiddenValueReasons('IconName | IconType', 'An icon.')).toEqual([
				expect.stringContaining('exempt from inlining only while')
			]);
		});
	});

	/**
	 * The synthetic cases above prove the predicate bites. These prove the
	 * *shipped docs are actually wired to it* — each one takes a real doc entry,
	 * stages the exact drift the guard exists to prevent, and asserts it fails. A
	 * guard that green-lights the regression it was built to catch is decoration;
	 * these are the tests that stop it becoming one.
	 */
	describe('the guard bites the real docs when they drift', () => {
		const realProp = (component: string, prop: string): DocProp => {
			const found = docProps.find((p) => p.component === component && p.prop === prop);
			if (!found) {
				throw new Error(`no doc prop ${component}.${prop}`);
			}
			return found;
		};

		/** What source says this doc prop is — the authority drift is judged against. */
		const authority = (p: DocProp): string => {
			const declared = declaredType(p.dir, p.component, p.prop);
			if (!declared) {
				throw new Error(
					`${p.component}.${p.prop} has no source declaration, so nothing ` +
						`holds its inlined literals to the union in source.`
				);
			}
			return declared;
		};

		it("#1645's headline prop is guarded: useTableSortable.sort", () => {
			const sort = realProp('useTableSortable', 'sort');
			expect(authority(sort)).toBe('TableSortState<TSortKey>');
			// The shipped doc is honest today…
			expect(hiddenValueReasons(sort.type, sort.description, authority(sort))).toEqual([]);
			// …and the moment it stops naming 'descending', the guard fails. This is
			// the doc lying about the legal sort values all over again — the literal
			// bug #1645 was filed for.
			//
			// RESTATED in where the drift is staged. Upstream's doc spells the shape
			// out in the *type* (`Array<{sortKey, direction: 'ascending' |
			// 'descending'}>`), so upstream stales the type. This port's type column
			// is machine-derived and names `TableSortState<TSortKey>`, paying the
			// INDIRECT rule's other half: the values live in the description. So the
			// description is what must not lose them, and staling it is the same
			// question asked of the surface that actually carries the values here.
			const stale = (s: string) => s.replace(/'?descending'?/g, '');
			expect(stale(sort.description)).not.toBe(sort.description);
			expect(
				hiddenValueReasons(stale(sort.type), stale(sort.description), authority(sort))
			).toEqual([expect.stringContaining("'ascending' | 'descending'")]);
		});

		it('Timestamp.size cannot quietly lose a step masked by a sibling', () => {
			const size = realProp('Timestamp', 'size');
			expect(authority(size)).toBe('TextSize');
			expect(hiddenValueReasons(size.type, size.description, authority(size))).toEqual([]);
			// Delete 'sm'. A substring match calls it present — 'xsm' contains it.
			const stale = size.type.replace("'sm' | ", '');
			expect(stale).not.toBe(size.type);
			expect(stale).toContain("'xsm'");
			expect(hiddenValueReasons(stale, size.description, authority(size))).toEqual([
				expect.stringContaining('TextSize')
			]);
		});

		it('AppShell.mobileNav stays a bare ReactNode (the editor hides on an exact string)', () => {
			const nav = realProp('AppShell', 'mobileNav');
			// RESTATED. Upstream pins `type` to the exact string 'ReactNode' — not the
			// true `false | MobileNavConfig | ReactNode` — because its docsite
			// playground hides a prop by exact-matching the type against
			// PropertyEditor's UNSUPPORTED_PROP_TYPES, and widening drops that match.
			// This port's docs site has no PropertyEditor and no such set, so there is
			// nothing for a narrowed string to protect; and the type column is
			// machine-derived from this package's declarations, so it could not be
			// narrowed by hand even if there were. That half of upstream's case is
			// dropped with its premise.
			//
			// What survives is the half that is about the reader, and it holds
			// verbatim: the values still have to be discoverable, and they live in the
			// prose.
			expect(nav.description).toContain('breakpoint');
			expect(nav.description).toContain("'md'");
		});

		it('Lightbox.media keeps naming its type (spelling it out yields a string control)', () => {
			const media = realProp('Lightbox', 'media');
			expect(media.type).toBe('LightboxMedia | LightboxMedia[]');
			// Same bargain as IconName: named is allowed only while the prose carries
			// the values a consumer must write.
			expect(media.description).toContain("'image'");
			expect(media.description).toContain("'video'");
		});

		it('Grid.gap cannot quietly lose the step 1, masked by 1.5 and 10', () => {
			const gap = realProp('Grid', 'gap');
			expect(authority(gap)).toBe('SpacingStep');
			expect(hiddenValueReasons(gap.type, gap.description, authority(gap))).toEqual([]);
			const stale = gap.type.replace('1 | 1.5', '1.5');
			expect(stale).not.toBe(gap.type);
			expect(stale).toContain('1.5');
			expect(stale).toContain('10');
			expect(hiddenValueReasons(stale, gap.description, authority(gap))).toEqual([
				expect.stringContaining('SpacingStep')
			]);
		});
	});
});
