/** NO-UPSTREAM: coverage beyond upstream — the header below says why. */

import { describe, expect, it } from 'vitest';

import CheckboxInputDocs from '$lib/components/checkbox-input/CheckboxInput.doc.mjs';
import CheckboxListDocs from '$lib/components/checkbox-list/CheckboxList.doc.mjs';
import DateInputDocs from '$lib/components/date-input/DateInput.doc.mjs';
import DateRangeInputDocs from '$lib/components/date-range-input/DateRangeInput.doc.mjs';
import DateTimeInputDocs from '$lib/components/date-time-input/DateTimeInput.doc.mjs';
import FileInputDocs from '$lib/components/file-input/FileInput.doc.mjs';
import MultiSelectorDocs from '$lib/components/multi-selector/MultiSelector.doc.mjs';
import NumberInputDocs from '$lib/components/number-input/NumberInput.doc.mjs';
import RadioListDocs from '$lib/components/radio-list/RadioList.doc.mjs';
import SelectorDocs from '$lib/components/selector/Selector.doc.mjs';
import SliderDocs from '$lib/components/slider/Slider.doc.mjs';
import SwitchDocs from '$lib/components/switch/Switch.doc.mjs';
import TextAreaDocs from '$lib/components/text-area/TextArea.doc.mjs';
import TextInputDocs from '$lib/components/text-input/TextInput.doc.mjs';
import TimeInputDocs from '$lib/components/time-input/TimeInput.doc.mjs';
import TokenizerDocs from '$lib/components/tokenizer/Tokenizer.doc.mjs';
import TypeaheadDocs from '$lib/components/typeahead/Typeahead.doc.mjs';

/**
 * Astryx's `src/__tests__/inputWidthContract.test.tsx`, ported case for case —
 * **1 upstream `it` declaration at v0.4.5, 1 here**, under upstream's title and
 * with upstream's assertions. Nothing dropped, nothing added. The declaration
 * sits inside a `forEach` over the seventeen input-family components, so the
 * case count that *ran* was 17 on both sides, and it tracks the list.
 *
 * ## The upstream suite no longer exists — the count above is frozen at v0.4.5
 *
 * **Upstream deleted this file at 0.5.0**, in `63f398dfa` — *"test(core): drop
 * the tautological #4163 doc-contract tests (#5382)"* — along with
 * `apiContractDrift`, `fieldContract`, `structuralComponentContract` and lab's
 * `labApiContractDrift`. There is therefore **nothing at the 0.5.0 pin for this
 * file's count to be a contract against**, and the v0.4.5 numbers above are
 * kept only as the record of what it was ported from. This is the one suite
 * header in `src/tests/` that deliberately does not name the current pin,
 * because naming it would assert a file that is not there.
 *
 * The file is kept rather than deleted alongside upstream's, because the reason
 * for the deletion does not transfer: upstream's `.doc.mjs` are hand-authored,
 * so asserting that a hand-written `type` string says `SizeValue` really is
 * tautological — the assertion and the thing asserted are the same edit. This
 * port's are **generated** from the built `dist/**` declarations (see the note
 * on `type` below), so the same assertion reads the *components'* declared prop
 * types and can fail on a real drift upstream's never could. Whether to follow
 * upstream and drop it anyway is a decision for `port/debts.md`, not for this
 * documentation pass.
 *
 * The contract is a **documentation** one, not a rendering one, which is why
 * this file renders nothing and lives in the **server** project as upstream's
 * does: every member of the input family must document a `width` prop, and
 * document it as `SizeValue` rather than as an ad-hoc `number | string`. It is
 * the guard on Astryx issue #4163 — a family whose members disagreed about
 * whether they could be sized at all.
 *
 * All seventeen upstream components exist in this port, so the list is
 * upstream's list unchanged.
 *
 * ## Translations, none of them a dropped case
 *
 * **Where the docs come from, and the shape of the module.** Upstream's
 * `.doc.mjs` sit at `src/<Name>/<Name>.doc.mjs` and export `{docs}`; this port's
 * sit beside the kebab-case component directory and export a **default**, so the
 * imports are renamed accordingly. Upstream's structural narrowing is kept
 * verbatim, including the `components?.[0]?.props` branch — this port's
 * generator emits one file per component and so never takes it, but it is what
 * makes the assertion survive a future multi-component doc.
 *
 * **What `type` means here.** Upstream's doc files are hand-authored, so the
 * string is a claim a human made. This port's are generated by
 * `docs/scripts/emit-core-docs.mjs`, which reads every `type` out of this
 * package's own compiled `dist/**` declarations — so the assertion is checking
 * the *components'* declared prop types, one step closer to the source than
 * upstream can get.
 */

interface DocProp {
	name: string;
	type: string;
}

const inputDocsSuite: { name: string; docs: unknown }[] = [
	{ name: 'CheckboxInput', docs: CheckboxInputDocs },
	{ name: 'CheckboxList', docs: CheckboxListDocs },
	{ name: 'DateInput', docs: DateInputDocs },
	{ name: 'DateRangeInput', docs: DateRangeInputDocs },
	{ name: 'DateTimeInput', docs: DateTimeInputDocs },
	{ name: 'FileInput', docs: FileInputDocs },
	{ name: 'MultiSelector', docs: MultiSelectorDocs },
	{ name: 'NumberInput', docs: NumberInputDocs },
	{ name: 'RadioList', docs: RadioListDocs },
	{ name: 'Selector', docs: SelectorDocs },
	{ name: 'Slider', docs: SliderDocs },
	{ name: 'Switch', docs: SwitchDocs },
	{ name: 'TextArea', docs: TextAreaDocs },
	{ name: 'TextInput', docs: TextInputDocs },
	{ name: 'TimeInput', docs: TimeInputDocs },
	{ name: 'Tokenizer', docs: TokenizerDocs },
	{ name: 'Typeahead', docs: TypeaheadDocs }
];

describe('Input Family width Prop Contract (#4163)', () => {
	inputDocsSuite.forEach(({ name, docs }) => {
		it(`documents the width prop for ${name}`, () => {
			// `docs` is the ComponentDoc union (single vs multi component); narrow it
			// for structural access to either the top-level props or the first
			// sub-component's props.
			const doc = docs as {
				props?: DocProp[];
				components?: { props?: DocProp[] }[];
			};
			const propsList = (doc.props || doc.components?.[0]?.props) as DocProp[];
			expect(propsList, `${name}.doc.mjs must expose a props array`).toBeDefined();
			const widthProp = propsList.find((p) => p.name === 'width');
			expect(widthProp, `${name}.doc.mjs must document the width prop`).toBeDefined();
			expect(widthProp?.type).toBe('SizeValue');
		});
	});
});
