// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Switch',
	displayName: 'Switch',
	keywords: ['switch', 'toggle', 'onoff', 'flipswitch', 'boolean', 'toggleswitch'],
	category: 'Form Controls',
	theming: {
		targets: [
			{
				className: 'astryx-switch',
				visualProps: ['size'],
				states: ['checked', 'disabled']
			},
			{
				className: 'astryx-switch-thumb',
				visualProps: ['size'],
				states: ['checked']
			},
			{
				className: 'astryx-switch-field',
				visualProps: ['labelPosition', 'labelSpacing']
			},
			{
				className: 'astryx-switch-label'
			}
		]
	},
	usage: {
		description:
			'A toggle control for on/off states that take effect immediately. Supports labels, descriptions, loading states, and validation. Use it for settings or preferences that apply instantly. For changes requiring a form submission, use a checkbox instead.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use for settings that apply immediately; the toggle should take effect without a separate save action.'
			},
			{
				guidance: true,
				description: 'Pair with a clear, concise label that describes the setting being controlled.'
			},
			{
				guidance: false,
				description:
					'Use for options that require a form submission to take effect; use a checkbox instead.'
			},
			{
				guidance: false,
				description: "Use a switch for multi-state values; it's strictly on/off."
			},
			{
				guidance: false,
				description:
					'Wrap a disabled switch in Tooltip to explain why it is disabled; disabled controls swallow the hover events the wrapper needs. Use the disabledMessage prop instead.'
			}
		]
	},
	props: [
		{
			name: 'ref',
			type: 'HTMLInputElement | null',
			description: 'Ref forwarded to the underlying <input> element.'
		},
		{
			name: 'label',
			type: 'string',
			description: 'Label text for the switch (always rendered for accessibility).',
			required: true
		},
		{
			name: 'value',
			type: 'boolean',
			description: 'Whether the switch is on or off.',
			required: true
		},
		{
			name: 'onChange',
			type: '(checked: boolean, e: Event) => void',
			description: 'Callback fired when the switch state changes.'
		},
		{
			name: 'changeAction',
			type: '(checked: boolean, e: Event) => void | Promise<void>',
			description:
				'Async action fired after onChange. Triggers optimistic UI and shows a loading spinner until the promise resolves.'
		},
		{
			name: 'isLoading',
			type: 'boolean',
			description: 'Whether the switch is in a loading state, showing a spinner inside the thumb.',
			default: 'false'
		},
		{
			name: 'isLabelHidden',
			type: 'boolean',
			description: 'Visually hides the label while keeping it accessible to screen readers.',
			default: 'false'
		},
		{
			name: 'description',
			type: 'string',
			description: 'Description text displayed below the label.'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether the switch is disabled.',
			default: 'false'
		},
		{
			name: 'size',
			type: "'sm' | 'md'",
			description:
				'Size variant controlling track and thumb dimensions. sm (32x20px) matches sm checkbox/radio vertical rhythm; md (40x24px, default) matches md checkbox/radio vertical rhythm.',
			default: "'md'"
		},
		{
			name: 'htmlName',
			type: 'string',
			description:
				'The HTML name attribute for the underlying checkbox input, useful for form submissions (submits "on" when the switch is on).'
		},
		{
			name: 'disabledMessage',
			type: 'string',
			description:
				'Explains why the switch is disabled. With isDisabled, shows a tooltip on hover/keyboard focus and keeps the switch focusable via aria-disabled (toggling stays blocked). Use this instead of wrapping a disabled Switch in Tooltip. Disabled controls swallow the hover events an external Tooltip needs.'
		},
		{
			name: 'isOptional',
			type: 'boolean',
			description: 'Whether the field is optional. Mutually exclusive with isRequired.',
			default: 'false'
		},
		{
			name: 'isRequired',
			type: 'boolean',
			description: 'Whether the switch is required. Mutually exclusive with isOptional.',
			default: 'false'
		},
		{
			name: 'status',
			type: 'InputStatus',
			description:
				'Status indicator with type and message. Displays a colored message box below the switch and sets aria-invalid when type is "error".'
		},
		{
			name: 'onfocus',
			type: 'FocusEventHandler<HTMLInputElement>',
			description: 'Callback fired when the switch receives focus.'
		},
		{
			name: 'onblur',
			type: 'FocusEventHandler<HTMLInputElement>',
			description: 'Callback fired when the switch loses focus.'
		},
		{
			name: 'labelIcon',
			type: 'Snippet',
			description:
				'Icon displayed before the label text. See `astryx docs icons` for valid semantic names.'
		},
		{
			name: 'labelTooltip',
			type: 'string',
			description: 'Tooltip text shown in an info icon at the end of the label.'
		},
		{
			name: 'labelPosition',
			type: "'end' | 'start'",
			description:
				'Which side of the switch the label appears on. "start" places the label before the switch.',
			default: "'end'"
		},
		{
			name: 'labelSpacing',
			type: "'hug' | 'spread'",
			description:
				'Spacing behavior between label and switch. "hug" places them next to each other; "spread" pushes them to opposite ends of the container (full width).',
			default: "'hug'"
		},
		{
			name: 'width',
			type: 'SizeValue',
			description:
				'Width of the field (number = pixels, string used as-is, e.g. "100%"). Sizes the whole field (label, control, and status) so they stay aligned.'
		}
	]
};
