// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useClickableContainer',
	displayName: 'useClickableContainer',
	keywords: [
		'click',
		'container',
		'card',
		'pressable',
		'interactive',
		'nested',
		'link',
		'button',
		'delegate'
	],
	params: [
		{
			name: 'options',
			type: '() => UseClickableContainerOptions',
			description: 'Configuration object for the clickable container.',
			required: true
		},
		{
			name: 'options.container',
			type: 'HTMLElement | null',
			description: 'Ref to the outer container element.',
			required: true
		},
		{
			name: 'options.interactive',
			type: 'HTMLElement | null',
			description:
				'Ref to the primary interactive element inside (link, button). If no onClick or href is provided, clicks are proxied to this element.'
		},
		{
			name: 'options.onclick',
			type: '(event: MouseEvent) => void',
			description:
				'Click handler fired when the container surface (not a nested interactive element) is clicked.'
		},
		{
			name: 'options.href',
			type: 'string',
			description: 'Navigation URL. When provided, clicking the container navigates to this URL.'
		},
		{
			name: 'options.target',
			type: 'string',
			description: "Link target (e.g., '_blank'). Used with href for navigation behavior."
		},
		{
			name: 'options.disabled',
			type: 'boolean',
			description: 'Whether the container is disabled.',
			default: 'false'
		}
	],
	returns: [
		{
			name: 'onclick',
			type: '(event: MouseEvent) => void',
			description: 'Click handler to attach to the container element.'
		},
		{
			name: 'onmouseup',
			type: '(event: MouseEvent) => void',
			description:
				'Mouse up handler to attach to the container (handles middle-click navigation for href).'
		}
	],
	usage: {
		description:
			'Makes a container element clickable while preserving nested interactive element behavior. Solves the "nested interactive elements" problem: when a card is clickable but contains buttons/links, clicking those should NOT trigger the card\'s action. Detects interactive ancestors between the click target and the container, and ignores text selections. Supports href navigation (including middle-click and Ctrl/Cmd+click for new tabs).',
		bestPractices: [
			{
				guidance: true,
				description:
					'Attach both onClick and onMouseUp to the container element for full click handling including middle-click.'
			},
			{
				guidance: true,
				description:
					'Use inside ClickableCard or SelectableCard for the standard card interaction pattern.'
			},
			{
				guidance: false,
				description:
					'Use when the entire container is a single interactive element; just use a <button> or <a> directly.'
			}
		]
	},
	relatedComponents: ['ClickableCard', 'SelectableCard'],
	relatedHooks: ['useInputContainer'],
	importPath: '@astryx-svelte/core/hooks',
	category: 'interaction'
};
