// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useDevWarning',
	displayName: 'useDevWarning',
	keywords: [
		'warning',
		'dev',
		'development',
		'console',
		'guardrail',
		'misuse',
		'invariant',
		'debug',
		'devWarn'
	],
	params: [
		{
			name: 'component',
			type: 'string',
			description: 'Component or hook name, used as the message prefix.',
			required: true
		},
		{
			name: 'message',
			type: 'string | (() => string)',
			description: 'What went wrong and how to fix it.',
			required: true
		},
		{
			name: 'condition',
			type: '() => boolean',
			description: 'Whether to warn.',
			default: 'true'
		}
	],
	returns: [],
	usage: {
		description:
			'Fires a dev-only "Component: message" console warning once per mount while the condition holds. It is the render-safe way for a component to flag misuse: warning straight from the render body repeats on every render, and gating it with state adds a re-render, so this uses a ref and an effect instead. For a warning outside a component, use the imperative devWarn utility.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Say what is wrong and what the builder should do instead; the message is the whole value of the warning.'
			},
			{
				guidance: true,
				description:
					'Warn about combinations the types cannot express, such as two mutually exclusive props being set together.'
			},
			{
				guidance: false,
				description:
					'Use it for anything a user could see or for runtime error handling; it is stripped from production builds.'
			}
		]
	},
	importPath: '@astryx-svelte/core/hooks',
	category: 'utility'
};
