// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useGridFocus',
	displayName: 'useGridFocus',
	keywords: [
		'grid',
		'focus',
		'keyboard',
		'navigation',
		'arrow',
		'calendar',
		'a11y',
		'wai-aria',
		'cells'
	],
	params: [
		{
			name: 'options',
			type: '() => UseGridFocusOptions',
			description: 'Configuration object for grid focus behavior.',
			required: true
		},
		{
			name: 'options.columns',
			type: 'number',
			description:
				'Number of columns in the grid. Used for up/down navigation (moves by this many cells).',
			required: true
		},
		{
			name: 'options.cellSelector',
			type: 'string',
			description:
				'Selector for cells within the grid. Should match ALL cell positions in DOM order (including disabled/empty) so grid geometry is preserved.',
			default: '\'button:not([disabled]), [tabindex]:not([tabindex="-1"])\''
		},
		{
			name: 'options.isCellFocusable',
			type: '(cell: HTMLElement) => boolean',
			description:
				'Predicate for whether a matched cell can receive focus. Omit to treat every matched cell as focusable.'
		},
		{
			name: 'options.getFocusTarget',
			type: '(cell: HTMLElement) => HTMLElement | null',
			description:
				'Resolves the element to focus for a cell, e.g. a button inside a role="gridcell" wrapper. Omit to focus the cell itself.'
		},
		{
			name: 'options.onNavigateBefore',
			type: '(column: number, offset: number) => void',
			description:
				'Callback when navigation would go before the first cell. Receives the column index and offset (1 for horizontal, columns for vertical).'
		},
		{
			name: 'options.onNavigateAfter',
			type: '(column: number, offset: number) => void',
			description:
				'Callback when navigation would go after the last cell. Receives the column index and offset.'
		},
		{
			name: 'options.onPageUp',
			type: '() => void',
			description: 'Callback for Page Up key (e.g., navigate to previous month in calendars).'
		},
		{
			name: 'options.onPageDown',
			type: '() => void',
			description: 'Callback for Page Down key (e.g., navigate to next month in calendars).'
		},
		{
			name: 'options.isRtl',
			type: 'boolean',
			description:
				'Swap ArrowLeft/ArrowRight so horizontal navigation follows visual direction in right-to-left contexts. When omitted, auto-detected from the container computed direction on keydown.',
			default: "undefined (auto-detect from the container's computed direction)"
		},
		{
			name: 'options.hasRovingTabIndex',
			type: 'boolean',
			description:
				'Own a single roving tab stop across the grid: one focusable cell (its resolved focus target) carries tabindex="0", the rest -1. Stamped/repaired on render and moved with arrow navigation. Attach the returned handleFocus to the container onFocus.',
			default: 'false'
		}
	],
	returns: [
		{
			name: 'gridRef',
			type: 'HTMLElement | null',
			description: 'Ref to attach to the grid container element.'
		},
		{
			name: 'handleKeyDown',
			type: '(event: KeyboardEvent) => void',
			description: 'Key down handler to attach to the grid container.'
		},
		{
			name: 'handleFocus',
			type: '(event: FocusEvent) => void',
			description:
				'Focus handler for the grid container. Keeps the roving tab stop in sync when hasRovingTabIndex is enabled; a no-op otherwise, so always safe to attach.'
		},
		{
			name: 'focusCell',
			type: '(index: number) => void',
			description: 'Focus a specific cell by index (clamped to valid range).'
		},
		{
			name: 'focusFirst',
			type: '() => void',
			description: 'Focus the first focusable cell in the grid.'
		},
		{
			name: 'focusLast',
			type: '() => void',
			description: 'Focus the last focusable cell in the grid.'
		}
	],
	usage: {
		description:
			'Manages keyboard navigation within a 2D grid following the WAI-ARIA grid pattern. Supports arrow keys for cell-to-cell navigation, Home/End for row boundaries, Ctrl+Home/Ctrl+End for grid boundaries, and Page Up/Down for custom callbacks (e.g., month navigation in calendars). Boundary navigation callbacks allow cross-grid navigation.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use for calendar date grids: wire onPageUp/onPageDown to month navigation and onNavigateBefore/onNavigateAfter for cross-month arrow key navigation.'
			},
			{
				guidance: true,
				description: 'Attach both gridRef and handleKeyDown to the grid container element.'
			},
			{
				guidance: true,
				description:
					'For roving-tabindex grids (e.g. Calendar), set hasRovingTabIndex: true and attach handleFocus to the container onFocus; seed one focus target with tabindex=0 and the hook repairs and moves it.'
			},
			{
				guidance: false,
				description: 'Use for simple linear lists; prefer useListFocus for 1D navigation.'
			}
		]
	},
	relatedComponents: ['Calendar'],
	relatedHooks: ['useListFocus', 'useFocusTrap'],
	importPath: '@astryx-svelte/core/hooks',
	category: 'focus'
};
