// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useKeyboardHint',
	displayName: 'useKeyboardHint',
	keywords: [
		'keyboard',
		'hint',
		'arrow',
		'navigation',
		'roving',
		'tabindex',
		'focus',
		'discoverability',
		'toolbar',
		'tabs',
		'segmented',
		'affordance',
		'a11y'
	],
	params: [
		{
			name: 'options',
			type: '() => UseKeyboardHintOptions',
			description: 'Configuration object for the keyboard hint.'
		},
		{
			name: 'options.orientation',
			type: "'horizontal' | 'vertical' | 'both'",
			description:
				'Which arrow-key axis the composite navigates, controlling which arrow icons the hint shows (← → for horizontal, ↑ ↓ for vertical, all four for both).',
			default: "'horizontal'"
		},
		{
			name: 'options.dismissAfterMs',
			type: 'number',
			description: 'Milliseconds before the hint auto-dismisses after appearing.',
			default: '3000'
		},
		{
			name: 'options.isEnabled',
			type: 'boolean',
			description:
				'Whether the hint is enabled. Set to false to suppress it for a specific instance (e.g. a disabled or read-only widget).',
			default: 'true'
		}
	],
	returns: [
		{
			name: 'hintElement',
			type: 'string | Snippet',
			description:
				'The popover hint element to render inside the composite container (as the last child). Portals to the top layer via popover="manual", renders arrow keys with Kbd, and manages its own visibility; render it unconditionally.'
		},
		{
			name: 'onFocus',
			type: '(e: FocusEvent) => void',
			description:
				'Attach to the container onFocus. Shows the hint on the first keyboard-focus (:focus-visible) entry from outside the composite.'
		},
		{
			name: 'onBlur',
			type: '(e: FocusEvent) => void',
			description:
				'Attach to the container onBlur. Hides the hint when focus leaves the composite entirely, and re-anchors when focus moves within.'
		},
		{
			name: 'onKeyDown',
			type: '(e: KeyboardEvent) => void',
			description:
				'Attach to the container onKeyDown. Dismisses the hint on the first arrow press (the user has discovered the interaction). Never prevents default or stops propagation.'
		}
	],
	usage: {
		description:
			'Shows an ephemeral "← → to navigate" hint anchored to the focused item the first time a roving-tabindex composite (Toolbar, TabList, SegmentedControl, etc.) receives keyboard focus. It teaches sighted keyboard users that arrow keys move within the group. The hint renders arrow keys with Kbd in the top layer (popover="manual") and is CSS-anchor-positioned to the focused element, so overflow containers never clip it. It auto-dismisses on the first arrow press, on timeout, or on blur, and does not re-show for that instance. Toolbar, TabList, and SegmentedControl wire this in automatically; reach for the hook directly only when building a custom roving-tabindex widget.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Compose the returned onFocus/onKeyDown with your existing focus handlers rather than replacing them: call onKeyDown first (it only dismisses, never prevents), then your navigation handler.'
			},
			{
				guidance: true,
				description:
					'Render hintElement as the last child of the composite container; it is position:fixed in the top layer and aria-hidden, so it never affects layout or the accessibility tree.'
			},
			{
				guidance: true,
				description:
					'Match orientation to the arrow keys your widget actually responds to so the hint shows the correct icons.'
			},
			{
				guidance: false,
				description:
					'Use for single controls or widgets without roving-tabindex navigation; the hint only makes sense where arrows move focus within a group.'
			}
		]
	},
	relatedComponents: ['Toolbar', 'TabList', 'SegmentedControl'],
	relatedHooks: ['useListFocus', 'useGridFocus', 'useTreeFocus'],
	importPath: '@astryx-svelte/core/hooks',
	category: 'focus'
};
