// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useListFocus',
	displayName: 'useListFocus',
	keywords: [
		'list',
		'focus',
		'keyboard',
		'navigation',
		'menu',
		'toolbar',
		'roving',
		'tabindex',
		'a11y',
		'arrow',
		'wai-aria'
	],
	params: [
		{
			name: 'options',
			type: '() => UseListFocusOptions',
			description: 'Configuration object for list focus behavior. All fields are optional.'
		},
		{
			name: 'options.itemSelector',
			type: 'string',
			description: 'Selector for focusable items within the list.',
			default: '\'[role="menuitem"]\''
		},
		{
			name: 'options.boundarySelector',
			type: 'string',
			description:
				"Selector identifying a list boundary, for lists that contain nested lists of the same kind (e.g. a menu with submenu flyouts). When set, item collection and key handling are scoped to this level's own container. Typically '[role=\"menu\"]'."
		},
		{
			name: 'options.wrap',
			type: 'boolean',
			description: 'Whether arrow navigation wraps around at the ends.',
			default: 'true'
		},
		{
			name: 'options.onEscape',
			type: '() => void',
			description: 'Callback when Escape key is pressed (e.g., close menu).'
		},
		{
			name: 'options.orientation',
			type: "'horizontal' | 'vertical' | 'both'",
			description:
				"Navigation orientation. 'horizontal' uses ArrowLeft/ArrowRight, 'vertical' uses ArrowUp/ArrowDown, 'both' accepts all four arrows.",
			default: "'vertical'"
		},
		{
			name: 'options.hasHomeEnd',
			type: 'boolean',
			description: 'Whether Home/End jump to the first/last enabled item.',
			default: 'true'
		},
		{
			name: 'options.isRtl',
			type: 'boolean',
			description:
				'Whether the list is in a right-to-left context. When true, ArrowLeft/ArrowRight are swapped for horizontal navigation so it follows visual direction. When omitted, auto-detected from the container computed direction on keydown.',
			default: "undefined (auto-detect from the container's computed direction)"
		},
		{
			name: 'options.hasRovingTabIndex',
			type: 'boolean',
			description:
				'Opt into roving-tabindex ownership: the hook stamps a single tab stop (one item tabindex="0", the rest -1), repairs it as items mount/unmount or toggle disabled, and moves it with arrow navigation. When false, the hook only moves focus and never touches tabindex.',
			default: 'false'
		},
		{
			name: 'options.hasCaretGuard',
			type: 'boolean',
			description:
				'When true, arrow keys are not stolen from a nested text input/textarea whose caret is not at the boundary in the direction of travel (or that has a selection), and are never stolen from a nested contenteditable (rich-text editor / chat composer). Preserves inline text editing within the list.',
			default: 'false'
		}
	],
	returns: [
		{
			name: 'listRef',
			type: 'HTMLElement | null',
			description: 'Ref to attach to the list container element.'
		},
		{
			name: 'handleKeyDown',
			type: '(event: KeyboardEvent) => void',
			description: 'Key down handler to attach to the list container.'
		},
		{
			name: 'handleFocus',
			type: '(event: FocusEvent) => void',
			description:
				'Focus handler for the container. Keeps the roving tab stop in sync when hasRovingTabIndex is enabled; a no-op otherwise, so it is always safe to attach.'
		},
		{
			name: 'focusItem',
			type: '(index: number) => void',
			description: 'Focus a specific item by index (clamped to valid range).'
		},
		{
			name: 'focusFirst',
			type: '() => boolean',
			description: 'Focus the first enabled item. Returns true when an item was focused.'
		},
		{
			name: 'focusLast',
			type: '() => boolean',
			description: 'Focus the last enabled item. Returns true when an item was focused.'
		},
		{
			name: 'ownsEvent',
			type: '(event: KeyboardEvent) => boolean',
			description:
				'Whether a key event belongs to this list level rather than a nested list sharing the same boundarySelector. Always true when no boundarySelector is set. Use to guard consumer-added key handling (Enter/Space, typeahead).'
		},
		{
			name: 'getItems',
			type: '() => HTMLElement[]',
			description:
				"This level's focusable items in DOM order (already scoped by boundarySelector). Build typeahead targets from this instead of re-querying."
		}
	],
	usage: {
		description:
			'Manages keyboard navigation within a linear list following WAI-ARIA menu/listbox/toolbar patterns. Supports arrow key navigation (vertical, horizontal, or both), Home/End for boundaries, optional wrap-around, RTL, and Escape to close. Opt into hasRovingTabIndex for composite widgets (toolbars, segmented controls, tab strips) that own a single tab stop. Suitable for dropdown menus, toolbars, and any 1D focusable list.',
		bestPractices: [
			{
				guidance: true,
				description:
					"Set orientation to 'horizontal' for toolbars and tab bars, 'vertical' for dropdown menus."
			},
			{
				guidance: true,
				description:
					'Provide an onEscape callback for menus/dropdowns to return focus to the trigger.'
			},
			{
				guidance: true,
				description:
					'Enable hasRovingTabIndex (and hasCaretGuard when the widget can contain text inputs) for toolbar-style composites that should be a single tab stop.'
			},
			{
				guidance: false,
				description: 'Use for 2D grid navigation; prefer useGridFocus for grids and calendars.'
			}
		]
	},
	relatedComponents: ['TabMenu', 'Toolbar'],
	relatedHooks: ['useGridFocus', 'useFocusTrap'],
	importPath: '@astryx-svelte/core/hooks',
	category: 'focus'
};
