// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useScrollLock',
	displayName: 'useScrollLock',
	keywords: [
		'scroll',
		'lock',
		'modal',
		'dialog',
		'body',
		'prevent',
		'background',
		'ios',
		'safari',
		'fixed'
	],
	params: [
		{
			name: 'isLocked',
			type: '() => boolean',
			description: 'whether body scroll should be locked.',
			required: true
		}
	],
	returns: [],
	usage: {
		description:
			'Locks body scroll when active by pinning the body with position: fixed. This prevents background scrolling behind modals and dialogs, which is necessary for iOS Safari where overscroll-behavior: contain does not work. Restores the original scroll position when unlocked.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use when opening full-screen modals or dialogs to prevent background content from scrolling.'
			},
			{
				guidance: true,
				description:
					'Pass the same boolean that controls dialog visibility (e.g., isOpen) as the isLocked parameter.'
			},
			{
				guidance: false,
				description:
					'Use for non-modal overlays like popovers or tooltips; users should be able to scroll away from those.'
			}
		]
	},
	relatedComponents: ['Dialog'],
	relatedHooks: ['useFocusTrap'],
	importPath: '@astryx-svelte/core/hooks',
	category: 'layout'
};
