// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useTreeFocus',
	displayName: 'useTreeFocus',
	keywords: [
		'tree',
		'treeview',
		'focus',
		'keyboard',
		'navigation',
		'arrow',
		'expand',
		'collapse',
		'roving',
		'tabindex',
		'a11y',
		'wai-aria',
		'apg'
	],
	params: [
		{
			name: 'options',
			type: '() => UseTreeFocusOptions',
			description: 'Configuration object for tree focus behavior.'
		},
		{
			name: 'options.itemSelector',
			type: 'string',
			description: 'Selector for visible treeitems within the tree, in DOM order.',
			default: '\'[role="treeitem"]\''
		},
		{
			name: 'options.isItemDisabled',
			type: '(item: HTMLElement) => boolean',
			description:
				'Predicate for whether a treeitem is disabled and must be skipped during navigation. Defaults to reading `data-tree-disabled` / `aria-disabled`.'
		},
		{
			name: 'options.getLevel',
			type: '(item: HTMLElement) => number',
			description:
				'Reads the 1-based nesting level of a treeitem. Defaults to the `aria-level` attribute.'
		},
		{
			name: 'options.onToggleExpand',
			type: '(id: string) => void',
			description:
				'Called to expand/collapse the treeitem with the given id (ArrowRight on a collapsed parent, ArrowLeft on an expanded parent, Enter/Space on a parent without its own action).'
		},
		{
			name: 'options.onActivate',
			type: '(item: HTMLElement, id: string) => boolean',
			description:
				'Called when Enter/Space activates a treeitem. Return true when handled; return false/undefined to let the hook fall back to toggling expansion.'
		},
		{
			name: 'options.onActiveChange',
			type: '(id: string) => void',
			description:
				'Notified when the hook moves focus to a treeitem. Consumers use this to move a single roving tab stop.'
		},
		{
			name: 'options.hasRovingTabIndex',
			type: 'boolean',
			description:
				'When true, the hook owns a single roving tab stop across the visible treeitems (stamps tabindex 0/-1, repairs on mount, moves with navigation). Preserves an existing tabindex="0" seed on mount. Attach the returned `handleFocus` to keep the stop in sync after clicks.',
			default: 'false'
		},
		{
			name: 'options.typeahead',
			type: 'boolean',
			description:
				'Whether typeahead (jump to next item whose text starts with the typed characters) is enabled.',
			default: 'true'
		}
	],
	returns: [
		{
			name: 'treeRef',
			type: 'HTMLElement | null',
			description: 'Ref to attach to the tree container element (role="tree").'
		},
		{
			name: 'handleKeyDown',
			type: '(event: KeyboardEvent) => void',
			description: 'Key down handler to attach to the tree container.'
		},
		{
			name: 'handleFocus',
			type: '(event: FocusEvent) => void',
			description:
				"Focus handler to attach to the container's onFocus. Keeps the roving tab stop in sync when hasRovingTabIndex is enabled; a no-op otherwise, so always safe to attach."
		},
		{
			name: 'focusFirst',
			type: '() => void',
			description: 'Focus the first enabled visible treeitem.'
		},
		{
			name: 'focusLast',
			type: '() => void',
			description: 'Focus the last enabled visible treeitem.'
		}
	],
	usage: {
		description:
			'Manages roving-tabindex focus and the WAI-ARIA tree keyboard model. ArrowUp/ArrowDown/Home/End roam linearly over the visible treeitems (skipping disabled ones), while ArrowRight/ArrowLeft carry tree semantics (expand/collapse, move to first-child/parent). Enter/Space activate, and printable characters trigger typeahead.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use for hierarchical tree widgets: wire onToggleExpand to your expansion state and onActiveChange to a single roving tab stop.'
			},
			{
				guidance: true,
				description: 'Attach both treeRef and handleKeyDown to the role="tree" container element.'
			},
			{
				guidance: false,
				description:
					'Use for linear lists (prefer useListFocus) or 2D grids (prefer useGridFocus); those traversals differ from a tree.'
			}
		]
	},
	relatedComponents: ['TreeList'],
	relatedHooks: ['useListFocus', 'useGridFocus', 'useFocusTrap'],
	importPath: '@astryx-svelte/core/hooks',
	category: 'focus'
};
