// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'CheckIndicator',
	displayName: 'Check Indicator',
	subComponentOf: 'Indicator',
	description:
		'The mark on a chosen option: a checkmark by default, and nothing at all when unchosen, so a listbox shows no empty box beside every row. This is the indicator to replace to change what "chosen" looks like: mapping it to RadioIndicator gives every single-selection mark radio visuals, including an empty circle on unchosen rows. Unlike the checkbox and radio visuals it renders no chrome of its own (it IS the glyph), so a host\'s theme target lands on the same element as astryx-icon.',
	keywords: [
		'indicator',
		'checkbox',
		'radio',
		'control',
		'selection',
		'mark',
		'tick',
		'themeable',
		'swap'
	],
	group: 'Indicator',
	category: 'Data Input',
	props: [
		{
			name: 'state',
			type: "'unchecked' | 'checked'",
			description:
				'Which state to draw. The default renders nothing when unchecked; a replacement may draw in both states.',
			required: true
		},
		{
			name: 'size',
			type: "'sm' | 'md'",
			description: 'Control size, matching the other indicators.',
			default: "'md'"
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description:
				'Whether the owning row is disabled. Purely visual; the owner keeps the real disabled semantics.',
			default: 'false'
		},
		{
			name: 'children',
			type: 'Snippet',
			description:
				'Rendered INSTEAD of the mark, in every state: a host showing a pending Spinner passes it through whether or not the row is chosen.'
		}
	]
};
