// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'CheckboxIndicator',
	displayName: 'Checkbox Indicator',
	subComponentOf: 'Indicator',
	description:
		'The checkbox visual: a square box with a checkmark or an indeterminate bar. Decorative (aria-hidden); the owning control keeps the input, role, accessible name, focus, and keyboard behavior.',
	keywords: [
		'indicator',
		'checkbox',
		'radio',
		'control',
		'selection',
		'mark',
		'tick',
		'themeable',
		'swap'
	],
	group: 'Indicator',
	category: 'Form Controls',
	props: [
		{
			name: 'state',
			type: "'indeterminate' | 'unchecked' | 'checked'",
			description:
				'Which state to draw. An indicator draws in EVERY state: the unchecked box is an empty box, not nothing.',
			required: true
		},
		{
			name: 'size',
			type: "'sm' | 'md'",
			description: 'Control size: 20px or 24px.',
			default: "'md'"
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description:
				'Whether the owning control is disabled. Purely visual; the owner keeps the real disabled semantics.',
			default: 'false'
		},
		{
			name: 'children',
			type: 'Snippet',
			description:
				'Rendered inside the chrome INSTEAD of the state mark. CheckboxInput passes its loading Spinner through this while a change action is pending, so a replacement indicator must render children when they will actually draw something: use `isRenderable(children)`, never `children ?? mark`, because a host writes `children={isBusy && <Spinner/>}` and `false` slips straight past a nullish check and deletes the mark.'
		}
	]
};
