// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'LayerProvider',
	displayName: 'Layer Provider',
	subComponentOf: 'Layer',
	description:
		'App-level provider for layer systems such as toast viewports and imperative modals. Nested providers pass through.',
	keywords: [
		'layer',
		'overlay',
		'popover',
		'positioning',
		'anchor',
		'floating',
		'dropdown',
		'popper',
		'popup',
		'portal'
	],
	group: 'Utilities',
	category: 'Utility',
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Application subtree that can use the shared layer context.',
			required: true
		},
		{
			name: 'toast',
			type: 'LayerToastConfig',
			description:
				'Toast viewport configuration. Controls position, maxVisible, and inset for toasts shown through useToast.'
		}
	]
};
