// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Center',
	displayName: 'Center',
	keywords: [
		'center',
		'centered',
		'centering',
		'align',
		'alignment',
		'justify',
		'flexbox',
		'middle'
	],
	group: 'Layout',
	category: 'Layout',
	isHiddenFromOverview: true,
	theming: {
		targets: [
			{
				className: 'astryx-center',
				visualProps: ['axis']
			}
		]
	},
	usage: {
		description:
			'Center aligns content to the middle of its container. Use it for empty states, loading screens, login forms, or any content that should sit in the center of the available space.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use axis="horizontal" or axis="vertical" when you only need one direction. Both axes is the default but not always needed.'
			},
			{
				guidance: true,
				description:
					'Set a height when centering vertically. Center needs a defined height to know what space to center within.'
			},
			{
				guidance: true,
				description:
					'Use isInline to center small elements like icons or badges within a line of text without breaking the text flow.'
			},
			{
				guidance: false,
				description:
					'Wrap large page sections in Center. Use Layout or AppShell for page-level structure.'
			},
			{
				guidance: false,
				description:
					'Use Center for horizontal lists of items. Use Stack with hAlign="center" instead.'
			}
		],
		anatomy: [
			{
				name: 'Container',
				required: true,
				description:
					'A flexbox wrapper that aligns its children to the center along the chosen axis.'
			},
			{
				name: 'Content',
				required: true,
				description:
					'Any children passed to Center. Typically a card, form, spinner, or empty state message.'
			}
		]
	},
	props: [
		{
			name: 'axis',
			type: "'horizontal' | 'vertical' | 'both'",
			description: 'Which direction(s) to center.',
			default: "'both'"
		},
		{
			name: 'width',
			type: 'SizeValue',
			description: 'Container width (px or CSS value).'
		},
		{
			name: 'height',
			type: 'SizeValue',
			description: 'Container height (px or CSS value).'
		},
		{
			name: 'maxWidth',
			type: 'SizeValue',
			description: 'Maximum container width (px or CSS value).'
		},
		{
			name: 'minHeight',
			type: 'SizeValue',
			description: 'Minimum container height (px or CSS value).'
		},
		{
			name: 'padding',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Inner padding on all sides, using the spacing scale (0, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 8, 10). Matches the padding prop on Stack, Card, LayoutContent, and LayoutPanel. Pass as a JSX number expression e.g. padding={3}.'
		},
		{
			name: 'paddingInline',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Inline (horizontal) padding, using the spacing scale. Overrides padding on the inline axis when both are set.'
		},
		{
			name: 'paddingInlineStart',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Inline-start padding, using the spacing scale (left in LTR, right in RTL). Overrides paddingInline and padding on that edge only.'
		},
		{
			name: 'paddingInlineEnd',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Inline-end padding, using the spacing scale (right in LTR, left in RTL). Overrides paddingInline and padding on that edge only.'
		},
		{
			name: 'paddingBlock',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Block (vertical) padding, using the spacing scale. Overrides padding on the block axis when both are set.'
		},
		{
			name: 'paddingBlockStart',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Block-start (top) padding, using the spacing scale. Overrides paddingBlock and padding on that edge only.'
		},
		{
			name: 'paddingBlockEnd',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Block-end (bottom) padding, using the spacing scale. Overrides paddingBlock and padding on that edge only.'
		},
		{
			name: 'isInline',
			type: 'boolean',
			description: 'Use inline-flex (useful for text/icons).',
			default: 'false'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Content to center.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
