// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'TableCell',
	displayName: 'Table Cell',
	subComponentOf: 'Table',
	description:
		'<td> wrapper that reads TableContext to apply density padding, font size, and divider borders when used inside Table.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Cell content.'
		}
	]
};
