// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Citation',
	displayName: 'Citation',
	group: 'Citation',
	category: 'Content',
	theming: {
		targets: [
			{
				className: 'astryx-citation',
				visualProps: ['variant']
			}
		]
	},
	usage: {
		description:
			'Citations display inline references to external sources. Use them to attribute information within AI-generated responses, articles, or anywhere provenance and source links are needed.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use the label variant when the source title adds meaningful context for the reader.'
			},
			{
				guidance: true,
				description:
					'Use the number variant for compact inline references within body text, like footnotes.'
			},
			{
				guidance: false,
				description:
					'Mix label and number variants in the same paragraph. Pick one style per context for visual consistency.'
			}
		],
		anatomy: [
			{
				name: 'Container',
				required: true,
				description:
					'The interactive wrapper. Renders as an anchor when a URL is provided, or a span otherwise.'
			},
			{
				name: 'Icon',
				required: false,
				description:
					'An optional source icon shown before the label text. Accepts a favicon/logo image URL (via source.src) or a React node such as an Astryx <Icon>. Only available in the label variant.'
			},
			{
				name: 'Label text',
				required: false,
				description:
					'The source title, truncated with ellipsis when it exceeds the max width. Shown in the label variant.'
			},
			{
				name: 'Number',
				required: false,
				description:
					'The citation index displayed as a superscript badge. Shown in the number variant.'
			}
		]
	},
	playground: {
		defaults: {
			source: {
				title: 'Astryx Design',
				url: 'https://example.com'
			},
			number: 1
		}
	},
	props: [
		{
			name: 'source',
			type: 'CitationSource',
			description:
				'The citation source object containing title, url, an optional image src, and an optional icon node.',
			required: true
		},
		{
			name: 'number',
			type: 'number',
			description: 'The display index for this citation.',
			required: true
		},
		{
			name: 'variant',
			type: "'number' | 'label'",
			description:
				'Display style: a label chip showing the source title or a compact numbered badge.',
			default: "'label'"
		}
	]
};
