// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Text',
	displayName: 'Text',
	keywords: [
		'text',
		'typography',
		'label',
		'paragraph',
		'heading',
		'caption',
		'font',
		'body',
		'subtitle'
	],
	category: 'Content',
	theming: {
		targets: [
			{
				className: 'astryx-heading',
				visualProps: ['level', 'color']
			},
			{
				className: 'astryx-text',
				visualProps: ['type', 'size', 'color']
			}
		]
	},
	usage: {
		description:
			'Text renders styled body text and headings from the theme. Use Text with a semantic type for body copy, labels, and captions, and Heading for section titles that output the correct h1–h6 element.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Pick a semantic type (body, label, supporting, large, code) instead of manually setting size and weight; the theme handles the details.'
			},
			{
				guidance: true,
				description:
					'Set accessibilityLevel on Heading when the visual level differs from the document outline so screen readers announce the correct hierarchy.'
			},
			{
				guidance: true,
				description:
					'Use maxLines with a number to truncate long content; a tooltip appears automatically on hover so no text is lost.'
			},
			{
				guidance: true,
				description:
					'Enable hasTabularNumbers for columns of numeric data so digits align vertically across rows.'
			},
			{
				guidance: false,
				description:
					'Override size and weight when a semantic type already matches; extra overrides fight the theme and break when themes change.'
			},
			{
				guidance: false,
				description:
					'Skip heading levels in the document outline; go h1 then h2 then h3, never h1 then h3.'
			},
			{
				guidance: false,
				description:
					'Use raw HTML tags like <p>, <h1>–<h6>, or <span> for text; Text and Heading apply the correct theme tokens automatically.'
			},
			{
				guidance: false,
				description:
					'Pass a `variant` prop; Text does not have a `variant` prop. Use `type` for semantic styling (body, label, large, supporting, code) or use Heading for headings.'
			},
			{
				guidance: false,
				description:
					'Use Text for headings; use Heading with a `level` prop (1–6) for section titles and headings.'
			}
		]
	},
	playground: {
		defaults: {
			children: 'The quick brown fox jumps over the lazy dog.',
			type: 'body'
		}
	},
	props: [
		{
			name: 'type',
			type: 'TextType',
			description:
				"Semantic text type. Determines size, weight, and line-height from the theme. 'inherit' takes all three from the surrounding text instead. Themes may add custom types. Note: this prop is called `type`, not `variant`.",
			default: "'body'"
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Text content.',
			required: true
		},
		{
			name: 'size',
			type: "'base' | 'sm' | 'lg' | 'xl' | '4xs' | '3xs' | '2xs' | 'xsm' | '2xl' | '3xl' | '4xl'",
			description:
				'Explicit font size override. Overrides the size from `type` but preserves other type properties. Prefer using `type` alone.'
		},
		{
			name: 'color',
			type: "'placeholder' | 'inherit' | 'disabled' | 'primary' | 'secondary' | 'accent'",
			description:
				"Text color. Defaults to 'secondary' for the 'supporting' type, 'primary' for all others. Themes may add custom colors."
		},
		{
			name: 'weight',
			type: "'medium' | 'normal' | 'semibold' | 'bold'",
			description: 'Font weight override.'
		},
		{
			name: 'display',
			type: "'inline' | 'block'",
			description:
				"Display type. Silently overridden to 'block' when maxLines > 0 or hasCapsize is true.",
			default: "'inline'"
		},
		{
			name: 'as',
			type: "'label' | 'div' | 'span' | 'h1' | 'h2' | 'h3' | 'p'",
			description: 'HTML element to render.',
			default: "'span'"
		},
		{
			name: 'maxLines',
			type: 'number',
			description:
				'Maximum lines before truncation. 0 means no truncation. When set, shows a tooltip on hover if content is truncated.',
			default: '0'
		},
		{
			name: 'hasTruncateTooltip',
			type: 'boolean | LayerPlacement',
			description:
				"Controls tooltip behavior for truncated text. true shows the tooltip at the default position, false disables it, or a placement string ('above' | 'below' | 'start' | 'end') sets a specific position.",
			default: 'true'
		},
		{
			name: 'wordBreak',
			type: "'break-word' | 'break-all'",
			description:
				"Word break behavior when truncating. Defaults to 'break-all' for single-line truncation, 'break-word' otherwise."
		},
		{
			name: 'textWrap',
			type: "'wrap' | 'nowrap' | 'balance' | 'pretty'",
			description: 'Text wrapping behavior.'
		},
		{
			name: 'justify',
			type: "'end' | 'start' | 'center'",
			description:
				'Text alignment (justification). Uses logical values (start/end) for i18n/RTL compatibility.',
			default: "'start'"
		},
		{
			name: 'hasCapsize',
			type: 'boolean',
			description: 'Enable optical alignment using text-box-trim. Forces block display.',
			default: 'false'
		},
		{
			name: 'hasStrikethrough',
			type: 'boolean',
			description: 'Apply strikethrough text decoration.',
			default: 'false'
		},
		{
			name: 'hasTabularNumbers',
			type: 'boolean',
			description: 'Use tabular (monospace) numbers for aligned numeric data.',
			default: 'false'
		},
		{
			name: 'id',
			type: 'string | null',
			description: 'HTML id attribute.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
