// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Avatar',
	displayName: 'Avatar',
	keywords: [
		'avatar',
		'profile',
		'user',
		'photo',
		'thumbnail',
		'initials',
		'gravatar',
		'pfp',
		'userpic'
	],
	group: 'Avatar',
	category: 'Content',
	theming: {
		targets: [
			{
				className: 'astryx-avatar',
				visualProps: ['size']
			},
			{
				className: 'astryx-avatar-status-dot',
				visualProps: ['variant']
			},
			{
				className: 'astryx-avatar-status-dot-glyph',
				visualProps: ['shape']
			}
		],
		vars: [
			{
				name: '--_avatar-fallback-font-size',
				description:
					'Initials font size; default is proportional to the avatar size (size × 0.4). Override per size tier (e.g. size:sm) for a custom type scale.',
				default: 'calc(avatar-size × 0.4)',
				private: true
			},
			{
				name: '--_avatar-fallback-font-weight',
				description: 'Initials font weight',
				default: 'var(--font-weight-medium)',
				private: true
			},
			{
				name: '--_avatar-fallback-color',
				description: 'Fallback text and default-icon color',
				default: 'var(--color-text-secondary)',
				private: true
			},
			{
				name: '--_avatar-fallback-background',
				description: 'Fallback wash background fill',
				default: 'var(--color-neutral)',
				private: true
			}
		],
		derived: [
			{
				property: 'fontSize',
				vars: ['--_avatar-fallback-font-size']
			},
			{
				property: 'fontWeight',
				vars: ['--_avatar-fallback-font-weight']
			},
			{
				property: 'color',
				vars: ['--_avatar-fallback-color']
			},
			{
				property: 'backgroundColor',
				vars: ['--_avatar-fallback-background']
			}
		]
	},
	usage: {
		description:
			'Avatar represents a person or team with a profile photo, initials, or a default icon. Use it in comment headers, contact lists, chat messages, user cards, and anywhere you need to identify someone visually.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Always pass a name so the avatar can show initials if the photo fails to load, and so screen readers can announce who it represents.'
			},
			{
				guidance: true,
				description:
					'Pick a size that matches the context: xsm or sm for inline mentions, md or lg for lists and cards, xl for profile headers.'
			},
			{
				guidance: true,
				description:
					"Add a status dot when knowing someone's availability matters, like in chat or team views."
			},
			{
				guidance: true,
				description:
					'When wrapping an Avatar in your own Tooltip or HoverCard, set tooltip={false} so the built-in name tooltip does not overlap yours.'
			},
			{
				guidance: false,
				description:
					"Use Avatar for logos, product images, or anything that isn't a person or team. Use an image or icon instead."
			},
			{
				guidance: false,
				description:
					'Force a square or custom shape. Avatars are always circular to stay consistent across the system.'
			}
		],
		anatomy: [
			{
				name: 'Photo',
				required: false,
				description: 'The profile image, loaded from the src URL. Shown when available.'
			},
			{
				name: 'Initials',
				required: false,
				description: 'One or two letters extracted from the name. Shown when no photo is available.'
			},
			{
				name: 'Default icon',
				required: false,
				description: 'A generic person silhouette. Shown when there is no photo or name.'
			},
			{
				name: 'Status dot',
				required: false,
				description:
					'A small indicator in the bottom-right corner showing availability (online, away, busy). Each variant pairs colour with a distinct shape so status does not rely on colour alone.'
			}
		]
	},
	props: [
		{
			name: 'src',
			type: 'string',
			description: 'Primary image source URL.'
		},
		{
			name: 'fallbackSrc',
			type: 'string',
			description: 'Fallback image when primary fails.'
		},
		{
			name: 'name',
			type: 'string',
			description: 'User name for initials and alt text.'
		},
		{
			name: 'alt',
			type: 'string',
			description: 'Alt text (falls back to name).'
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg' | 'xl' | 'xsm' | 16 | 20 | 24 | 32 | 36 | 40 | 48 | 60 | 64 | 72 | 96 | 128 | 144 | 180",
			description:
				"Avatar size. Use a named size ('xsm' 20px, 'sm' 24px, 'md' 36px, 'lg' 48px, 'xl' 128px) or a numeric pixel value. Avatar shares Icon's abbreviated scale, but its tiers are larger because avatars align with media rather than glyphs.",
			default: "'md'"
		},
		{
			name: 'status',
			type: 'Snippet',
			description:
				'Corner content for status indicators. A string `label` on the element (as on AvatarStatusDot) is composed into the avatar\'s accessible name (e.g. "Jane Doe, Online") so screen readers announce the status.'
		},
		{
			name: 'tooltip',
			type: 'string | boolean',
			description:
				"Tooltip shown on hover and keyboard focus. Omitted or true shows the avatar's name; a string shows that text instead; false shows no tooltip. Not auto-disabled when wrapped in your own Tooltip/HoverCard. Set tooltip={false} if you supply your own overlay. No tooltip is shown when tooltip is true/omitted and there is no name.",
			default: 'true'
		},
		{
			name: 'href',
			type: 'string',
			description:
				'When set, the avatar renders as an interactive link (`<a>` or a custom link component) pointing here. This follows the same element-swap rule as Button. Requires a meaningful accessible name via `alt` or `name`. Inside an AvatarGroup, interactive avatars share a single Tab stop and are reached with arrow keys.'
		},
		{
			name: 'as',
			type: 'LinkComponentType',
			description:
				'Custom link component used when `href` is set (e.g. Next.js `Link`). Overrides the provider-level LinkProvider default. Only applies with `href`.'
		},
		{
			name: 'target',
			type: 'string',
			description: 'Link target attribute. Only applies with `href`.'
		},
		{
			name: 'rel',
			type: 'string',
			description: 'Link rel attribute. Only applies with `href`.'
		},
		{
			name: 'onclick',
			type: '(event: MouseEvent) => void',
			description:
				'Click handler. When set without `href`, the avatar renders as a focusable `<button type="button">`. Requires a meaningful accessible name via `alt` or `name`.'
		}
	]
};
