// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Outline',
	displayName: 'Outline',
	keywords: [
		'outline',
		'table of contents',
		'toc',
		'heading navigation',
		'scroll spy',
		'documentation',
		'anchors',
		'sliding indicator'
	],
	group: 'Outline',
	category: 'Navigation',
	theming: {
		targets: [
			{
				className: 'astryx-outline',
				visualProps: ['density']
			},
			{
				className: 'astryx-outline-indicator'
			},
			{
				className: 'astryx-outline-item',
				visualProps: ['level'],
				states: ['active']
			}
		]
	},
	usage: {
		description:
			'A table-of-contents sidebar for documentation pages, help centers, wikis, and long settings pages. Use it for navigation within a single page, not for app routes. Features a sliding indicator track that animates to the active heading. The list is a single tab stop: arrow keys move between headings, Home/End jump to the ends, and Enter/Space activate.',
		bestPractices: [
			{
				guidance: true,
				description: 'Pass a flat ordered list of headings and let level control indentation.'
			},
			{
				guidance: true,
				description: 'Use activeId when custom scroll logic owns the active section.'
			},
			{
				guidance: true,
				description: 'Use density="compact" in dense sidebars where vertical space is tight.'
			},
			{
				guidance: true,
				description:
					'Use useOutlineFromMarkdown or useOutlineFromDOM when headings are generated from content.'
			},
			{
				guidance: true,
				description:
					'Pass scrollContainerRef when the content scrolls in a split pane, modal, or panel instead of the viewport.'
			},
			{
				guidance: true,
				description:
					'Set offset to the height of a fixed header that overlays the content, so headings land below it instead of underneath it.'
			},
			{
				guidance: false,
				description: 'Use Outline for application navigation - use SideNav or TopNav for routes.'
			},
			{
				guidance: false,
				description:
					'Use Outline for expandable hierarchy - use TreeList when nodes need expand and collapse.'
			},
			{
				guidance: false,
				description:
					'Rely on onNavigateEnd to mean "arrived" - it also fires when the user interrupts the scroll.'
			}
		]
	},
	playground: {
		defaults: {
			items: [
				{
					id: 'overview',
					label: 'Overview',
					level: 2
				},
				{
					id: 'installation',
					label: 'Installation',
					level: 2
				},
				{
					id: 'configuration',
					label: 'Configuration',
					level: 3
				},
				{
					id: 'api-reference',
					label: 'API reference',
					level: 2
				}
			]
		}
	},
	props: [
		{
			name: 'items',
			type: 'OutlineItem[]',
			description:
				'Ordered heading items. Each item has id, label, and level (1-6). The id should match the target heading element id.',
			required: true
		},
		{
			name: 'activeId',
			type: 'string',
			description:
				'Currently active heading id. Providing this prop makes active state controlled and disables built-in scroll-spy.'
		},
		{
			name: 'onActiveIdChange',
			type: '(id: string) => void',
			description:
				'Called when the active item changes from built-in scroll-spy or from an outline link click.'
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the nav landmark.',
			default: "'Table of contents'"
		},
		{
			name: 'density',
			type: "'compact' | 'default'",
			description:
				"Density variant controlling item padding. 'compact' for dense UIs, 'default' for standard spacing.",
			default: "'default'"
		},
		{
			name: 'onNavigateStart',
			type: '(id: string) => void',
			description:
				'Called with the item id when navigation begins, before the scroll starts. Pair with onNavigateEnd to drive an arrival effect (flash, ring, pulse) on the target heading.'
		},
		{
			name: 'onNavigateEnd',
			type: '(id: string) => void',
			description:
				'Called with the item id once the navigation resolves - when the smooth scroll settles, or when reduced motion turns it into an instant jump. Fires exactly once per onNavigateStart, including when the user interrupts the scroll, so a "navigating" state can never leak.'
		},
		{
			name: 'offset',
			type: 'number',
			description:
				"Height in px of a fixed header overlaying the top of the scroll root. Shifts both the activation line and the scroll landing by the same amount, so a heading activates exactly where navigating to it puts it - below the header, not underneath it. Composes with each heading's own scroll-margin-top (the header, then the breathing room below it); it does not replace it. Leave at 0 when nothing overlays the content and let scroll-margin-top do the work.",
			default: '0'
		},
		{
			name: 'scrollContainerRef',
			type: '() => HTMLElement | null',
			description:
				'Scroll container to track, instead of auto-detecting the nearest scrollable ancestor. Use it when content scrolls inside a split pane, modal, or dashboard panel rather than the viewport.'
		},
		{
			name: 'hasScrollOnClick',
			type: 'boolean',
			description:
				'Whether activating an item smooth-scrolls to it. Set to false to own the scrolling yourself (virtualized content, a router): the Outline still updates the active item, the hash, and the navigate callbacks, but performs no scroll.',
			default: 'true'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for layout customization. Must be a stylex.create() value.'
		}
	]
};
