// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Code',
	displayName: 'Code',
	subComponentOf: 'CodeBlock',
	description:
		'Inline code element. Renders a styled <code> with monospace font and muted background. For fenced blocks, use CodeBlock.',
	keywords: [
		'code',
		'syntax',
		'highlight',
		'snippet',
		'prism',
		'shiki',
		'pre',
		'monospace',
		'codeblock',
		'inline'
	],
	category: 'Content',
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Code content.',
			required: true
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for layout customization. Must be a stylex.create() value.'
		},
		{
			name: 'class',
			type: 'ClassValue | null',
			description: 'CSS class name for the root element. Prefer xstyle for styling.'
		},
		{
			name: 'style',
			type: 'string | null',
			description: 'Inline styles. Prefer xstyle for StyleX-optimized styling.'
		},
		{
			name: 'data-testid',
			type: 'string',
			description: 'Test selector for automated testing frameworks.'
		}
	]
};
