// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Breadcrumbs',
	displayName: 'Breadcrumbs',
	keywords: [
		'breadcrumbs',
		'breadcrumb',
		'navigation',
		'nav',
		'crumbs',
		'trail',
		'path',
		'hierarchy',
		'wayfinding',
		'steps'
	],
	group: 'Breadcrumbs',
	category: 'Navigation',
	theming: {
		targets: [
			{
				className: 'astryx-breadcrumb-item',
				visualProps: ['variant']
			},
			{
				className: 'astryx-breadcrumb-item-menu-trigger',
				visualProps: ['variant']
			},
			{
				className: 'astryx-breadcrumb-menu'
			},
			{
				className: 'astryx-breadcrumbs',
				visualProps: ['variant']
			}
		]
	},
	usage: {
		description:
			'Breadcrumbs show a trail of links from the root to the current page. Use them at the top of detail pages, settings panels, or anywhere the user needs to see where they are and navigate back up.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Place breadcrumbs above the page heading so the user sees their location before reading the content.'
			},
			{
				guidance: true,
				description:
					'Keep labels short and match the page titles they link to: "Settings" not "Application Settings Page".'
			},
			{
				guidance: true,
				description:
					'Use the supporting variant in dense UIs like admin panels or sidebars where the breadcrumb should be subtle.'
			},
			{
				guidance: true,
				description:
					'Make the last item plain text, not a link; it represents the current page. The component does this automatically when you set isCurrent.'
			},
			{
				guidance: true,
				description:
					'The component implements the WAI-ARIA APG Breadcrumb pattern: a labelled nav landmark wrapping an ordered list, with aria-current="page" on the current item. A crumb with a menu additionally implements the APG Menu Button pattern, opening on Enter, Space or ArrowDown and closing on Escape.'
			},
			{
				guidance: true,
				description:
					'Give each trail its own label when a page renders more than one, so the nav landmarks stay distinguishable in a screen reader landmark list.'
			},
			{
				guidance: false,
				description:
					'Use breadcrumbs as the primary navigation. They supplement a sidebar or top nav, not replace it.'
			},
			{
				guidance: false,
				description:
					'Show breadcrumbs on top-level pages that have no parent; they add clutter without helping the user.'
			},
			{
				guidance: false,
				description:
					'Let the trail grow beyond 5 levels. If you need more, consider simplifying the page hierarchy instead.'
			},
			{
				guidance: false,
				description:
					'Mirror a separator the bidi algorithm already mirrors. An angle-quote glyph such as › is Bidi_Mirrored, so it flips under RTL on its own and rtlStyles.mirror would flip it back. An arrow glyph such as → and any Icon separator are not, so those do need rtlStyles.mirror through xstyle.'
			}
		],
		anatomy: [
			{
				name: 'Trail',
				required: true,
				description: 'The ordered list of links from root to current page.'
			},
			{
				name: 'Item',
				required: true,
				description:
					'A single step in the trail. Renders as a link or plain text for the current page.'
			},
			{
				name: 'Separator',
				required: true,
				description: 'The character between items. Defaults to "/" but can be customized.'
			},
			{
				name: 'Icon',
				required: false,
				description: 'An optional icon before an item label, like a home icon on the first item.'
			}
		]
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'BreadcrumbItem elements to render inside the breadcrumb trail.',
			required: true
		},
		{
			name: 'separator',
			type: 'string | Snippet',
			description: 'Separator rendered between breadcrumb items.',
			default: "'/'"
		},
		{
			name: 'variant',
			type: "'supporting' | 'default'",
			description: 'Visual variant: supporting is smaller with secondary text styling.',
			default: "'default'"
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the nav landmark (aria-label).',
			default: "'Breadcrumb'"
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
