// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'VisuallyHidden',
	displayName: 'VisuallyHidden',
	keywords: [
		'visually hidden',
		'sr-only',
		'screen reader',
		'accessibility',
		'a11y',
		'aria-live',
		'hidden label',
		'assistive technology'
	],
	category: 'Utility',
	usage: {
		description:
			'Renders content in the accessibility tree while hiding it visually. Use for accessible names on icon-only controls, aria-live announcement regions, and supplementary screen-reader context. Deliberately has no styling props; the whole point is to stay invisible.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use to give icon-only buttons and controls an accessible name that screen readers announce.'
			},
			{
				guidance: true,
				description:
					'Render as a block element (as="div") with aria-live to announce dynamic updates like drag-and-drop or result counts.'
			},
			{
				guidance: false,
				description:
					'Use it to hide content from everyone; it stays in the accessibility tree; use conditional rendering or `hidden` to remove content entirely.'
			},
			{
				guidance: false,
				description:
					'Put interactive controls inside it; the content is not visible and cannot receive pointer input.'
			}
		]
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Content exposed to assistive technology while hidden from sight.'
		},
		{
			name: 'as',
			type: "'object' | 'title' | 'slot' | 'style' | 'small' | 'header' | 'menu' | 'search' | 'button' | 'article' | 'dialog' | 'figure' | 'form' | 'img' | 'link' | 'main' | 'option' | 'table' | 'label' | 'base' | 'body' | 'code' | 'time' | 'section' | 'input' | 'strong' | 'div' | 'li' | 'span' | 'blockquote' | 'hr' | 'a' | 'abbr' | 'address' | 'area' | 'aside' | 'audio' | 'b' | 'bdi' | 'bdo' | 'br' | 'canvas' | 'caption' | 'cite' | 'col' | 'colgroup' | 'data' | 'datalist' | 'dd' | 'del' | 'details' | 'dfn' | 'dl' | 'dt' | 'em' | 'embed' | 'fieldset' | 'figcaption' | 'footer' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'head' | 'hgroup' | 'html' | 'i' | 'iframe' | 'ins' | 'kbd' | 'legend' | 'map' | 'mark' | 'meta' | 'meter' | 'nav' | 'noscript' | 'ol' | 'optgroup' | 'output' | 'p' | 'picture' | 'pre' | 'progress' | 'q' | 'rp' | 'rt' | 'ruby' | 's' | 'samp' | 'script' | 'select' | 'source' | 'sub' | 'summary' | 'sup' | 'tbody' | 'td' | 'template' | 'textarea' | 'tfoot' | 'th' | 'thead' | 'tr' | 'track' | 'u' | 'ul' | 'var' | 'video' | 'wbr'",
			description: 'HTML tag to render as. Use a block element for live regions.',
			default: "'span'"
		}
	]
};
