// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'DateTimeInput',
	displayName: 'Date Time Input',
	keywords: [
		'datetimepicker',
		'datetime',
		'datepicker',
		'timepicker',
		'calendar',
		'schedule',
		'event',
		'deadline',
		'timestamp'
	],
	group: 'DateInput',
	category: 'Form Controls',
	theming: {
		targets: [
			{
				className: 'astryx-date-time-input',
				visualProps: ['size', 'status'],
				states: ['disabled']
			},
			{
				className: 'astryx-date-time-input-date-segment',
				visualProps: ['size', 'status']
			},
			{
				className: 'astryx-date-time-input-time-segment',
				visualProps: ['size', 'status']
			},
			{
				className: 'astryx-date-time-input-toggle-icon',
				states: ['state']
			},
			{
				className: 'astryx-date-time-input-clock-icon'
			},
			{
				className: 'astryx-date-time-input-time-listbox'
			},
			{
				className: 'astryx-date-time-input-time-option'
			}
		]
	},
	usage: {
		description:
			'DateTimeInput combines date and time selection in one field. On mouse/trackpad devices it uses a calendar popover plus text time input; on coarse-pointer devices the closed control still has separate Date and Time segments, and either segment opens a bottom sheet with Date and Time sections, a swipable month calendar, and accessible time wheels. The closed date and time segments stay side by side when at least 400px is available and wrap into full-width rows below 400px, independent of viewport width. Use it for scheduling, event creation, deadline setting, or any form field that needs a specific datetime.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Provide clear labels and descriptions so users understand what datetime is expected.'
			},
			{
				guidance: true,
				description: 'Use min and max to restrict selectable datetimes to valid ranges.'
			},
			{
				guidance: true,
				description: 'Use hasClear when the datetime is optional so the user can reset it.'
			},
			{
				guidance: true,
				description: "Choose the hour format (12h or 24h) that matches your audience's locale."
			},
			{
				guidance: false,
				description: 'Use DateTimeInput when only a date is needed; use DateInput instead.'
			},
			{
				guidance: false,
				description: 'Use DateTimeInput when only a time is needed; use TimeInput instead.'
			},
			{
				guidance: false,
				description:
					'Hide the label without surrounding context that makes the field purpose obvious.'
			},
			{
				guidance: false,
				description:
					'Wrap a disabled DateTimeInput in Tooltip to explain why it is disabled; disabled triggers swallow the hover events the wrapper needs. Use the disabledMessage prop instead.'
			}
		],
		anatomy: [
			{
				name: 'Label',
				required: true,
				description: 'Text above the input describing what datetime is expected.'
			},
			{
				name: 'Date input',
				required: true,
				description:
					'A text input where the user can type a date. Clicking opens a calendar popover.'
			},
			{
				name: 'Calendar icon',
				required: true,
				description: 'A button that opens the calendar popover.'
			},
			{
				name: 'Calendar popover',
				required: false,
				description:
					'A month grid that appears in a popover on desktop, or in the mobile bottom sheet on coarse-pointer devices.'
			},
			{
				name: 'Time input',
				required: true,
				description:
					"A text input for entering the time on desktop; a read-only time segment opening accessible hour/minute/second wheels on touch. The touch Date panel's Save date action advances to Time; the Time panel's Save closes the sheet."
			},
			{
				name: 'Time options popover',
				required: false,
				description:
					'A desktop-only list of preset times at the timeOptionInterval cadence, shown when that prop is set and the time input is clicked or opened with Alt+ArrowDown.'
			},
			{
				name: 'Clear button',
				required: false,
				description: 'A × button that resets the datetime value.'
			},
			{
				name: 'Status message',
				required: false,
				description: 'An error, warning, or success message below the inputs.'
			}
		]
	},
	props: [
		{
			name: 'label',
			type: 'string',
			description: 'Label text.',
			required: true
		},
		{
			name: 'isLabelHidden',
			type: 'boolean',
			description: 'Visually hide the label.',
			default: 'false'
		},
		{
			name: 'description',
			type: 'string',
			description: 'Helper text displayed below the label.'
		},
		{
			name: 'isOptional',
			type: 'boolean',
			description: 'Show an "(optional)" indicator next to the label.',
			default: 'false'
		},
		{
			name: 'isRequired',
			type: 'boolean',
			description: 'Mark the field as required.',
			default: 'false'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Disable the input and picker.',
			default: 'false'
		},
		{
			name: 'disabledMessage',
			type: 'string',
			description:
				'Explains why the input is disabled. With isDisabled, shows a tooltip on hover/keyboard focus and keeps the field focusable via aria-disabled (activation stays blocked). Use this instead of wrapping a disabled DateTimeInput in Tooltip. Disabled controls swallow the hover events an external Tooltip needs.'
		},
		{
			name: 'value',
			type: 'ISODateTimeString',
			description: 'Selected datetime in ISO 8601 format (YYYY-MM-DDTHH:MM or YYYY-MM-DDTHH:MM:SS).'
		},
		{
			name: 'onChange',
			type: '(value: ISODateTimeString) => void',
			description: 'Callback invoked when the selected datetime changes.',
			required: true
		},
		{
			name: 'changeAction',
			type: '(value: ISODateTimeString) => void | Promise<void>',
			description:
				'Async action fired after onChange. Drives optimistic UI updates via useTransition.'
		},
		{
			name: 'isLoading',
			type: 'boolean',
			description:
				'Whether the input is in a loading state. Disables interaction and shows a spinner.',
			default: 'false'
		},
		{
			name: 'min',
			type: 'ISODateTimeString',
			description: 'Minimum selectable datetime. Constrains both date and time selection.'
		},
		{
			name: 'max',
			type: 'ISODateTimeString',
			description: 'Maximum selectable datetime. Constrains both date and time selection.'
		},
		{
			name: 'dateConstraints',
			type: 'ReadonlyArray<(date: Date) => boolean>',
			description: 'Array of custom constraint functions that disable specific dates.'
		},
		{
			name: 'hasSeconds',
			type: 'boolean',
			description: 'Include seconds in the time portion.',
			default: 'false'
		},
		{
			name: 'hourFormat',
			type: "'12h' | '24h'",
			description: "Hour display format. '12h' shows AM/PM; '24h' uses 24-hour notation.",
			default: "'12h'"
		},
		{
			name: 'timeIncrement',
			type: '1 | 5 | 10 | 15 | 30',
			description:
				'Minutes to add or subtract when using arrow keys in the desktop time input. Ignored on the mobile touch sheet, where time is changed with wheels.',
			default: '1'
		},
		{
			name: 'timeOptionInterval',
			type: '5 | 10 | 60 | 15 | 30',
			description:
				'Minute cadence for a dropdown of preset times on the desktop time portion. Set it to turn the desktop time field into a combobox listing every valid time at that cadence (60 gives a 12 AM to 11 PM list). Omitted, the desktop time field stays a plain text input and gains no combobox semantics. Typed entry keeps working either way, so a time between two options is still reachable. Ignored on the mobile touch sheet, where the wheels expose every hour/minute/second.'
		},
		{
			name: 'hasClear',
			type: 'boolean',
			description: 'Shows a clear button when a datetime value is set.',
			default: 'false'
		},
		{
			name: 'placeholder',
			type: 'string',
			description: 'Placeholder text shown in the date portion when no date is selected.',
			default: "'Select a date'"
		},
		{
			name: 'timePlaceholder',
			type: 'string',
			description:
				'Placeholder text shown in the time portion when no time is selected. On touch, this appears in the closed time segment before a time is chosen.',
			default: "'Select a time'"
		},
		{
			name: 'timeLabel',
			type: 'string',
			description:
				'Accessible label for the time portion. Defaults to "{label} time" so it is tied to the field label and localizable.'
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description: 'Size of the input control.',
			default: "'md'"
		},
		{
			name: 'status',
			type: 'InputStatus',
			description: 'Status indicator object for error, warning, or success states with a message.'
		},
		{
			name: 'labelTooltip',
			type: 'string',
			description: 'Tooltip text displayed via an info icon at the end of the label.'
		},
		{
			name: 'numberOfMonths',
			type: '2 | 1',
			description:
				'Number of months displayed simultaneously in the desktop calendar popover. Ignored on the mobile touch sheet, whose Date panel always shows one swipe-paged month at a time.',
			default: '1'
		},
		{
			name: 'weekStartsOn',
			type: "0 | 6 | 2 | 4 | 1 | 3 | 5 | 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat'",
			description:
				'First day of week in the calendar. A number (0 = Sunday to 6 = Saturday) or a three-letter day name.',
			default: '0'
		},
		{
			name: 'width',
			type: 'SizeValue',
			description:
				'Width of the field (number = pixels, string used as-is, e.g. "100%"). Sizes the whole field (label, control, and status) so they stay aligned.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
