// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Stepper',
	displayName: 'Stepper',
	keywords: [
		'stepper',
		'steps',
		'wizard',
		'workflow',
		'progress',
		'multi-step',
		'form wizard',
		'onboarding'
	],
	group: 'Stepper',
	category: 'Navigation',
	theming: {
		targets: [
			{
				className: 'astryx-stepper',
				visualProps: ['orientation', 'indicatorPosition']
			},
			{
				className: 'astryx-step',
				visualProps: ['progress', 'status']
			},
			{
				className: 'astryx-step-indicator',
				visualProps: ['progress', 'status']
			},
			{
				className: 'astryx-step-bar'
			},
			{
				className: 'astryx-step-connector'
			}
		]
	},
	usage: {
		description:
			'Steppers display progress through a sequence of logical and numbered steps. Use them for multi-step workflows like forms, onboarding flows, or checkout processes where users need to see their position and the steps ahead. Rendered as an ordered list (not a navigation landmark).',
		bestPractices: [
			{
				guidance: true,
				description:
					'Keep step labels short and descriptive: "Payment" not "Enter your payment information".'
			},
			{
				guidance: true,
				description:
					'Use the vertical orientation for narrow containers or when steps have longer descriptions.'
			},
			{
				guidance: true,
				description:
					'Provide onStepClick for non-linear workflows where users may need to revisit earlier steps.'
			},
			{
				guidance: true,
				description:
					'Use status only to apply a semantic color (accent/success/warning/error); pass a custom icon for richer indicators.'
			},
			{
				guidance: false,
				description:
					'Use a stepper for fewer than 3 steps; a simple heading or progress bar works better.'
			},
			{
				guidance: false,
				description:
					'Use more than 7 steps; consider grouping related steps or using a different pattern.'
			}
		],
		anatomy: [
			{
				name: 'Progress bar',
				required: true,
				description:
					'A 4px segmented bar per step. Filled for completed and active steps. Advancing one step grows the fill along the track it just covered, so the movement reads as progress rather than a bar changing color. Every other change applies at once: going back, jumping forward by more than one step, mounting mid-flow, and any change at all under prefers-reduced-motion. Where a span is drawn by more than one segment — the on-track layouts split it between two steps, three when a content slot sits between them — the segments run in track order at one constant speed, so the fill reads as a single line growing rather than pieces lighting in turn.'
			},
			{
				name: 'Indicator',
				required: false,
				description:
					'A numbered badge, a check, or any custom icon. Controlled via the indicator prop.'
			},
			{
				name: 'Label',
				required: true,
				description: 'Text identifying the step.'
			},
			{
				name: 'Description',
				required: false,
				description: 'Supporting text below the label with additional context.'
			}
		]
	},
	playground: {
		defaults: {
			activeStep: 1
		}
	},
	props: [
		{
			name: 'activeStep',
			type: 'number',
			description:
				'Zero-based index of the currently active step. Steps before this index are marked as completed.',
			required: true
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Step elements to render in the stepper.',
			required: true
		},
		{
			name: 'orientation',
			type: "'horizontal' | 'vertical'",
			description: 'Layout direction of the stepper.',
			default: "'horizontal'"
		},
		{
			name: 'onStepClick',
			type: '(index: number) => void',
			description:
				'Called when a step is clicked. Enables non-linear navigation. All non-disabled steps become clickable, including not-started steps.'
		},
		{
			name: 'label',
			type: 'string',
			description:
				'Accessible label describing the set of steps (applied to the ordered list). Defaults to a localized "Progress".',
			default: "'Progress' (localized)"
		},
		{
			name: 'density',
			type: "'compact' | 'balanced' | 'spacious'",
			description: 'Controls the padding of all steps.',
			default: "'balanced'"
		},
		{
			name: 'indicatorPosition',
			type: "'separated' | 'on-track'",
			description: 'Position of step indicators relative to the connector track.',
			default: "'separated'"
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for layout customization. Must be a stylex.create() value.'
		}
	]
};
