// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Step',
	displayName: 'Step',
	subComponentOf: 'Stepper',
	description:
		'Individual step within a Stepper. Renders a progress-bar segment, an indicator, and a label with optional description. Progress (completed/active/not-started) is derived from the parent Stepper’s activeStep and this step’s step index.',
	keywords: [
		'stepper',
		'steps',
		'wizard',
		'workflow',
		'progress',
		'multi-step',
		'form wizard',
		'onboarding'
	],
	group: 'Stepper',
	category: 'Navigation',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			step: 1,
			label: 'Billing address',
			description: 'Used for invoices and tax'
		},
		wrapper: {
			component: 'Stepper',
			props: {
				activeStep: 1,
				orientation: 'vertical'
			}
		}
	},
	props: [
		{
			name: 'step',
			type: 'number',
			description:
				'Zero-based index of this step. Used to derive progress (completed/active/not-started) relative to the parent activeStep.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description: 'Step label text.',
			required: true
		},
		{
			name: 'description',
			type: 'string',
			description: 'Optional description shown below the label for additional context.'
		},
		{
			name: 'children',
			type: 'Snippet',
			description:
				'Content rendered below the label and description. Useful in vertical steppers for form fields or detailed step content.'
		},
		{
			name: 'status',
			type: "'success' | 'error' | 'warning' | 'accent'",
			description:
				'Semantic color for the step. Controls color only and maps to the global Astryx semantic tokens. Leave unset for the progress-derived default coloring.'
		},
		{
			name: 'indicator',
			type: "'auto' | 'number' | 'none' | Snippet",
			description:
				"What to show as the step indicator. 'auto' shows a number until completed then a check, 'number' always shows a numbered badge, 'none' hides it, or pass any ReactNode (e.g. an Icon) for a fully custom indicator.",
			default: "'auto'"
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Disables interaction and dims the step indicator and label.',
			default: 'false'
		},
		{
			name: 'isOptional',
			type: 'boolean',
			description:
				'Marks the step as optional, appending an "Optional" affordance after the label.',
			default: 'false'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Trailing content rendered at the end of the label row.'
		},
		{
			name: 'density',
			type: "'compact' | 'balanced' | 'spacious'",
			description:
				'Controls vertical padding of the step. Falls back to the stepper-level density when unset.'
		}
	]
};
