// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'BottomSheetSwitcher',
	displayName: 'Bottom Sheet Switcher',
	keywords: ['bottom sheet', 'switcher', 'multi-step', 'flow', 'wizard'],
	group: 'BottomSheet',
	category: 'Overlay',
	usage: {
		description:
			"Coordinates a multi-step bottom-sheet flow in one shared dialog; set activeSheet to a nested BottomSheet's sheetId to open or switch steps, and to null to close.",
		bestPractices: [
			{
				guidance: true,
				description:
					'Use when each step depends on the previous one and only one step needs attention at a time.'
			},
			{
				guidance: false,
				description:
					"Don't split information across sheets when people need to compare it; use a full-page layout that keeps the relevant content visible together instead."
			}
		]
	},
	playground: {
		defaults: {
			activeSheet: null
		},
		overlay: true
	},
	props: [
		{
			name: 'activeSheet',
			type: 'string | null',
			description:
				"ID of the interactive BottomSheet, or null when the flow should close. Match a nested BottomSheet's unique sheetId; the previous sheet may remain visually present and inert while the new sheet enters, simultaneously align downward behind a shorter step, then fade away.",
			required: true
		},
		{
			name: 'onActiveSheetChange',
			type: '(sheetId: string | null) => void',
			description:
				"Called with null when the active sheet dismisses according to its purpose. Child BottomSheets may use purpose='form' or purpose='required' to limit implicit dismissal while flow controls can still use the same state setter to switch sheets or close the flow.",
			required: true
		},
		{
			name: 'hasScrim',
			type: 'boolean',
			description:
				"Whether the shared dialog is modal. true uses showModal() once for one native ::backdrop, focus trap, scroll lock, and click-to-dismiss when the active BottomSheet has purpose='info'. false uses show() with no backdrop and leaves the page interactive; avoid transformed, contained, or clipping ancestors because the non-modal dialog remains in its containing context.",
			default: 'true'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'BottomSheets identified by unique sheetId values.',
			required: true
		}
	]
};
