// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'TextInput',
	displayName: 'Text Input',
	keywords: [
		'textinput',
		'textfield',
		'input',
		'search',
		'clearable',
		'prefix',
		'suffix',
		'adornment',
		'validation'
	],
	category: 'Data Input',
	theming: {
		targets: [
			{
				className: 'astryx-text-input',
				visualProps: ['size', 'status']
			}
		]
	},
	usage: {
		description:
			'TextInput collects short-form text like names, emails, or search queries. Use it for single-line values where the expected input is brief. Pair it with validation status to guide users through required or formatted fields.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Always provide a visible label so users know what the field is for. Only hide the label when surrounding context makes it obvious, like a search bar with a magnifying-glass icon.'
			},
			{
				guidance: true,
				description:
					'Use validation status with a message to explain what went wrong: "Email must include @" is better than just turning the border red.'
			},
			{
				guidance: true,
				description:
					'Size the input to match the expected content length so users can gauge how much to type: small for zip codes, medium for names, large for URLs.'
			},
			{
				guidance: true,
				description:
					'Add a clear button for search and filter inputs so users can quickly reset without selecting all text.'
			},
			{
				guidance: false,
				description:
					"Don't use placeholder text as a replacement for a label; placeholders disappear on focus and are not reliably read by screen readers."
			},
			{
				guidance: false,
				description:
					"Don't use TextInput for multi-line content like comments or descriptions; use TextArea instead."
			},
			{
				guidance: false,
				description:
					"Don't mark every field as required; only flag mandatory fields so users are not overwhelmed by validation errors."
			},
			{
				guidance: false,
				description:
					"Don't wrap a disabled TextInput in Tooltip to explain why it's disabled; disabled controls swallow the hover events the wrapper needs. Use the disabledMessage prop instead."
			}
		],
		anatomy: [
			{
				name: 'Label',
				required: true,
				description:
					'Text that identifies the field. Always rendered for accessibility even when visually hidden.'
			},
			{
				name: 'Description',
				required: false,
				description:
					'Helper text between the label and the input that provides additional context or formatting hints.'
			},
			{
				name: 'Start icon',
				required: false,
				description:
					'A leading icon inside the input that hints at the expected content, like a magnifying glass for search.'
			},
			{
				name: 'Placeholder',
				required: false,
				description: 'Hint text shown when the input is empty. Disappears on focus.'
			},
			{
				name: 'Clear button',
				required: false,
				description: 'A trailing × button that resets the value and returns focus to the input.'
			},
			{
				name: 'Spinner',
				required: false,
				description:
					'Loading indicator that appears during async actions like server-side validation.'
			},
			{
				name: 'Status icon',
				required: false,
				description:
					'A trailing icon (error, warning, or success) that communicates validation state.'
			}
		]
	},
	props: [
		{
			name: 'type',
			type: "'text' | 'email' | 'password'",
			description: 'The HTML input type.',
			default: "'text'"
		},
		{
			name: 'label',
			type: 'string',
			description: 'Label text for the input: always rendered for accessibility.',
			required: true
		},
		{
			name: 'value',
			type: 'string',
			description: 'Current value of the input.',
			required: true
		},
		{
			name: 'onChange',
			type: '(value: string, e: Event) => void',
			description: 'Callback fired when the input value changes.'
		},
		{
			name: 'changeAction',
			type: '(value: string, e: Event) => void | Promise<void>',
			description:
				'Async action fired after onChange (if not prevented). Triggers optimistic update and shows a loading spinner while pending.'
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description: 'Size variant of the input.',
			default: "'md'"
		},
		{
			name: 'isLabelHidden',
			type: 'boolean',
			description: 'Visually hides the label while keeping it accessible to screen readers.',
			default: 'false'
		},
		{
			name: 'description',
			type: 'string',
			description: 'Description text displayed between the label and input.'
		},
		{
			name: 'isOptional',
			type: 'boolean',
			description:
				'Displays an "Optional" indicator next to the label. Mutually exclusive with isRequired.',
			default: 'false'
		},
		{
			name: 'isRequired',
			type: 'boolean',
			description:
				'Displays a "Required" indicator next to the label and sets aria-required. Mutually exclusive with isOptional.',
			default: 'false'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Disables the input, preventing interaction and dimming the element.',
			default: 'false'
		},
		{
			name: 'disabledMessage',
			type: 'string',
			description:
				'Explains why the input is disabled. With isDisabled, shows a tooltip on hover/keyboard focus and keeps the input focusable via aria-disabled (the field becomes read-only). Use this instead of wrapping a disabled TextInput in Tooltip. Disabled controls swallow the hover events an external Tooltip needs.'
		},
		{
			name: 'isLoading',
			type: 'boolean',
			description: 'Puts the input in a loading state, showing a spinner and setting aria-busy.',
			default: 'false'
		},
		{
			name: 'placeholder',
			type: 'string',
			description: 'Placeholder text shown when the input is empty.'
		},
		{
			name: 'labelTooltip',
			type: 'string',
			description: 'Tooltip text displayed in an info icon at the end of the label.'
		},
		{
			name: 'startIcon',
			type: 'Snippet',
			description:
				'SVG icon component displayed at the start of the input. See `astryx docs icons` for valid semantic names.'
		},
		{
			name: 'status',
			type: 'InputStatus',
			description:
				'Validation status: applies a colored border and status icon. If message is provided, displays a floating message below the input. Error type also sets aria-invalid.'
		},
		{
			name: 'statusVariant',
			type: "'tooltip' | 'attached' | 'detached'",
			description:
				'How the status message is placed relative to the input. attached overlaps directly below the input (bordered treatment); detached floats below as a separate element with spacing; tooltip hides the message box and surfaces it in a tooltip on the status icon.',
			default: "'attached'"
		},
		{
			name: 'hasClear',
			type: 'boolean',
			description:
				'Shows a clear (×) button when the input has a value. Clicking it clears the value and returns focus to the input.',
			default: 'false'
		},
		{
			name: 'hasAutoFocus',
			type: 'boolean',
			description: 'Automatically focuses the input on mount.',
			default: 'false'
		},
		{
			name: 'htmlName',
			type: 'string',
			description: 'The HTML name attribute for the input, useful for form submissions.'
		},
		{
			name: 'width',
			type: 'SizeValue',
			description:
				'Width of the field (number = pixels, string used as-is, e.g. "100%"). Sizes the whole field (label, control, and status) so they stay aligned.'
		}
	]
};
