// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Skeleton',
	displayName: 'Skeleton',
	keywords: [
		'skeleton',
		'placeholder',
		'loading',
		'shimmer',
		'pulse',
		'loader',
		'bone',
		'ghost',
		'preloader'
	],
	category: 'Feedback & Status',
	theming: {
		targets: [
			{
				className: 'astryx-skeleton'
			}
		]
	},
	usage: {
		description:
			'An animated shimmer placeholder that previews the shape of content while it loads. Use it to build loading screens that match the layout of the real content. For content with unknown dimensions, use Spinner instead.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Match the size and shape of the content being loaded to create a realistic placeholder.'
			},
			{
				guidance: true,
				description:
					'Stagger multiple skeletons with the `index` prop for a natural wave animation.'
			},
			{
				guidance: false,
				description: 'Use when the content dimensions are unknown; use Spinner instead.'
			},
			{
				guidance: false,
				description: 'Combine with a Spinner on the same content area; pick one loading pattern.'
			},
			{
				guidance: false,
				description:
					'Show skeletons indefinitely; if loading takes too long, show an error or empty state instead.'
			}
		]
	},
	playground: {
		defaults: {
			width: 320,
			height: 80
		}
	},
	props: [
		{
			name: 'width',
			type: 'number | string',
			description: 'Width in pixels (number) or CSS value (string).',
			default: "'100%'"
		},
		{
			name: 'height',
			type: 'number | string',
			description: 'Height in pixels (number) or CSS value (string).',
			default: "'100%'"
		},
		{
			name: 'radius',
			type: "0 | 'none' | 1 | 2 | 3 | 4 | 'rounded'",
			description:
				'Border radius using design token scale. Use none for sharp corners, rounded for fully rounded (avatars, pills, circles).',
			default: '3'
		},
		{
			name: 'index',
			type: 'number',
			description:
				'Index for staggered animation timing. For element at index n, animation starts at DELAY_TIME + (STAGGER_TIME × n).',
			default: '0'
		}
	]
};
