// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ContextMenu',
	displayName: 'Context Menu',
	keywords: ['contextmenu', 'right-click', 'menu', 'popover', 'actions', 'context'],
	group: 'ContextMenu',
	category: 'Action',
	isHiddenFromOverview: true,
	theming: {
		targets: [
			{
				className: 'astryx-context-menu'
			}
		],
		vars: [
			{
				name: '--_dropdown-menu-radius',
				description: 'Border radius of the menu popup',
				default: 'var(--radius-container)',
				private: true
			},
			{
				name: '--_dropdown-menu-padding',
				description: 'Inner padding of the menu popup',
				default: 'var(--spacing-1)',
				private: true
			}
		],
		derived: [
			{
				property: 'borderRadius',
				vars: ['--_dropdown-menu-radius']
			},
			{
				property: 'padding',
				vars: ['--_dropdown-menu-padding']
			}
		]
	},
	usage: {
		description:
			'A right-click context menu that appears at the cursor position. Use to provide contextual actions for specific elements or regions without cluttering the UI with visible buttons.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Keep menu items concise and action-oriented; users expect quick access to contextual actions.'
			},
			{
				guidance: true,
				description:
					'Use sections and dividers to group related actions when the menu has many items.'
			},
			{
				guidance: true,
				description:
					'Ensure all context menu actions are also accessible via other UI elements for keyboard-only users.'
			},
			{
				guidance: false,
				description:
					'Use a ContextMenu as the only way to access important actions; not all users know to right-click.'
			},
			{
				guidance: false,
				description:
					'Place more than 10–12 items in a single menu without grouping them into sections.'
			}
		]
	},
	playground: {
		defaults: {
			items: [
				{
					label: 'Edit'
				},
				{
					label: 'Duplicate'
				},
				{
					type: 'divider'
				},
				{
					label: 'Delete'
				}
			]
		}
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'The trigger area: right-click on this content to open the menu.',
			required: true
		},
		{
			name: 'items',
			type: 'DropdownMenuOption[]',
			description:
				'Array of menu entries. Each entry is one of: an action item `{label, onClick?, icon?, isDisabled?}`, a divider `{type: "divider"}`, or a section `{type: "section", title?, items: [...action items]}`.',
			required: true
		},
		{
			name: 'menuContent',
			type: 'Snippet<[]>',
			description:
				'Custom JSX menu content for compound mode. Use instead of items for dynamic or stateful menus.'
		},
		{
			name: 'menuWidth',
			type: 'number | string',
			description: 'Custom menu width.',
			default: "'160px'"
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description: 'Size of menu items: controls padding density.',
			default: "'md'"
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible name for the menu surface, announced when it opens.',
			default: "'Context menu'"
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'When true, right-click shows the native browser context menu instead.',
			default: 'false'
		}
	]
};
