// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'useTableSelectionState',
	displayName: 'useTableSelectionState',
	subComponentOf: 'Table',
	description:
		'State management companion for useTableSelection. Handles disabled/selectable row filtering for select-all automatically: disabled rows are frozen (preserved across select-all/deselect-all), non-selectable rows are excluded.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	props: [
		{
			name: 'data',
			type: 'T[]',
			description: 'The full data array rendered in the table.',
			required: true
		},
		{
			name: 'idKey',
			type: '(keyof T & string) | ((item: T) => string)',
			description: 'Key extractor: property name or function returning a unique string ID.',
			required: true
		},
		{
			name: 'selectedKeys',
			type: 'Set<string>',
			description: 'Controlled set of selected item IDs.',
			required: true
		},
		{
			name: 'setSelectedKeys',
			type: '(next: Set<string>) => void',
			description: 'Setter for the controlled selected keys.',
			required: true
		},
		{
			name: 'getIsItemSelectable',
			type: '(item: T) => boolean',
			description:
				'Should this row show a checkbox? Non-selectable rows are excluded from select-all.',
			default: '() => true'
		},
		{
			name: 'getIsItemEnabled',
			type: '(item: T) => boolean',
			description:
				'Is this row checkbox interactive? Disabled rows are frozen: select-all preserves their state.',
			default: '() => true'
		}
	]
};
