// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'useTableSelection',
	displayName: 'useTableSelection',
	subComponentOf: 'Table',
	description:
		'Hook that returns a TablePlugin implementing row selection with checkboxes, select-all, and aria-selected. Uses React Context for independent checkbox re-renders.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	props: [
		{
			name: 'getIsItemSelected',
			type: '(item: T) => boolean',
			description: 'Returns whether the given item is currently selected.',
			required: true
		},
		{
			name: 'onSelectItem',
			type: '(event: { item: T; isSelected: boolean; }) => void',
			description: 'Called when a row checkbox is toggled. isSelected is the new desired state.',
			required: true
		},
		{
			name: 'onSelectAll',
			type: '(event: { isAllSelected: boolean; }) => void',
			description: 'Called when the select-all header checkbox is toggled.',
			required: true
		},
		{
			name: 'getIsAllSelected',
			type: '() => boolean',
			description: 'Returns whether all selectable items are currently selected.',
			required: true
		},
		{
			name: 'getIsIndeterminate',
			type: '() => boolean',
			description:
				'Returns whether selection is partial (some but not all). Renders the select-all checkbox in indeterminate state.'
		},
		{
			name: 'getIsItemSelectable',
			type: '(item: T) => boolean',
			description:
				'Returns whether a row should show a checkbox. Non-selectable rows render nothing in the selection cell.',
			default: '() => true'
		},
		{
			name: 'getIsItemEnabled',
			type: '(item: T) => boolean',
			description:
				'Returns whether a row checkbox is interactive. Disabled rows show a disabled checkbox.',
			default: '() => true'
		},
		{
			name: 'getRowLabel',
			type: '(item: T) => string',
			description:
				'Derives a human-readable identity for a row; the row checkbox\'s hidden label becomes `Select ${getRowLabel(item)}` so screen readers announce which row each checkbox selects. Falls back to "Select row" when omitted.'
		}
	]
};
