// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'StatusDot',
	displayName: 'Status Dot',
	keywords: [
		'statusdot',
		'dot',
		'indicator',
		'status',
		'signal',
		'presence',
		'availability',
		'online',
		'pip'
	],
	category: 'Feedback & Status',
	theming: {
		targets: [
			{
				className: 'astryx-statusdot',
				visualProps: ['variant']
			}
		]
	},
	usage: {
		description:
			'A small colored dot that communicates status like online/offline presence or severity levels. Supports five semantic variants and an optional pulse animation. Always pair with a visible text label, as color alone should not carry meaning.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Always pair with a visible text label so status is not conveyed by color alone.'
			},
			{
				guidance: true,
				description: 'Provide a descriptive `label` prop for screen reader accessibility.'
			},
			{
				guidance: false,
				description:
					'Use the pulse animation for purely decorative purposes; reserve it for states that require immediate attention.'
			},
			{
				guidance: false,
				description: 'Rely on color alone to communicate status; always include text.'
			}
		]
	},
	props: [
		{
			name: 'variant',
			type: "'success' | 'neutral' | 'error' | 'warning' | 'accent'",
			description: 'Semantic color variant.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label surfaced via aria-label.',
			required: true
		},
		{
			name: 'isPulsing',
			type: 'boolean',
			description: 'Enables a pulse animation; respects prefers-reduced-motion: reduce.',
			default: 'false'
		},
		{
			name: 'tooltip',
			type: 'string',
			description: 'Tooltip text shown on hover to explain the status meaning.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
