// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'StatusDot',
	displayName: 'Status Dot',
	keywords: [
		'statusdot',
		'dot',
		'indicator',
		'status',
		'signal',
		'presence',
		'availability',
		'online',
		'pip'
	],
	category: 'Feedback & Status',
	theming: {
		targets: [
			{
				className: 'astryx-statusdot',
				visualProps: ['variant']
			}
		]
	},
	usage: {
		description:
			'A small colored dot that communicates status like online/offline presence or severity levels. Supports five semantic variants and an optional pulse animation. Always pair with a visible text label, as color alone should not carry meaning.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use StatusDot as a binary present/absent signal; avoid encoding many distinct states in a single dot, since color and size alone cannot reliably distinguish them.'
			},
			{
				guidance: true,
				description:
					'Always pair with a visible text label so status is not conveyed by color alone.'
			},
			{
				guidance: true,
				description: 'Provide a descriptive `label` prop for screen reader accessibility.'
			},
			{
				guidance: true,
				description:
					'Pair the dot with an icon that carries the status as a distinct shape when it must stand on its own without adjacent text, so meaning survives without color.'
			},
			{
				guidance: true,
				description:
					"If you can't add a label or an icon, make sure the status is conveyed elsewhere accessibly (e.g. adjacent text, a table column, or a live region)."
			},
			{
				guidance: false,
				description:
					'Rely on color alone to communicate status; StatusDot is not fully accessible in isolation, so the builder must make the status distinguishable in context via a label, an icon, or an accessible alternative.'
			},
			{
				guidance: false,
				description:
					'Use the pulse animation for purely decorative purposes; reserve it for states that require immediate attention.'
			}
		]
	},
	props: [
		{
			name: 'variant',
			type: "'success' | 'neutral' | 'error' | 'warning' | 'accent'",
			description: 'Semantic color variant.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label surfaced via aria-label.',
			required: true
		},
		{
			name: 'isPulsing',
			type: 'boolean',
			description: 'Enables a pulse animation; respects prefers-reduced-motion: reduce.',
			default: 'false'
		},
		{
			name: 'tooltip',
			type: 'string',
			description: 'Tooltip text shown on hover to explain the status meaning.'
		},
		{
			name: 'icon',
			type: 'Snippet',
			description:
				"Optional icon rendered centered inside the dot, painted in currentColor (the variant's ink). Gives the status a non-color mark, so use a different icon per status. Booleans and empty strings are ignored, so `cond && <Icon />` is safe. Same contract as AvatarStatusDot."
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
