// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Spinner',
	displayName: 'Spinner',
	keywords: [
		'spinner',
		'loader',
		'loading',
		'circular',
		'progress',
		'spin',
		'activity',
		'busy',
		'indeterminate'
	],
	category: 'Feedback & Status',
	theming: {
		targets: [
			{
				className: 'astryx-spinner',
				visualProps: ['size', 'shade']
			}
		],
		vars: [
			{
				name: '--spinner-diameter',
				description:
					"Diameter of the drawn ring. Set it on a size-variant target to retheme what each named size resolves to, e.g. spinner: { 'size:xl': { '--spinner-diameter': '2.5rem' } }. The rendered box is this plus the stroke width on each side, and follows automatically. Any length works — rem, em and calc() are resolved before the ring is drawn.",
				default: '10px (sm), 14px (md), 18px (lg), 28px (xl)'
			},
			{
				name: '--spinner-stroke-width',
				description:
					'Stroke width of both circles the ring is drawn from — the moving arc and the track behind it. Set it per size alongside the diameter. One stroke width drives both, so 0 is honoured as a zero-width stroke and paints nothing at all rather than falling back to the default — for an arc with no track behind it, set --spinner-track-color to transparent instead.',
				default: '2px (sm), 3px (md), 3px (lg), 4px (xl)'
			},
			{
				name: '--spinner-color',
				description:
					"Color of the moving arc. Defaults to the shade's token, so set it on a shade-variant target to retheme one shade — spinner: { 'shade:subtle': { '--spinner-color': 'var(--color-text-tertiary)' } } — or on the base target to retheme all four. Accepts any color notation, including var(), color-mix() and currentColor.",
				default:
					'var(--color-accent) (default), var(--color-text-secondary) (subtle), var(--color-on-dark) (onMedia), currentColor (inherit)'
			},
			{
				name: '--spinner-track-color',
				description:
					'Color of the track the arc travels on. Set it to `transparent` for an arc with no track. The onMedia and inherit shades draw the track at reduced alpha (30%) so it reads against an arbitrary backdrop; that fade applies to a themed color too.',
				default:
					'var(--color-track) (default, subtle), var(--color-on-dark) (onMedia), currentColor (inherit)'
			}
		]
	},
	usage: {
		description:
			'An animated loading indicator for processes with unknown duration, such as data fetching or form submission. Supports visible labels, multiple sizes, and a dark background variant. For content with known dimensions, use Skeleton instead.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Provide a meaningful label to describe what is loading for screen reader users.'
			},
			{
				guidance: true,
				description: 'Use the "onMedia" shade when placed on dark or accent-colored backgrounds.'
			},
			{
				guidance: false,
				description:
					'Use for content areas with known dimensions; use Skeleton to preserve layout instead.'
			},
			{
				guidance: false,
				description:
					'Stack multiple spinners in the same view; use one to represent the overall loading state.'
			}
		]
	},
	props: [
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg' | 'xl'",
			description: 'Spinner size — ring diameter (10px, 14px, 18px, 28px).',
			default: "'md'"
		},
		{
			name: 'shade',
			type: "'inherit' | 'default' | 'subtle' | 'onMedia'",
			description: 'Color shade for light or dark backgrounds.',
			default: "'default'"
		},
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Visible content below the spinner. String labels auto-set aria-label.'
		},
		{
			name: 'aria-label',
			type: 'string | null',
			description:
				'Accessible name for screen readers. Defaults to label (if string) or "Loading".',
			default: "'Loading'"
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
