// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Spinner',
	displayName: 'Spinner',
	keywords: [
		'spinner',
		'loader',
		'loading',
		'circular',
		'progress',
		'spin',
		'activity',
		'busy',
		'indeterminate'
	],
	category: 'Feedback & Status',
	theming: {
		targets: [
			{
				className: 'astryx-spinner',
				visualProps: ['size', 'shade']
			}
		]
	},
	usage: {
		description:
			'An animated loading indicator for processes with unknown duration, such as data fetching or form submission. Supports visible labels, multiple sizes, and a dark background variant. For content with known dimensions, use Skeleton instead.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Provide a meaningful label to describe what is loading for screen reader users.'
			},
			{
				guidance: true,
				description: 'Use the "onMedia" shade when placed on dark or accent-colored backgrounds.'
			},
			{
				guidance: false,
				description:
					'Use for content areas with known dimensions; use Skeleton to preserve layout instead.'
			},
			{
				guidance: false,
				description:
					'Stack multiple spinners in the same view; use one to represent the overall loading state.'
			}
		]
	},
	props: [
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg' | 'xl'",
			description: 'Spinner size (10px, 14px, 18px).',
			default: "'md'"
		},
		{
			name: 'shade',
			type: "'inherit' | 'default' | 'subtle' | 'onMedia'",
			description: 'Color shade for light or dark backgrounds.',
			default: "'default'"
		},
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Visible content below the spinner. String labels auto-set aria-label.'
		},
		{
			name: 'aria-label',
			type: 'string | null',
			description:
				'Accessible name for screen readers. Defaults to label (if string) or "Loading".',
			default: "'Loading'"
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
