// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'useTableRowIndex',
	displayName: 'useTableRowIndex',
	subComponentOf: 'Table',
	description:
		'Hook that returns a TablePlugin which prepends a right-aligned, monospaced row-number column. Numbering follows the rendered data order (reflecting the current sort / filter / pagination view) and starts at 1 by default. Astryx renderCell receives only the row item, so the plugin takes the rendered data array to derive each ordinal.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	props: [
		{
			name: 'data',
			type: 'T[]',
			description:
				'The data array currently rendered by the table (post sort/filter/page). Numbering follows this order.',
			required: true
		},
		{
			name: 'getRowKey',
			type: '(item: T) => string',
			description:
				'Optional key extractor returning a unique string per row. When provided, index lookup is keyed by the returned string; otherwise items are matched by reference identity. Memoize with useCallback for a stable plugin identity.'
		},
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Header label for the index column.',
			default: "'#'"
		},
		{
			name: 'startFrom',
			type: 'number',
			description: 'First index value.',
			default: '1'
		}
	]
};
