// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'function',
	name: 'useHoverCard',
	displayName: 'useHoverCard',
	group: 'HoverCard',
	keywords: ['hovercard', 'hover', 'preview', 'card', 'tooltip', 'popup', 'floating', 'anchor'],
	params: [
		{
			name: 'placement',
			type: "'below' | 'above' | 'end' | 'start'",
			description:
				"Position relative to the trigger. Logical: start/end resolve against the popover's own inherited direction (RTL mirrors in pure CSS).",
			default: "'above'"
		},
		{
			name: 'alignment',
			type: "'end' | 'start' | 'center'",
			description:
				"Alignment along the placement axis. Logical: start/end resolve against the popover's own inherited direction (RTL mirrors in pure CSS).",
			default: "'center'"
		},
		{
			name: 'delay',
			type: 'number',
			description: 'Delay before showing the hover card on hover, in milliseconds.',
			default: '300'
		},
		{
			name: 'hideDelay',
			type: 'number',
			description: 'Delay before hiding after mouse or focus leaves, in milliseconds.',
			default: '200'
		},
		{
			name: 'focusTrigger',
			type: "'auto' | 'always' | 'never'",
			description:
				'When focus should open the hover card. auto only attaches focus listeners to naturally focusable elements.',
			default: "'auto'"
		},
		{
			name: 'touchTrigger',
			type: "'none' | 'auto' | 'tap'",
			description:
				'What a tap does where there is no hover. auto opens on tap unless the trigger performs an action of its own; tap always opens; none never opens on touch.',
			default: "'auto'"
		},
		{
			name: 'isEnabled',
			type: 'boolean',
			description: 'Whether hover and focus triggers are enabled.',
			default: 'true'
		},
		{
			name: 'label',
			type: 'string',
			description:
				'Accessible name for the hover card popup. When provided, the popup is exposed as a named role="dialog"; when omitted, it falls back to role="group" (a group may validly be unnamed).'
		},
		{
			name: 'isOpen',
			type: 'boolean',
			description:
				'Controlled open state. true force-shows, false force-hides, undefined lets hover/focus manage visibility.'
		},
		{
			name: 'isDefaultOpen',
			type: 'boolean',
			description: 'Whether the hover card should be shown on mount.',
			default: 'false'
		},
		{
			name: 'onShow',
			type: '() => void',
			description: 'Callback fired when the hover card becomes visible.'
		},
		{
			name: 'onHide',
			type: '() => void',
			description: 'Callback fired when the hover card is hidden.'
		}
	],
	returns: [
		{
			name: 'ref',
			type: '(node: HTMLElement | null) => void',
			description:
				'Combined ref that sets both position and interaction on the same trigger element.'
		},
		{
			name: 'positionRef',
			type: '(node: HTMLElement | null) => void',
			description:
				'Ref for the positioning anchor element. Use when position and interaction live on different elements.'
		},
		{
			name: 'interactionRef',
			type: '(node: HTMLElement | null) => void',
			description:
				'Ref for the hover/focus interaction element. Use with positionRef for split trigger patterns.'
		},
		{
			name: 'anchorId',
			type: 'string',
			description: 'CSS anchor name for advanced positioning cases.'
		},
		{
			name: 'describedBy',
			type: 'string',
			description: 'ID to compose into aria-describedby on the trigger.'
		},
		{
			name: 'renderHoverCard',
			type: "(children: string | Snippet, props?: Omit<ContextRenderProps, 'positioning'>) => string | Snippet",
			description:
				'Render function for the anchor-positioned hover card content. The positioning opt-out is excluded: the hover card always derives its position from placement/alignment.'
		},
		{
			name: 'show',
			type: '() => void',
			description: 'Imperatively show the hover card immediately.'
		},
		{
			name: 'hide',
			type: '() => void',
			description: 'Imperatively hide the hover card immediately.'
		}
	],
	usage: {
		description:
			'Headless hook for hover-triggered floating cards. Builds on useLayer with hover/focus intent detection, configurable delays, safe hover behavior, and accessible aria-describedby linking. Use for rich previews on hover when you need full control over the trigger or rendered content.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use for rich content previews such as user profiles, entity summaries, and link previews.'
			},
			{
				guidance: true,
				description:
					'Prefer the HoverCard component for standard trigger-content pairs; use the hook for custom trigger patterns.'
			},
			{
				guidance: false,
				description: 'Use for simple text hints: use Tooltip or useTooltip instead.'
			}
		]
	},
	relatedComponents: ['HoverCard', 'Tooltip', 'Popover'],
	relatedHooks: ['useLayer', 'useTooltip', 'usePopover'],
	importPath: '@astryx-svelte/core',
	category: 'interaction'
};
