// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Tab',
	displayName: 'Tab',
	subComponentOf: 'TabList',
	description:
		'Individual tab item that renders as a button or an anchor link, with selected-state styling and optional icons.',
	keywords: [
		'tabs',
		'tabbar',
		'tabstrip',
		'navigation',
		'tabpanel',
		'tabgroup',
		'segmented',
		'navtabs',
		'tab'
	],
	group: 'Tabs',
	category: 'Navigation',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			value: 'tab-1',
			label: 'Tab'
		},
		wrapper: {
			component: 'TabList',
			props: {
				value: 'tab-1'
			}
		}
	},
	props: [
		{
			name: 'value',
			type: 'string',
			description: 'Unique value for this tab, matched against TabListContext.value.',
			required: true
		},
		{
			name: 'label',
			type: 'string',
			description:
				'Accessible label for this tab. Used as visible text by default, or as aria-label when isLabelHidden is true.',
			required: true
		},
		{
			name: 'isLabelHidden',
			type: 'boolean',
			description:
				'Whether the label is visually hidden. When true, only the icon and endContent are displayed, and label is used as aria-label for accessibility.',
			default: 'false'
		},
		{
			name: 'href',
			type: 'string',
			description: 'URL to navigate to; when provided, the tab renders as an anchor element.'
		},
		{
			name: 'as',
			type: 'LinkComponentType',
			description:
				'Custom component to render instead of <a> for link tabs. Overrides the LinkProvider default. Only applies when href is provided.'
		},
		{
			name: 'icon',
			type: 'Snippet',
			description: 'Icon element shown when the tab is not selected.'
		},
		{
			name: 'selectedIcon',
			type: 'Snippet',
			description:
				'Icon element shown when the tab is selected; falls back to icon if not provided.'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Content rendered after the label, such as a badge count or status dot.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
