// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'AlertDialog',
	displayName: 'Alert Dialog',
	keywords: [
		'alert',
		'alertdialog',
		'confirm',
		'confirmation',
		'destructive',
		'delete',
		'modal',
		'dialog',
		'imperative'
	],
	group: 'Dialog',
	category: 'Overlay',
	isHiddenFromOverview: true,
	theming: {
		targets: [
			{
				className: 'astryx-alert-dialog'
			}
		]
	},
	usage: {
		description:
			'AlertDialog asks the user to confirm a destructive or irreversible action before it happens. Use it for things like deleting content, revoking access, or discarding unsaved changes.\n\nIt implements the WAI-ARIA APG [Alert Dialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/): `role="alertdialog"`, a title linked by `aria-labelledby`, a consequence description linked by `aria-describedby`, focus moved into the dialog on open and returned to the trigger on close, and no dismissal by clicking outside. Escape cancels.\n\nFor cases where you want to show an alert without managing open state, use the `useImperativeAlertDialog` hook: call `alert.show(options)` and render `alert.element` in your tree.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Make the action button label specific: "Delete project" is better than "OK" or "Confirm".'
			},
			{
				guidance: true,
				description:
					'Describe what will happen in the description so the user knows the consequences before confirming.'
			},
			{
				guidance: true,
				description:
					'Keep the cancel button first: it takes initial focus, so the least destructive choice is the one already selected when the dialog opens.'
			},
			{
				guidance: false,
				description: 'Use AlertDialog for non-destructive actions; use a standard Dialog instead.'
			},
			{
				guidance: false,
				description:
					'Rely on color alone to signal danger; the action label itself should say what will happen.'
			},
			{
				guidance: false,
				description:
					'Close the dialog from onAction before the work finishes; hold it open with isActionLoading and call onOpenChange(false) when the action settles.'
			}
		],
		anatomy: [
			{
				name: 'Title',
				required: true,
				description:
					'The question being asked. Renders as a level-2 heading and labels the dialog via aria-labelledby.'
			},
			{
				name: 'Description',
				required: true,
				description:
					'What will happen if the user confirms. Linked to the dialog via aria-describedby.'
			},
			{
				name: 'Cancel button',
				required: true,
				description:
					'Ghost button that dismisses without acting. Takes initial focus, and Escape does the same thing.'
			},
			{
				name: 'Action button',
				required: true,
				description:
					'The confirming action. Destructive by default; shows a spinner while isActionLoading is set.'
			},
			{
				name: 'Backdrop',
				required: true,
				description:
					'Overlay behind the dialog that blocks page interaction. Clicking it does not dismiss.'
			}
		]
	},
	playground: {
		defaults: {
			isOpen: true,
			isInline: true,
			title: 'Delete item?',
			description:
				'This action cannot be undone. The item and all its data will be permanently removed.',
			actionLabel: 'Delete'
		}
	},
	props: [
		{
			name: 'isOpen',
			type: 'boolean',
			description: 'Whether the dialog is open.',
			required: true
		},
		{
			name: 'onOpenChange',
			type: '(isOpen: boolean) => unknown',
			description: 'Visibility change callback.',
			required: true
		},
		{
			name: 'title',
			type: 'string',
			description: 'Dialog title. Linked via aria-labelledby.',
			required: true
		},
		{
			name: 'description',
			type: 'string',
			description: 'Consequence description. Linked via aria-describedby.',
			required: true
		},
		{
			name: 'actionLabel',
			type: 'string',
			description: 'Action button label.',
			required: true
		},
		{
			name: 'onAction',
			type: '() => unknown',
			description: 'Called when action button is clicked. Does NOT auto-close.',
			required: true
		},
		{
			name: 'cancelLabel',
			type: 'string',
			description: 'Cancel button label.',
			default: "'Cancel'"
		},
		{
			name: 'actionVariant',
			type: "'primary' | 'secondary' | 'ghost' | 'destructive'",
			description: 'Action button variant.',
			default: "'destructive'"
		},
		{
			name: 'isActionLoading',
			type: 'boolean',
			description: 'Shows loading spinner on the action button.'
		},
		{
			name: 'width',
			type: 'number | string',
			description: 'Dialog width.',
			default: '400'
		},
		{
			name: 'isInline',
			type: 'boolean',
			description:
				'Renders alert dialog content inline without modal behavior. For documentation previews and showcases only. Not being a modal, the inline path renders role="group" instead of role="alertdialog".',
			default: 'false'
		}
	]
};
