// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'AvatarGroup',
	displayName: 'Avatar Group',
	keywords: [
		'avatar',
		'group',
		'facepile',
		'stack',
		'overlap',
		'participants',
		'assignees',
		'members',
		'team'
	],
	group: 'Avatar',
	category: 'Content',
	theming: {
		targets: [
			{
				className: 'astryx-avatar-group',
				visualProps: ['size']
			},
			{
				className: 'astryx-avatar-group-overflow'
			}
		]
	},
	usage: {
		description:
			'AvatarGroup displays multiple avatars in an overlapping row with an optional overflow indicator. Uses a compositional API: pass Avatar children directly so each avatar can carry its own props (status dots, click handlers, etc.).',
		bestPractices: [
			{
				guidance: true,
				description: 'Set max to limit visible avatars when the list is long; 3-5 is typical.'
			},
			{
				guidance: true,
				description:
					'Use AvatarGroupOverflow for custom overflow content like a popover trigger or "add member" button.'
			},
			{
				guidance: true,
				description: 'Pass status dots, click handlers, or tooltips directly on each Avatar child.'
			},
			{
				guidance: true,
				description:
					'Make avatars interactive with href or onClick to link to profiles. Interactive avatars share a single Tab stop; arrow keys move between them, and the group announces a keyboard hint to assistive tech.'
			},
			{
				guidance: false,
				description: "Don't nest AvatarGroups; use a single group with all avatars."
			}
		],
		anatomy: [
			{
				name: 'Avatar children',
				required: true,
				description: 'Avatar elements that form the overlapping row. Each can have its own props.'
			},
			{
				name: 'Overflow indicator',
				required: false,
				description:
					'A "+N" circle at the end showing hidden count, or a custom AvatarGroupOverflow slot.'
			}
		]
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description:
				'Avatar children, optionally followed by one AvatarGroupOverflow. Consumers handle slicing to the desired visible count.',
			required: true
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg' | 'xl' | 'xsm' | 16 | 20 | 24 | 32 | 36 | 40 | 48 | 60 | 64 | 72 | 96 | 128 | 144 | 180",
			description: 'Size applied to all avatars via context.',
			default: "'md'"
		},
		{
			name: 'ref',
			type: 'HTMLDivElement | null',
			description: 'Ref forwarded to the root element.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for layout customization.'
		},
		{
			name: 'data-testid',
			type: 'string',
			description: 'Test selector for automated testing frameworks.'
		}
	]
};
