// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'useTableGroupedRows',
	displayName: 'useTableGroupedRows',
	subComponentOf: 'Table',
	description:
		'Hook that groups a flat data array into collapsible section rows. Each distinct groupBy value becomes a full-width section-header row with a chevron toggle, the group label, and a member count; collapsing hides that group\'s data rows while keeping the header visible. Mirrors useTableTreeState: the consumer owns the collapsedGroups set and the hook returns {data, plugin, idKey}: pass them to Table as data, plugins, and idKey respectively. Grouping runs on the rows you hand it, so with pagination the order is filter, sort, slice, then group — sort by the group key first and the user\'s keys second, so a section\'s rows stay contiguous and each page appends to the bottom of the table instead of splicing rows in above the reader. A page that ends on a row count still cuts mid-section, and the heading then counts what has loaded rather than what exists — "6" quietly becoming "10". Where the full result set is in hand, carry the cut forward to the end of the section it lands in: every rendered section is then whole and its count is a total.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	props: [
		{
			name: 'data',
			type: 'T[]',
			description: 'The flat data to group.',
			required: true
		},
		{
			name: 'groupBy',
			type: '(item: T) => string',
			description: 'Derive the group key for a row. Rows with the same key share a section.',
			required: true
		},
		{
			name: 'collapsedGroups',
			type: 'Set<string>',
			description: 'Set of currently-collapsed group keys.',
			required: true
		},
		{
			name: 'onToggleGroup',
			type: '(groupKey: string) => void',
			description: 'Called with a group key when its header is toggled.',
			required: true
		},
		{
			name: 'renderGroupHeader',
			type: 'Snippet<[string, number, boolean]>',
			description:
				"Custom renderer for a group header's content (right of the chevron). Defaults to `<groupKey> (<count>)`."
		},
		{
			name: 'getRowKey',
			type: '(item: T) => string',
			description: 'Stable key for a real row. Falls back to a positional key when omitted.'
		},
		{
			name: 'groupOrder',
			type: 'string[]',
			description: 'Explicit group ordering; groups not listed keep first-seen order after these.'
		}
	]
};
