// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'InputGroupText',
	displayName: 'Input Group Text',
	subComponentOf: 'InputGroup',
	description:
		'A prefix or suffix text element rendered inside InputGroup. Displays text or icons.',
	keywords: ['inputgroup', 'addon', 'prefix', 'suffix', 'connected', 'grouped', 'input'],
	group: 'Field',
	category: 'Form Controls',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Text or icon content.',
			required: true
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description: 'StyleX styles for customization.'
		},
		{
			name: 'class',
			type: 'ClassValue | null',
			description: 'CSS class name(s).'
		},
		{
			name: 'style',
			type: 'string | null',
			description: 'Inline styles.'
		}
	]
};
