// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Slider',
	displayName: 'Slider',
	keywords: ['slider', 'range', 'slidebar', 'trackbar', 'scrubber', 'knob', 'thumb', 'rangeslider'],
	category: 'Form Controls',
	theming: {
		targets: [
			{
				className: 'astryx-slider',
				visualProps: ['orientation'],
				states: ['disabled']
			},
			{
				className: 'astryx-slider-track',
				visualProps: ['orientation']
			},
			{
				className: 'astryx-slider-thumb',
				visualProps: ['orientation'],
				states: ['disabled']
			}
		]
	},
	usage: {
		description:
			'A draggable control for selecting a numeric value or range within defined bounds. Supports single value and range selection, tick marks, custom value formatting, and vertical orientation. Use it when users need to explore a continuous range, such as volume, price, or percentage.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Always provide a label, even if visually hidden, so the slider is accessible to screen readers.'
			},
			{
				guidance: true,
				description:
					'Format values with meaningful units like "$50" or "75%" instead of raw numbers.'
			},
			{
				guidance: false,
				description:
					'Use for precise numeric entry; pair with a text input or use NumberInput instead.'
			},
			{
				guidance: false,
				description:
					'Set a step size so large that only a few positions are possible; use SegmentedControl or radio buttons instead.'
			},
			{
				guidance: false,
				description:
					'Wrap a disabled slider in Tooltip to explain why it is disabled; disabled controls swallow the hover events the wrapper needs. Use the disabledMessage prop instead.'
			}
		]
	},
	playground: {
		defaults: {
			label: 'Volume',
			value: 50,
			width: 300
		}
	},
	props: [
		{
			name: 'label',
			type: 'string',
			description: 'Label text (always rendered for accessibility).',
			required: true
		},
		{
			name: 'value',
			type: 'number | [number, number]',
			description:
				'Current value: a `number` for single thumb mode or `[number, number]` for range mode.',
			required: true
		},
		{
			name: 'onChange',
			type: '((value: number) => void) | ((value: [number, number]) => void)',
			description: 'Callback fired on value change during drag.'
		},
		{
			name: 'onChangeEnd',
			type: '((value: number) => void) | ((value: [number, number]) => void)',
			description: 'Callback fired when drag ends.'
		},
		{
			name: 'min',
			type: 'number',
			description: 'Minimum value.',
			default: '0'
		},
		{
			name: 'max',
			type: 'number',
			description: 'Maximum value.',
			default: '100'
		},
		{
			name: 'step',
			type: 'number',
			description: 'Step increment.',
			default: '1'
		},
		{
			name: 'orientation',
			type: "'horizontal' | 'vertical'",
			description: 'Orientation of the slider.',
			default: "'horizontal'"
		},
		{
			name: 'formatValue',
			type: '(value: number) => string',
			description: 'Custom value formatting function used for display and `aria-valuetext`.'
		},
		{
			name: 'valueDisplay',
			type: "'none' | 'tooltip' | 'text'",
			description: 'How the current value is displayed.',
			default: "'tooltip'"
		},
		{
			name: 'marks',
			type: '{ value: number; label?: string; }[]',
			description: 'Tick marks at specified positions with optional labels.'
		},
		{
			name: 'minStepsBetweenThumbs',
			type: 'number',
			description:
				'Minimum number of steps between thumbs in range mode; prevents thumbs from overlapping.',
			default: '0'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether the slider is disabled.',
			default: 'false'
		},
		{
			name: 'htmlName',
			type: 'string',
			description:
				'The HTML name attribute for form submissions. Renders hidden inputs carrying the current value (two entries in range mode).'
		},
		{
			name: 'disabledMessage',
			type: 'string',
			description:
				'Explains why the slider is disabled. With isDisabled, shows a tooltip on hover/keyboard focus and keeps the thumb focusable via aria-disabled (value changes stay blocked). Use this instead of wrapping a disabled Slider in Tooltip. Disabled controls swallow the hover events an external Tooltip needs.'
		},
		{
			name: 'isOptional',
			type: 'boolean',
			description: 'Whether the field is optional.',
			default: 'false'
		},
		{
			name: 'isRequired',
			type: 'boolean',
			description: 'Whether the field is required.',
			default: 'false'
		},
		{
			name: 'isLabelHidden',
			type: 'boolean',
			description: 'Whether to visually hide the label.',
			default: 'false'
		},
		{
			name: 'description',
			type: 'string',
			description: 'Description text rendered below the label.'
		},
		{
			name: 'status',
			type: 'InputStatus',
			description: 'Status indicator object (`{ type, message }`) for validation feedback.'
		},
		{
			name: 'labelTooltip',
			type: 'string',
			description: 'Tooltip text for an info icon displayed next to the label.'
		},
		{
			name: 'width',
			type: 'SizeValue',
			description:
				'Width of the field (number = pixels, string used as-is, e.g. "100%"). Sizes the whole field (label, control, and status) so they stay aligned.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
