// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Thumbnail',
	displayName: 'Thumbnail',
	keywords: [
		'thumbnail',
		'attachment',
		'preview',
		'image',
		'upload',
		'dismiss',
		'remove',
		'loading'
	],
	category: 'Content',
	theming: {
		targets: [
			{
				className: 'astryx-thumbnail'
			}
		],
		vars: [
			{
				name: '--_thumbnail-hit-inset',
				description:
					'Outset of the remove button’s invisible hit area, applied to a ::after overlay. 0 on a fine pointer; negative on a coarse one, which grows the 20px button to the 24px touch target without changing what is drawn.',
				default: '0px',
				private: true
			}
		]
	},
	usage: {
		description:
			'Thumbnail displays a compact, square preview of an image attachment. It shows a shimmer effect while uploading, the image on success, and a placeholder icon when no source is set. Use it in chat composers, file upload lists, or anywhere you need a small image preview with optional remove and click actions.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Always provide a label prop with the file name so the thumbnail and its remove button are accessible to screen readers and show a tooltip on hover.'
			},
			{
				guidance: true,
				description:
					'Use isLoading without a src to show a skeleton during initial upload, and isLoading with a src to show a spinner overlay once a preview URL is available.'
			},
			{
				guidance: true,
				description:
					'Pair onClick with a lightbox or detail view so users can inspect the full image; the thumbnail adds button semantics and a hover overlay automatically.'
			},
			{
				guidance: false,
				description:
					"Don't use Thumbnail for non-image file types like PDFs or spreadsheets; use a file attachment component with an appropriate icon instead."
			},
			{
				guidance: false,
				description:
					"Don't omit alt text when a src is provided; screen readers need a description of the image content, not just the file name from label."
			}
		],
		anatomy: [
			{
				name: 'Image',
				required: false,
				description: 'The preview image, displayed as a square with cover fit.'
			},
			{
				name: 'Placeholder',
				required: false,
				description: 'An image silhouette icon shown when no src is provided.'
			},
			{
				name: 'Remove button',
				required: false,
				description:
					'An overlaid close button in the top-right corner. Appears when onRemove is set. Sits on a fixed --color-overlay scrim with an --color-on-dark icon to stay visible on any image.'
			},
			{
				name: 'Upload overlay',
				required: false,
				description:
					'A semi-transparent overlay with a spinner, shown when isLoading is true and a src preview is available.'
			},
			{
				name: 'Skeleton',
				required: false,
				description: 'A shimmer animation shown when isLoading is true and no src is set.'
			}
		]
	},
	props: [
		{
			name: 'src',
			type: 'string',
			description: 'Image source URL.'
		},
		{
			name: 'alt',
			type: 'string',
			description:
				'Alt text for the image. When omitted, the image is explicitly decorative (alt="", role="presentation", aria-hidden) and hidden from screen readers; a dev warning fires if neither alt nor label is set.'
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label (e.g. file name). Shown as tooltip on hover.'
		},
		{
			name: 'onRemove',
			type: '(event: MouseEvent) => void',
			description: 'Callback for the overlaid remove button.'
		},
		{
			name: 'onclick',
			type: '(event: MouseEvent) => void',
			description: 'Click handler. Adds button semantics and a hover overlay.'
		},
		{
			name: 'isLoading',
			type: 'boolean',
			description: 'Shows skeleton (no src) or upload overlay (with src).',
			default: 'false'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether the thumbnail is disabled.',
			default: 'false'
		},
		{
			name: 'showRemoveOn',
			type: "'always' | 'hover'",
			description:
				'When the remove button is visible. `hover` (the default) reveals it on hover and on keyboard focus, and keeps it visible on any touch-capable device; `always` shows it at rest. Only applies when `onRemove` is set.',
			default: "'hover'"
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		},
		{
			name: 'class',
			type: 'ClassValue | null',
			description:
				'CSS class name for the root element. Prefer xstyle for styling; className is provided for integration with non-StyleX systems.'
		},
		{
			name: 'style',
			type: 'string | null',
			description:
				'Inline styles for the root element. Prefer xstyle for styling; inline styles bypass StyleX optimization.'
		},
		{
			name: 'data-testid',
			type: 'string',
			description: 'Test selector for automated testing frameworks.'
		}
	]
};
