// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Overlay',
	displayName: 'Overlay',
	keywords: ['overlay', 'scrim', 'media', 'hover', 'focus', 'image', 'card'],
	group: 'Overlay',
	category: 'Overlay',
	theming: {
		targets: [
			{
				className: 'astryx-overlay'
			},
			{
				className: 'astryx-overlay-scrim',
				visualProps: ['position']
			}
		]
	},
	usage: {
		description:
			'Overlay layers action or supporting content over media, cards, video, or other bounded surfaces with an optional scrim and reveal behavior.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use overlays for short, contextual actions or labels that belong directly to the underlying media or surface.'
			},
			{
				guidance: true,
				description:
					'Keep overlay content compact so it remains legible over the scrim and does not obscure important visual information.'
			},
			{
				guidance: false,
				description:
					'Do not use Overlay for floating content anchored outside the surface. Use Popover, Tooltip, or Dialog for those patterns.'
			}
		],
		anatomy: [
			{
				name: 'Base content',
				required: false,
				description: 'The media, card, or bounded surface that the overlay sits on top of.'
			},
			{
				name: 'Scrim',
				required: false,
				description: 'Optional dark or light overlay background that improves content contrast.'
			},
			{
				name: 'Overlay content',
				required: true,
				description: 'Actions, labels, or supporting content rendered above the base surface.'
			}
		]
	},
	props: [
		{
			name: 'content',
			type: 'Snippet',
			description: 'Content rendered inside the overlay scrim.',
			required: true
		},
		{
			name: 'children',
			type: 'Snippet',
			description:
				'Base content such as an image, video, card, or media surface that the overlay sits on top of.'
		},
		{
			name: 'showOn',
			type: "'always' | 'hover' | 'focus' | 'hover-or-focus'",
			description:
				'Visibility trigger. Hover mode also reveals on focus for keyboard accessibility; hover-or-focus is an alias for hover.',
			default: "'always'"
		},
		{
			name: 'isOpen',
			type: 'boolean',
			description:
				'Controlled visibility override. When set, this takes precedence over showOn and touch toggle behavior.'
		},
		{
			name: 'scrim',
			type: 'OverlayScrimMode',
			description:
				'Scrim background mode. Set to false to render overlay content without a scrim background.',
			default: "'dark'"
		},
		{
			name: 'position',
			type: "'top' | 'fill' | 'bottom'",
			description: 'Where the scrim appears within the base surface.',
			default: "'fill'"
		},
		{
			name: 'align',
			type: "'end' | 'start' | 'center'",
			description: 'Alignment of the overlay content within the scrim.',
			default: "'end'"
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		},
		{
			name: 'class',
			type: 'ClassValue | null',
			description:
				'CSS class name(s) appended to the root element. Prefer xstyle for styling when possible.'
		},
		{
			name: 'style',
			type: 'string | null',
			description:
				'Inline styles applied to the root element. Prefer xstyle for design-system styling.'
		},
		{
			name: 'ref',
			type: 'HTMLDivElement | null',
			description: 'Ref forwarded to the overlay root element.'
		}
	]
};
