// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'DropdownMenuCheckboxItem',
	displayName: 'Dropdown Menu Checkbox Item',
	subComponentOf: 'DropdownMenu',
	description:
		'A checkable menu item (role="menuitemcheckbox") that toggles an independent boolean. Use for on/off options inside a DropdownMenu; for a one-of-N choice use DropdownMenuRadioGroup.',
	keywords: [
		'dropdown',
		'menu',
		'popover',
		'select',
		'actions',
		'contextmenu',
		'overflow',
		'kebab',
		'menubutton'
	],
	group: 'DropdownMenu',
	category: 'Action',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Primary label text identifying the item.'
		},
		{
			name: 'description',
			type: 'string | Snippet',
			description: 'Secondary description text displayed below the label.'
		},
		{
			name: 'icon',
			type: 'Snippet | IconName',
			description:
				'Icon to display before the label. See `npx astryx docs icons` for valid semantic names.'
		},
		{
			name: 'value',
			type: 'boolean',
			description: 'Whether the item is checked. Controlled; pair with onChange.'
		},
		{
			name: 'onChange',
			type: '(checked: boolean) => void',
			description: 'Callback fired with the next checked state when the item is toggled.'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description:
				'Whether the item is disabled. Disabled items stay focusable (via aria-disabled) so they remain discoverable by keyboard and assistive technology, but activation is blocked.',
			default: 'false'
		},
		{
			name: 'hasCloseOnSelect',
			type: 'boolean',
			description:
				'Whether toggling the item closes the menu. Checkbox items default to staying open so several can be toggled in a single session.',
			default: 'false'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description:
				'Content to render after the label and description, such as a keyboard shortcut hint or badge.'
		}
	]
};
