// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'DropdownMenuRadioGroup',
	displayName: 'Dropdown Menu Radio Group',
	subComponentOf: 'DropdownMenu',
	description:
		'A single-select group of radio menu items (role="group" of menuitemradio). Owns the selected value and lays its items out with the menu\'s inter-item gap.',
	keywords: [
		'dropdown',
		'menu',
		'popover',
		'select',
		'actions',
		'contextmenu',
		'overflow',
		'kebab',
		'menubutton'
	],
	group: 'DropdownMenu',
	category: 'Action',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'value',
			type: 'string',
			description:
				'The currently selected value in the group. Pass undefined when nothing is selected yet.'
		},
		{
			name: 'onChange',
			type: '(value: string) => void',
			description: 'Callback fired when the selected value changes.'
		},
		{
			name: 'label',
			type: 'string',
			description:
				'Accessible name for the group, applied as aria-label so screen readers announce the radios as a named set, e.g. "Sort by". Required. Pass aria-labelledby (via base props) instead when the name already exists as a visible element.'
		},
		{
			name: 'hasCloseOnSelect',
			type: 'boolean',
			description:
				'Whether selecting a value closes the menu. Radio items default to closing on selection (a single-choice commit).',
			default: 'true'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'The DropdownMenuRadioItems that make up the group.'
		}
	]
};
