// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'DropdownMenuDivider',
	displayName: 'Dropdown Menu Divider',
	subComponentOf: 'DropdownMenu',
	description:
		'A horizontal rule separating groups of rows in a compound menu. Renders role="separator", so it is never a stop in the arrow-key order. The data-driven equivalent is the `{type: "divider"}` entry in `items`; both modes render this component, so they look and theme identically.',
	keywords: [
		'dropdown',
		'menu',
		'popover',
		'select',
		'actions',
		'contextmenu',
		'overflow',
		'kebab',
		'menubutton'
	],
	group: 'DropdownMenu',
	category: 'Action',
	isHiddenFromOverview: true,
	theming: {
		targets: [
			{
				className: 'astryx-dropdown-menu-divider'
			}
		]
	},
	props: [
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles applied after the menu spacing. Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
