// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'DropdownMenuItem',
	displayName: 'Dropdown Menu Item',
	subComponentOf: 'DropdownMenu',
	description: 'Helper component for custom item rendering with consistent styling.',
	keywords: [
		'dropdown',
		'menu',
		'popover',
		'select',
		'actions',
		'contextmenu',
		'overflow',
		'kebab',
		'menubutton'
	],
	group: 'DropdownMenu',
	category: 'Action',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			label: 'Edit',
			description: 'Modify this item'
		}
	},
	props: [
		{
			name: 'icon',
			type: 'Snippet | IconName',
			description:
				'Icon to display before the label. See `astryx docs icons` for valid semantic names.'
		},
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Primary label text.'
		},
		{
			name: 'description',
			type: 'string | Snippet',
			description: 'Secondary description text displayed below the label.'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Additional content rendered after the label and description.'
		},
		{
			name: 'hasCloseOnSelect',
			type: 'boolean',
			description:
				'Whether activating the item closes the menu. Set false for an action that reports its result on the item itself.',
			default: 'true'
		},
		{
			name: 'variant',
			type: "'destructive' | 'default'",
			description:
				"Visual variant. 'destructive' renders the label, description, and icon in the error color for dangerous actions (e.g. Delete).",
			default: "'default'"
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value: not an inline style object like style={{}}.'
		}
	]
};
