// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Layout',
	displayName: 'Layout',
	keywords: [
		'layout',
		'container',
		'content',
		'flex',
		'box',
		'wrapper',
		'scaffold',
		'page',
		'shell'
	],
	group: 'Layout',
	category: 'Layout',
	theming: {
		targets: [
			{
				className: 'astryx-layout',
				visualProps: ['height']
			},
			{
				className: 'astryx-layout-content'
			},
			{
				className: 'astryx-layout-footer'
			},
			{
				className: 'astryx-layout-header'
			},
			{
				className: 'astryx-layout-panel'
			}
		]
	},
	usage: {
		description:
			'Layout provides composable components for building structured page shells with header, sidebar, content, and footer slots. Use Layout for full app layouts and HStack/VStack for simple directional stacking.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use Layout for page shells that need distinct zones like header, sidebar(s), content, and footer.'
			},
			{
				guidance: true,
				description: 'Use HStack and VStack for simple directional stacking within a content area.'
			},
			{
				guidance: false,
				description: 'Use Layout for simple stacking layouts; use HStack or VStack instead.'
			},
			{
				guidance: false,
				description:
					'Nest multiple Layout components; use one per page shell and compose content within its slots.'
			}
		]
	},
	props: [
		{
			name: 'content',
			type: 'Snippet',
			description:
				'Main content area (center). Children passed to `<Layout>` render here too: `<Layout>{main}</Layout>` is shorthand for `<Layout content={main} />`.'
		},
		{
			name: 'header',
			type: 'Snippet',
			description: 'Header slot.'
		},
		{
			name: 'footer',
			type: 'Snippet',
			description: 'Footer slot.'
		},
		{
			name: 'start',
			type: 'Snippet',
			description: 'Start panel (left in LTR).'
		},
		{
			name: 'end',
			type: 'Snippet',
			description: 'End panel (right in LTR).'
		},
		{
			name: 'height',
			type: "'auto' | 'fill'",
			description: 'Height behavior: fill the container or grow with content.',
			default: "'fill'"
		}
	]
};
