// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'LayoutHeader',
	displayName: 'Layout Header',
	subComponentOf: 'Layout',
	description: 'Top bar for page titles, app bars, and toolbars.',
	keywords: [
		'layout',
		'container',
		'content',
		'flex',
		'box',
		'wrapper',
		'scaffold',
		'page',
		'shell'
	],
	group: 'Layout',
	category: 'Layout',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Header content.'
		},
		{
			name: 'hasDivider',
			type: 'boolean',
			description: 'Border at bottom edge.',
			default: 'false'
		},
		{
			name: 'height',
			type: 'SizeValue',
			description: 'Header height. Numbers are treated as pixels, strings are used as-is.'
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the landmark element.'
		},
		{
			name: 'role',
			type: 'AriaRole',
			description: 'ARIA landmark role.'
		}
	]
};
