// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'LayoutContent',
	displayName: 'Layout Content',
	subComponentOf: 'Layout',
	description: 'Scrollable main content area.',
	keywords: [
		'layout',
		'container',
		'content',
		'flex',
		'box',
		'wrapper',
		'scaffold',
		'page',
		'shell'
	],
	group: 'Layout',
	category: 'Layout',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Content.'
		},
		{
			name: 'padding',
			type: '0 | 6 | 2 | 4 | 0.5 | 1 | 1.5 | 3 | 5 | 8 | 10',
			description:
				'Internal padding using the spacing scale. Overrides the default padding from the layout container.'
		},
		{
			name: 'isScrollable',
			type: 'boolean',
			description: 'Enable scrollable overflow.',
			default: 'true'
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the landmark element.'
		},
		{
			name: 'role',
			type: 'AriaRole',
			description: 'ARIA landmark role.'
		}
	]
};
