// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Layout',
	displayName: 'Layout',
	keywords: ['layout', 'container', 'content', 'flex', 'box', 'wrapper', 'page', 'regions'],
	group: 'Layout',
	category: 'Layout',
	theming: {
		targets: [
			{
				className: 'astryx-layout',
				visualProps: ['height']
			},
			{
				className: 'astryx-layout-content'
			},
			{
				className: 'astryx-layout-footer'
			},
			{
				className: 'astryx-layout-header'
			},
			{
				className: 'astryx-layout-panel'
			}
		]
	},
	usage: {
		description:
			'Layout is a general five-slot primitive for arranging header, start, content, end, and footer regions within a page or bounded container. AppShell owns the page shell and app-wide navigation behavior; use HStack or VStack for simple directional stacking.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use Layout when content needs named header, start, content, end, or footer regions.'
			},
			{
				guidance: true,
				description: 'Use HStack and VStack for simple directional stacking within a content area.'
			},
			{
				guidance: false,
				description: 'Use Layout for simple stacking layouts; use HStack or VStack instead.'
			},
			{
				guidance: false,
				description:
					'Use Layout as the page shell or for app-wide navigation; use AppShell for that responsibility.'
			}
		],
		anatomy: [
			{
				name: 'Layout container',
				required: true,
				description:
					'General layout primitive that places the header, start, content, end, and footer slots.'
			},
			{
				name: 'Header',
				required: false,
				description:
					'Optional LayoutHeader region supplied by the caller, typically in the header slot.'
			},
			{
				name: 'Panel',
				required: false,
				description: 'Optional LayoutPanel region supplied by the caller in the start or end slot.'
			},
			{
				name: 'Content area',
				required: false,
				description: 'Optional LayoutContent region supplied by the caller in the content slot.'
			},
			{
				name: 'Footer',
				required: false,
				description:
					'Optional LayoutFooter region supplied by the caller, typically in the footer slot.'
			}
		]
	},
	props: [
		{
			name: 'content',
			type: 'Snippet',
			description:
				'Content slot (center). Accepts any ReactNode; use LayoutContent when a content region is needed. Children passed to `<Layout>` render here too: `<Layout>{main}</Layout>` is shorthand for `<Layout content={main} />`.'
		},
		{
			name: 'header',
			type: 'Snippet',
			description:
				'Header slot. Accepts any ReactNode; use LayoutHeader when a header region is needed.'
		},
		{
			name: 'footer',
			type: 'Snippet',
			description:
				'Footer slot. Accepts any ReactNode; use LayoutFooter when a footer region is needed.'
		},
		{
			name: 'start',
			type: 'Snippet',
			description:
				'Logical-start slot (left in LTR). Accepts any ReactNode; use LayoutPanel when a panel region is needed.'
		},
		{
			name: 'end',
			type: 'Snippet',
			description:
				'Logical-end slot (right in LTR). Accepts any ReactNode; use LayoutPanel when a panel region is needed.'
		},
		{
			name: 'height',
			type: "'auto' | 'fill'",
			description: 'Height behavior: fill the container or grow with content.',
			default: "'fill'"
		},
		{
			name: 'contentWidth',
			type: 'SizeValue',
			description:
				'Maximum width of the aligned content within each slot (header, content, footer, panels), centered when narrower than the available space. Without panels, LayoutContent spans the available width so its scrollbar stays at the outer edge while its children align internally to contentWidth. With exactly one panel, the panel stays aligned to the contentWidth frame while LayoutContent extends to the opposite open edge. With both panels, contentWidth includes the complete middle composition. Percentage widths—including percentage-bearing calc(), min(), max(), and clamp() values—and intrinsic widths, plus bare var(...) values, retain the constrained composition; use calc(var(...)) for a variable guaranteed to resolve to a length. Dividers stay full-bleed. Numbers are treated as pixels, strings are used as-is (e.g. `60ch`). Common page widths: 640 for forms, settings, and text-focused pages; 960 for content pages and wider layouts.'
		},
		{
			name: 'padding',
			type: '0 | 6 | 2 | 4 | 0.5 | 1 | 1.5 | 3 | 5 | 8 | 10',
			description: "Padding at the layout's outer edges using the spacing scale."
		},
		{
			name: 'defaultHasDividers',
			type: 'boolean',
			description:
				"Default divider visibility for LayoutHeader and LayoutFooter children. Headers and footers that don't pass `hasDivider` use this value; when unset, nested layouts inherit from their parent context."
		}
	]
};
