// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'LayoutHeader',
	displayName: 'Layout Header',
	subComponentOf: 'Layout',
	description: 'Top bar for page titles, app bars, and toolbars.',
	keywords: ['layout', 'container', 'content', 'flex', 'box', 'wrapper', 'page', 'regions'],
	group: 'Layout',
	category: 'Layout',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			children: 'Page Title',
			hasDivider: true
		},
		wrapper: {
			component: 'Layout'
		}
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Header content.'
		},
		{
			name: 'hasDivider',
			type: 'boolean',
			description: 'Border at bottom edge.',
			default: 'false'
		},
		{
			name: 'height',
			type: 'SizeValue',
			description: 'Header height. Numbers are treated as pixels, strings are used as-is.'
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the landmark element.'
		},
		{
			name: 'paddingBlockEnd',
			type: '0 | 0.5 | 1 | 1.5 | 2 | 3 | 4 | 5 | 6 | 8 | 10',
			description:
				'Block-end (bottom) padding, using the spacing scale. Overrides padding on that edge only; paddingBlockEnd={0} docks the last child on the header bottom edge.'
		},
		{
			name: 'role',
			type: 'AriaRole',
			description: 'ARIA landmark role.'
		}
	]
};
