// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'NumberInput',
	displayName: 'Number Input',
	keywords: [
		'numberinput',
		'numberfield',
		'stepper',
		'spinner',
		'counter',
		'increment',
		'decrement',
		'quantity',
		'numberpicker'
	],
	category: 'Data Input',
	theming: {
		targets: [
			{
				className: 'astryx-number-input',
				visualProps: ['size', 'status']
			}
		]
	},
	usage: {
		description:
			'A form input for numeric values with built-in validation, min/max constraints, and step controls. Use NumberInput for quantities, measurements, percentages, and similar inputs.',
		bestPractices: [
			{
				guidance: true,
				description: 'Set min, max, and step to guide users toward valid values.'
			},
			{
				guidance: true,
				description: 'Show units (e.g. "%" or "GB") so users know what the number represents.'
			},
			{
				guidance: false,
				description:
					'Use NumberInput for free-form text that happens to contain numbers; use TextInput instead.'
			},
			{
				guidance: false,
				description: 'Set both isOptional and isRequired on the same field.'
			},
			{
				guidance: false,
				description:
					"Wrap a disabled NumberInput in Tooltip to explain why it's disabled; disabled controls swallow the hover events the wrapper needs. Use the disabledMessage prop instead."
			}
		],
		anatomy: [
			{
				name: 'Label',
				required: true,
				description: 'The label for the number input.'
			},
			{
				name: 'Description',
				required: false,
				description: 'Additional description text below the label.'
			},
			{
				name: 'Icon',
				required: false,
				description: 'An optional icon within the input.'
			},
			{
				name: 'Placeholder',
				required: false,
				description: 'Placeholder text shown when the input is empty.'
			}
		]
	},
	props: [
		{
			name: 'label',
			type: 'string',
			description: 'Label text for the input (always rendered for accessibility).',
			required: true
		},
		{
			name: 'value',
			type: 'number | null',
			description: 'Current value of the input.',
			required: true
		},
		{
			name: 'onChange',
			type: '((value: number) => void) | ((value: number | null) => void)',
			description: 'Callback fired when input value changes (only on valid input).',
			required: true
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description: 'Size variant.',
			default: "'md'"
		},
		{
			name: 'isLabelHidden',
			type: 'boolean',
			description: 'Visually hide the label (still accessible to screen readers).'
		},
		{
			name: 'description',
			type: 'string',
			description: 'Description text displayed between the label and input.'
		},
		{
			name: 'isOptional',
			type: 'boolean',
			description: 'Whether the field is optional (mutually exclusive with isRequired).'
		},
		{
			name: 'isRequired',
			type: 'boolean',
			description: 'Whether the field is required (mutually exclusive with isOptional).'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether the input is disabled.'
		},
		{
			name: 'disabledMessage',
			type: 'string',
			description:
				'Explains why the input is disabled. With isDisabled, shows a tooltip on hover/keyboard focus and keeps the input focusable via aria-disabled (the field becomes read-only). Use this instead of wrapping a disabled NumberInput in Tooltip.'
		},
		{
			name: 'placeholder',
			type: 'string',
			description: 'Placeholder text.'
		},
		{
			name: 'labelTooltip',
			type: 'string',
			description: 'Tooltip text to display in an info icon at the end of the label.'
		},
		{
			name: 'startIcon',
			type: 'Snippet',
			description:
				'Icon to display at the start of the input. See `astryx docs icons` for valid semantic names.'
		},
		{
			name: 'labelIcon',
			type: 'Snippet',
			description:
				'Icon to display before the label text. See `astryx docs icons` for valid semantic names.'
		},
		{
			name: 'status',
			type: 'InputStatus',
			description: 'Validation status with optional message.'
		},
		{
			name: 'statusVariant',
			type: "'tooltip' | 'attached' | 'detached'",
			description:
				'How the status message is placed relative to the input. attached overlaps directly below the input (bordered treatment); detached floats below as a separate element with spacing; tooltip hides the message box and surfaces it in a tooltip on the status icon.',
			default: "'attached'"
		},
		{
			name: 'min',
			type: 'number | null',
			description: 'Minimum value allowed.'
		},
		{
			name: 'max',
			type: 'number | null',
			description: 'Maximum value allowed.'
		},
		{
			name: 'step',
			type: 'number | null',
			description: 'Step increment for the input.',
			default: '1'
		},
		{
			name: 'units',
			type: 'string | null',
			description: 'Units text to display at the end of the input (e.g., "%" or "GB").'
		},
		{
			name: 'isIntegerOnly',
			type: 'boolean',
			description: 'Only allow integer values (no floating point).'
		},
		{
			name: 'hasClear',
			type: 'boolean',
			description:
				'Shows a clear (×) button when the input has a value. When true, the onChange callback also accepts null to signal the user cleared the input.',
			default: 'false'
		},
		{
			name: 'htmlName',
			type: 'string',
			description: 'HTML name attribute for form submissions.'
		},
		{
			name: 'autoComplete',
			type: 'string',
			description: 'HTML autocomplete attribute.'
		},
		{
			name: 'width',
			type: 'SizeValue',
			description:
				'Width of the field (number = pixels, string used as-is, e.g. "100%"). Sizes the whole field (label, control, and status) so they stay aligned.'
		},
		{
			name: 'hasAutoFocus',
			type: 'boolean',
			description: 'Whether to focus the input on mount.'
		},
		{
			name: 'onfocus',
			type: 'FocusEventHandler<HTMLInputElement>',
			description: 'Callback fired when the input receives focus.'
		},
		{
			name: 'onblur',
			type: 'FocusEventHandler<HTMLInputElement>',
			description: 'Callback fired when the input loses focus.'
		},
		{
			name: 'onEnter',
			type: '() => void',
			description: 'Callback fired when the user presses the Enter key.'
		}
	]
};
