// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'RadioListItem',
	displayName: 'Radio List Item',
	subComponentOf: 'RadioList',
	description: 'Individual radio item with label, description, and content slots.',
	keywords: [
		'radiolist',
		'radio',
		'radiogroup',
		'radiobutton',
		'optionlist',
		'singlechoice',
		'choicelist'
	],
	group: 'Radio',
	category: 'Form Controls',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			value: 'option-1',
			label: 'Option'
		},
		wrapper: {
			component: 'RadioList',
			props: {
				value: 'option-1',
				label: 'Radio list'
			}
		}
	},
	props: [
		{
			name: 'label',
			type: 'string',
			description: 'Label text for the radio item.',
			required: true
		},
		{
			name: 'value',
			type: 'string',
			description: 'Value of this radio item.',
			required: true
		},
		{
			name: 'description',
			type: 'string',
			description: 'Description text displayed below the label.'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether this individual radio item is disabled.',
			default: 'false'
		},
		{
			name: 'startContent',
			type: 'Snippet',
			description: 'Content to render before the radio circle.'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Content to render after the label.'
		}
	]
};
