// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'RadioListItem',
	displayName: 'Radio List Item',
	subComponentOf: 'RadioList',
	description: 'Individual radio item with label, description, and content slots.',
	keywords: [
		'radiolist',
		'radio',
		'radiogroup',
		'radiobutton',
		'optionlist',
		'singlechoice',
		'choicelist'
	],
	group: 'Radio',
	category: 'Form Controls',
	isHiddenFromOverview: true,
	playground: {
		defaults: {
			value: 'option-1',
			label: 'Option'
		},
		wrapper: {
			component: 'RadioList',
			props: {
				value: 'option-1',
				label: 'Radio list'
			}
		}
	},
	props: [
		{
			name: 'label',
			type: 'string',
			description:
				'Primary label for the radio item. Rich labels may contain links or buttons, which keep their own behavior without selecting the item. The label text names the radio; use aria-label only when that text is absent, or retain every visible label word in the override.',
			required: true
		},
		{
			name: 'aria-label',
			type: 'string | null',
			description:
				'Plain-text accessible name for the radio, applied to the control rather than the row. It overrides the name derived from the label. Use it when a rich label has no visible text; otherwise retain every visible label word.'
		},
		{
			name: 'value',
			type: 'string',
			description: 'Value of this radio item.',
			required: true
		},
		{
			name: 'description',
			type: 'string',
			description:
				'Secondary content displayed below the label. Links and buttons keep their own click behaviour — the row only delegates clicks from its non-interactive surface to the radio.'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether this individual radio item is disabled.',
			default: 'false'
		},
		{
			name: 'startContent',
			type: 'Snippet',
			description: 'Content to render before the radio circle.'
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Content to render after the label.'
		}
	]
};
