// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'useTablePagination',
	displayName: 'useTablePagination',
	subComponentOf: 'Table',
	description:
		'Headless pagination plugin for Table. Call with a config object: `useTablePagination({ page, onPageChange, totalItems })`. Returns a TablePlugin to pass to `<Table plugins={{ pagination: paginationPlugin }} />`.',
	keywords: [
		'table',
		'datatable',
		'datagrid',
		'spreadsheet',
		'sorting',
		'virtualized',
		'columns',
		'rows',
		'selection',
		'pinning'
	],
	group: 'Table',
	category: 'Table & List',
	usage: {
		description:
			'Call useTablePagination with a config object containing page state and callback. Pass the returned plugin to Table via the plugins prop.'
	},
	props: [
		{
			name: 'page',
			type: 'number',
			description: 'Current page number (1-based).',
			required: true
		},
		{
			name: 'onPageChange',
			type: '(page: number) => void',
			description: 'Called when the page changes.',
			required: true
		},
		{
			name: 'totalItems',
			type: 'number',
			description: 'Total number of items across all pages. Used to calculate total page count.'
		},
		{
			name: 'totalPages',
			type: 'number',
			description: 'Total number of pages. Use when you know the page count but not item count.'
		},
		{
			name: 'hasMore',
			type: 'boolean',
			description:
				'Whether more pages exist. Use for cursor-based pagination where the total is unknown.'
		},
		{
			name: 'pageSize',
			type: 'number',
			description: 'Number of items per page.',
			default: '10'
		},
		{
			name: 'onPageSizeChange',
			type: '(pageSize: number) => void',
			description:
				'Called when the user changes the page size. Shows a page size dropdown when provided with pageSizeOptions.'
		},
		{
			name: 'pageSizeOptions',
			type: 'number[]',
			description: 'Available page size options. Shows a page size selector when provided.'
		},
		{
			name: 'variant',
			type: "'none' | 'compact' | 'count' | 'pages' | 'dots'",
			description: 'Visual variant for the pagination controls.',
			default: "'pages'"
		},
		{
			name: 'position',
			type: "'none' | 'below' | 'above' | 'both'",
			description: 'Where to render pagination controls relative to the table.',
			default: "'below'"
		},
		{
			name: 'align',
			type: "'end' | 'start' | 'center'",
			description: 'Horizontal alignment of the pagination controls.',
			default: "'center'"
		},
		{
			name: 'label',
			type: 'string',
			description:
				"Accessible name for the pagination nav landmark. With position='both' the two navs get distinct names (the label suffixed as '(top)' and '(bottom)') so same-type landmarks stay unique (axe landmark-unique).",
			default: "'Table pagination'"
		}
	]
};
