// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'SelectorOption',
	displayName: 'Selector Option',
	subComponentOf: 'Selector',
	description: 'Helper component for custom item rendering inside an Selector renderOption prop.',
	keywords: [
		'selector',
		'select',
		'dropdown',
		'combobox',
		'picker',
		'listbox',
		'chooser',
		'autocomplete',
		'option',
		'selectmenu'
	],
	group: 'Selector',
	category: 'Form Controls',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'label',
			type: 'string | Snippet',
			description: 'Primary label text for the item.',
			required: true
		},
		{
			name: 'icon',
			type: 'IconName | Snippet',
			description:
				'Icon displayed before the label. See `astryx docs icons` for valid semantic names.'
		},
		{
			name: 'description',
			type: 'string | Snippet',
			description: 'Secondary description text displayed below the label.'
		},
		{
			name: 'layout',
			type: "'inline' | 'stacked'",
			description:
				"How the label and description sit together. 'stacked' puts the description on its own line; 'inline' keeps both on one line so the row fits a fixed-height host. Inside a Selector trigger the trigger's padding sizes itself to whichever layout you pick, so both land on the 4px rhythm; an InputGroup pins the row height and forces 'inline'.",
			default: "'stacked'"
		},
		{
			name: 'endContent',
			type: 'Snippet',
			description: 'Additional content rendered after the label and description.'
		}
	]
};
