// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'Popover',
	displayName: 'Popover',
	keywords: [
		'popover',
		'popup',
		'dropdown',
		'tooltip',
		'overlay',
		'flyout',
		'callout',
		'popper',
		'anchor',
		'floating',
		'bubble'
	],
	group: 'Popover',
	category: 'Overlay',
	theming: {
		targets: [
			{
				className: 'astryx-popover'
			},
			{
				className: 'astryx-popover-surface'
			}
		],
		vars: [
			{
				name: '--_popover-radius',
				description: 'Border radius of the popover',
				default: 'var(--radius-element)',
				private: true
			}
		],
		derived: [
			{
				property: 'borderRadius',
				vars: ['--_popover-radius']
			}
		]
	},
	usage: {
		description:
			'A click-triggered overlay anchored to a button or trigger element. Use it for secondary actions, inline confirmations, or supplementary information that does not warrant a full dialog. For hover previews use HoverCard, for brief helper text use Tooltip.',
		bestPractices: [
			{
				guidance: true,
				description: 'Keep popover content focused on a single task or piece of information.'
			},
			{
				guidance: true,
				description:
					'Provide a clear way to close: either by clicking outside or with an explicit close button.'
			},
			{
				guidance: false,
				description:
					'Nest popovers inside other popovers; it creates confusing focus and navigation.'
			},
			{
				guidance: false,
				description:
					'Use a popover for content that requires heavy user input; use a Dialog instead.'
			},
			{
				guidance: false,
				description:
					'Put too much content in a popover; if it needs scrolling, use a Dialog instead.'
			}
		],
		anatomy: [
			{
				name: 'Header',
				required: true,
				description: 'Contains the title, optional subheader, and close button.'
			},
			{
				name: 'Body',
				required: true,
				description: 'Main content area of the popover.'
			},
			{
				name: 'Trigger Element',
				required: true,
				description: 'The button or link that toggles the popover open.'
			}
		]
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Trigger element. Must contain a <button> or [role="button"] element.'
		},
		{
			name: 'anchorRef',
			type: 'HTMLElement | null',
			description: 'External ref to use as the popover anchor in sibling mode.'
		},
		{
			name: 'content',
			type: 'Snippet',
			description: 'Content to display inside the popover.',
			required: true
		},
		{
			name: 'placement',
			type: "'below' | 'above' | 'end' | 'start'",
			description:
				"Position placement relative to the trigger. Logical: start/end resolve against the popover's own inherited direction, so RTL contexts mirror automatically in pure CSS.",
			default: "'below'"
		},
		{
			name: 'alignment',
			type: "'end' | 'start' | 'center'",
			description:
				"Alignment along the placement axis. Logical: start/end follow the popover's own inherited direction (RTL mirrors).",
			default: "'start'"
		},
		{
			name: 'isOpen',
			type: 'boolean',
			description: 'Whether the popover is shown in controlled mode.'
		},
		{
			name: 'onOpenChange',
			type: '(isOpen: boolean) => void',
			description: 'Callback fired when the popover visibility changes.'
		},
		{
			name: 'isEnabled',
			type: 'boolean',
			description: 'When false, trigger interactions are ignored.',
			default: 'true'
		},
		{
			name: 'width',
			type: 'number | string',
			description: 'Width of the popover container.',
			default: "'auto'"
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the popover dialog.'
		},
		{
			name: 'role',
			type: "'none' | 'dialog'",
			description:
				'ARIA role for the popover wrapper. Use dialog for dialog-style popovers; use none when content provides its own role, like menu or listbox.',
			default: "'dialog'"
		},
		{
			name: 'isModal',
			type: 'boolean',
			description:
				'Whether a dialog-style popover sets aria-modal. Only applies when role is dialog.',
			default: 'true'
		},
		{
			name: 'hasCloseButton',
			type: 'boolean',
			description: 'Whether to include a hidden close button for accessibility.',
			default: 'true'
		},
		{
			name: 'closeButtonLabel',
			type: 'string',
			description: 'Label for the hidden close button.',
			default: "'Close popover'"
		},
		{
			name: 'hasAutoFocus',
			type: 'boolean',
			description:
				'Whether to auto-focus the first focusable element when the popover opens. Set to false for inline showcases or documentation previews.',
			default: 'true'
		},
		{
			name: 'hasLightDismiss',
			type: 'boolean',
			description:
				'Whether clicking outside dismisses the popover. Set to false for surfaces that stay open until explicitly dismissed, like onboarding coachmarks.',
			default: 'true'
		},
		{
			name: 'hasEscapeDismiss',
			type: 'boolean',
			description:
				'Whether pressing Escape dismisses the popover. Only takes full effect together with hasLightDismiss={false}, since native light dismiss also closes on Escape.',
			default: 'true'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
