// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'TopNavItem',
	displayName: 'Top Nav Item',
	subComponentOf: 'TopNav',
	description:
		'Navigation link item for use in TopNav startContent: renders as an anchor with hover and selected states.',
	keywords: ['topnav', 'navbar', 'appbar', 'header', 'toolbar', 'navigation', 'menubar', 'topbar'],
	group: 'Navigation',
	category: 'Navigation',
	isHiddenFromOverview: true,
	props: [
		{
			name: 'label',
			type: 'string',
			description:
				'Accessible label for the nav item. Rendered as visible text by default. When isIconOnly is true, used as aria-label instead.',
			required: true
		},
		{
			name: 'href',
			type: 'string',
			description: 'Navigation target URL.'
		},
		{
			name: 'isSelected',
			type: 'boolean',
			description:
				'Whether this nav item is currently selected. Sets aria-current="page" and applies highlighted styles.',
			default: 'false'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description:
				'Whether the nav item is disabled. Sets aria-disabled, drops href/target so the item cannot navigate, and prevents interaction.',
			default: 'false'
		},
		{
			name: 'isIconOnly',
			type: 'boolean',
			description:
				'Renders the item as a square icon-only element. When true, label becomes the aria-label and visible text is hidden. Requires icon to be set.',
			default: 'false'
		},
		{
			name: 'icon',
			type: 'Snippet',
			description: 'Optional icon to display before the label.'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Custom content to render instead of the label text.'
		},
		{
			name: 'as',
			type: 'LinkComponentType',
			description:
				'Custom component to render instead of <a>. Overrides the provider-level default set by LinkProvider. Must accept href, className, style, and children props.'
		}
	]
};
