// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'TopNavMenu',
	displayName: 'Top Nav Menu',
	subComponentOf: 'TopNav',
	description:
		'Navigation item that displays a hover-triggered popover menu with rich items containing an icon, title, and optional description.',
	keywords: ['topnav', 'navbar', 'appbar', 'header', 'toolbar', 'navigation', 'menubar', 'topbar'],
	group: 'Navigation',
	category: 'Navigation',
	props: [
		{
			name: 'label',
			type: 'string',
			description: 'Visible label for the trigger button.',
			required: true
		},
		{
			name: 'items',
			type: 'TopNavMenuItemData[]',
			description: 'Menu items to display in the hover popover.',
			required: true
		},
		{
			name: 'delay',
			type: 'number',
			description: 'Delay in milliseconds before showing the menu on hover.',
			default: '150'
		},
		{
			name: 'hideDelay',
			type: 'number',
			description: 'Delay in milliseconds before hiding the menu after the mouse leaves.',
			default: '200'
		}
	]
};
