// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'NavHeadingMenu',
	displayName: 'Nav Heading Menu',
	keywords: ['nav', 'menu', 'navigation', 'heading', 'menu-item', 'popover'],
	group: 'Navigation',
	category: 'Navigation',
	isHiddenFromOverview: true,
	theming: {
		targets: [
			{
				className: 'astryx-nav-heading-menu',
				visualProps: ['size']
			},
			{
				className: 'astryx-nav-heading-menu-item',
				visualProps: ['size']
			}
		]
	},
	usage: {
		description:
			'Accessible menu container and items for nav heading popovers. NavHeadingMenu provides role="menu" with keyboard navigation; NavHeadingMenuItem renders individual selectable items. Pass as the menu prop of SideNavHeading or TopNavHeading.'
	},
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Menu items.',
			required: true
		},
		{
			name: 'size',
			type: "'sm' | 'md' | 'lg'",
			description: 'Controls min-width and item padding.',
			default: "'md'"
		},
		{
			name: 'minWidth',
			type: 'SizeValue',
			description: 'Minimum width override.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
