// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'BaseTypeahead',
	displayName: 'Base Typeahead',
	subComponentOf: 'Typeahead',
	description:
		'Unstyled combobox engine providing input, search, keyboard navigation, and dropdown. No wrapper div, no border styling, no token rendering. Used by Typeahead and Tokenizer for custom compositions.',
	keywords: [
		'typeahead',
		'autocomplete',
		'combobox',
		'searchbox',
		'autosuggest',
		'select',
		'dropdown',
		'lookup',
		'searchable',
		'suggestion',
		'picker'
	],
	group: 'Typeahead',
	category: 'Data Input',
	isHiddenFromOverview: true,
	usage: {
		description:
			'Unstyled combobox engine providing input, search, keyboard navigation, and dropdown. No wrapper div, no border styling, no token rendering. Used by Typeahead and Tokenizer for custom compositions.',
		bestPractices: [
			{
				guidance: true,
				description:
					'Use Typeahead or Tokenizer for standard fields; they wrap BaseTypeahead with the wrapper div, border styling, and token rendering it intentionally omits.'
			},
			{
				guidance: true,
				description:
					'Provide your own wrapper div with border and layout when composing directly, since BaseTypeahead renders no visual chrome of its own.'
			},
			{
				guidance: true,
				description:
					'Pass anchorRef pointing to your wrapper so the dropdown positions against your custom input chrome, not just the bare input element.'
			},
			{
				guidance: false,
				description:
					"Expect a wrapper div, border, or token rendering. BaseTypeahead is an engine only; all visual chrome is the caller's responsibility."
			},
			{
				guidance: false,
				description:
					'Use BaseTypeahead when Typeahead or Tokenizer would suffice; the extra wrapper and styling work is only justified for truly custom compositions.'
			}
		]
	},
	props: [
		{
			name: 'searchSource',
			type: 'SearchSource<T>',
			description: 'Data source providing search and bootstrap methods.',
			required: true
		},
		{
			name: 'value',
			type: 'T | null',
			description: 'Currently selected item.',
			required: true
		},
		{
			name: 'onChange',
			type: '(item: T | null) => void',
			description: 'Called when the selection changes.',
			required: true
		},
		{
			name: 'renderItem',
			type: 'Snippet<[T]>',
			description: 'Custom render function for dropdown items.'
		},
		{
			name: 'placeholder',
			type: 'string',
			description: 'Input placeholder text.',
			default: "'Search...'"
		},
		{
			name: 'hasEntriesOnFocus',
			type: 'boolean',
			description: 'Show bootstrap results on focus before typing.',
			default: 'false'
		},
		{
			name: 'maxMenuItems',
			type: 'number',
			description: 'Maximum dropdown items to display.',
			default: '10'
		},
		{
			name: 'emptySearchResultsText',
			type: 'string',
			description: 'Text shown when search returns no results.',
			default: "'No results found'"
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether the input is disabled.',
			default: 'false'
		},
		{
			name: 'hasAutoFocus',
			type: 'boolean',
			description: 'Auto-focus the input on mount.',
			default: 'false'
		},
		{
			name: 'debounceMs',
			type: 'number',
			description:
				'Debounce delay in ms before triggering search. Set to 0 for synchronous sources.',
			default: '150'
		},
		{
			name: 'anchorRef',
			type: 'HTMLElement | null',
			description:
				'Ref to the anchor element for dropdown positioning. If not provided, the input itself is used.'
		},
		{
			name: 'inputXStyle',
			type: 'StyleArg',
			description: 'Additional StyleX styles for the input element.'
		},
		{
			name: 'onKeyDown',
			type: '(e: KeyboardEvent) => void',
			description:
				'Additional keydown handler called before internal keyboard navigation. Call e.preventDefault() to skip internal handling.'
		},
		{
			name: 'onChangeQuery',
			type: '(query: string) => void',
			description: 'Callback fired when the search query text changes.'
		},
		{
			name: 'onOpenChange',
			type: '(isOpen: boolean) => void',
			description: 'Callback when the dropdown opens or closes.'
		},
		{
			name: 'inputId',
			type: 'string',
			description: 'ID for the input element (for label association).'
		},
		{
			name: 'ariaDescribedBy',
			type: 'string',
			description: 'Additional aria-describedby IDs.'
		}
	]
};
