// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'TypeaheadItem',
	displayName: 'Typeahead Item',
	subComponentOf: 'Typeahead',
	description:
		'Default dropdown item renderer for typeahead results. Shows label with optional icon, description, and avatar. Exported for use in custom renderItem implementations.',
	keywords: [
		'typeahead',
		'autocomplete',
		'combobox',
		'searchbox',
		'autosuggest',
		'select',
		'dropdown',
		'lookup',
		'searchable',
		'suggestion',
		'picker'
	],
	group: 'Typeahead',
	category: 'Form Controls',
	props: [
		{
			name: 'item',
			type: 'T',
			description: 'The search result item to render.',
			required: true
		},
		{
			name: 'icon',
			type: 'Snippet',
			description: 'Icon or avatar to display before the label.'
		},
		{
			name: 'description',
			type: 'string',
			description: 'Description text displayed below the label.'
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Whether this item is visually disabled.',
			default: 'false'
		},
		{
			name: 'group',
			type: 'string',
			description: 'Group label for grouping items visually.'
		}
	]
};
