// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'ClickableCard',
	displayName: 'Clickable Card',
	keywords: ['card', 'clickable', 'interactive', 'navigation', 'action', 'link'],
	group: 'Card',
	category: 'Container',
	theming: {
		container: true,
		targets: [
			{
				className: 'astryx-clickable-card',
				visualProps: ['variant']
			}
		]
	},
	usage: {
		description:
			'An interactive card for navigation or action targets. Nested interactive elements work independently.',
		bestPractices: [
			{
				guidance: true,
				description: 'Use for cards that navigate to a detail page or trigger a single action.'
			},
			{
				guidance: true,
				description: 'Nest buttons or links freely inside; they handle their own events.'
			},
			{
				guidance: false,
				description: 'Use for toggling selection; use SelectableCard for that.'
			}
		],
		anatomy: [
			{
				name: 'Container',
				required: true,
				description: 'Interactive div with hover/focus/active states.'
			},
			{
				name: 'Content',
				required: true,
				description: 'Children, which may include nested interactive elements.'
			}
		]
	},
	playground: {
		defaults: {
			label: 'View product details',
			href: '#',
			padding: 4
		}
	},
	props: [
		{
			name: 'label',
			type: 'string',
			description: 'Accessibility label.',
			required: true
		},
		{
			name: 'onclick',
			type: '(event: MouseEvent) => void',
			description: 'Click handler: fires on card surface only.'
		},
		{
			name: 'href',
			type: 'string',
			description: 'Navigation URL.'
		},
		{
			name: 'target',
			type: 'string',
			description: 'Link target.',
			default: "'_self'"
		},
		{
			name: 'isDisabled',
			type: 'boolean',
			description: 'Disables the card.',
			default: 'false'
		},
		{
			name: 'children',
			type: 'Snippet',
			description: 'Card content.'
		},
		{
			name: 'padding',
			type: '0 | 6 | 2 | 4 | 0.5 | 1 | 1.5 | 3 | 5 | 8 | 10',
			description: 'Inner padding.',
			default: '4'
		},
		{
			name: 'variant',
			type: "'blue' | 'cyan' | 'green' | 'orange' | 'pink' | 'purple' | 'red' | 'teal' | 'yellow' | 'default' | 'transparent' | 'muted' | 'gray'",
			description: 'Background color variant.',
			default: "'default'"
		},
		{
			name: 'elevation',
			type: "'none' | 'low' | 'med' | 'high'",
			description: 'Resting shadow depth. Often raised to signal the whole card is clickable.',
			default: "'none'"
		},
		{
			name: 'width',
			type: 'SizeValue',
			description: 'Card width.'
		},
		{
			name: 'height',
			type: 'SizeValue',
			description: 'Card height.'
		},
		{
			name: 'maxWidth',
			type: 'SizeValue',
			description: 'Maximum card width.'
		},
		{
			name: 'xstyle',
			type: 'StyleArg',
			description:
				'StyleX styles for layout customization (margins, positioning, sizing). Must be a stylex.create() value, not an inline style object like style={{}}.'
		}
	]
};
