// @generated by docs/scripts/emit-core-docs.mjs — do not edit.
//
// Prose is upstream's, verbatim. Every `type` is read from this package's own
// compiled declarations rather than upstream's React ones, which is why this
// file is generated instead of copied.

export default {
	type: 'component',
	name: 'MobileNavToggle',
	displayName: 'Mobile Nav Toggle',
	subComponentOf: 'MobileNav',
	description:
		'Hamburger button that opens/closes the mobile nav drawer. Reads open state from AppShell context automatically: does NOT accept isOpen or onOpenChange props. Renders nothing above the mobile breakpoint.',
	keywords: [
		'mobilenav',
		'drawer',
		'sidebar',
		'navigation',
		'hamburger',
		'menu',
		'offcanvas',
		'slideout',
		'navdrawer',
		'toggle'
	],
	group: 'Navigation',
	category: 'Navigation',
	props: [
		{
			name: 'children',
			type: 'Snippet',
			description: 'Custom content to render instead of the default hamburger icon.'
		},
		{
			name: 'label',
			type: 'string',
			description: 'Accessible label for the toggle button.',
			default: "'Open navigation'"
		}
	]
};
